### ISSUE TITLE
Add `for-compiler:` to `layer:` node to include/exclude layer from build for a compiler toolchain

### ISSUE THREAD

**Issue by VladimirUmek** [Open-CMSIS-Pack/devtools#1010]
I have a project that contains multiple target layers. One target layer cannot be compiled with GCC because its Startup component is missing for GCC (no support is provided).

```yml
project:
  layers:
    - layer: ./Layer/Target/CM55_VHT/Target.clayer.yml
      for-context: +CM55
      for-compiler: AC6
```
Node `for-compiler:` would prevent a layer build for GCC.
