### ISSUE TITLE
Linker `define` should trigger the linker script preprocessing

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1037]
When under the `linker` node the `define` is specified but `regions` is not specified:
```
linker:
  - script: linker_script.sct
    define:
      - XIP_BOOT_HEADER_ENABLE: 1
```
the linker script preprocessing should still be triggered.
