### ISSUE TITLE
[csolution] *.cbuild.yml files - add pack ID and pack path for device and board information

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1111]
**Describe The Problem To Be Solved**
At this point (csolution 2.1.0) the generated `<context>.cbuild.yml` files do not contain information about the packID and pack path where the board and/or device information is taken from unlike for components. 

** Suggest A Solution**
Extend the device node with pack and path entries.
```
device:
  id: MyVendor::MyDevice
  pack: MyVendor::MyDFP@1.0.0
  path: ${CMSIS_PACK_ROOT}/MyVendor/MyDevice_DFP/1.0.0
```

Extend the board node with pack and path entries.
```
board:
  id: MyVendor::MyBoard
  pack: MyVendor::MyBSP@1.0.0
  path: ${CMSIS_PACK_ROOT}/MyVendor/MyBoard_BSP/1.0.0
```

**Comment by brondani** [comment]
@jkrech The suggested nodes are not yaml compliant, nested mappings are not allowed. Please suggest a different structure.
For example:
``` yml
device:
  id: MyDevice
  pack: MyVendor.MyDFP@1.0.0
  path: ${CMSIS_PACK_ROOT}/MyVendor/MyDFP/1.0.0
```
