### ISSUE TITLE
Implement Simplified Generator Proposal

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1112]
The revised proposal can be found here:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Simplified%20Generator%20Proposal.md

Please give feedback and comments on this proposal in this issue.

**Comment by jkrech** [comment]
We intentionally moved away from command line arguments and give the generator access to all pre-processed information.
Since we generate absolute paths in *.cbuild-gen.yml people had suggested to generate these files into the `intdir`.

**Comment by jkrech** [comment]
Further discussion suggests, that the `generator directory` seems like a good place to store the files
```
<csolution-name>.cbuild-gen-idx.yml
and
<context>.cbuild-gen.yml
```
This way these "input files" for the "generator-bridge" stay with the "output files" generated by the "generator-bridge" as well as the "generator".

There is a proposal to extend the content of the `<csolution-name>.cbuild-idx.yml` specifying a list of contexts that share the same `generator directory` 

see: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Simplified%20Generator%20Proposal.md#additions-to-cbuild-gen-idxyml-and-cbuild-idxyml

```
  generators:
    - id: STM32CubeMX
      for-context: <list of context types>
      output: <directory for generator output>
      cgen-dirs:
        - path: <cgen location>
          for-project-part: <secure | non-secure | processor-core<x> > 
```
