### ISSUE TITLE
Access sequence $Dname$ is empty in project selecting board

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#1184]
**Describe the bug**

Given a `.csolution.yml` like
```
solution:
  target-types:
    - type: board
      board: <some board>
````

Then using access sequence `$Bname$` correctly expands to the board name, but `$Dname$` expands to empty. 

**Expected behavior**

It is expected that `$Dname$` expands to the name of the device mounted on the selected board. E.g., the device name is used for device specific files under RTE. To reference them the `$Dname$` would be required as used internally in RTE Model.
