### ISSUE TITLE
Dname and Bname are reflected differently in file system and access sequences

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#1185]
**Describe the bug**

Given a `.csolution.yml` like:
```
solution:
  packs:
    - pack: ARM::V2M_MPS3_SSE_300_BSP

  target-types:
    - type: MPS3
      board: V2M-MPS3-SSE-300-FVP

  build-types:
    - type: Debug
```

Then we end up with two device folders created automatically:
```
RTE
  _Debug_MPS3
  Device
    SSE_300_MPS3
      regions_V2M_MPS3_SSE_300_FVP.h
    SSE-300-MPS3
      RTE_Device.h
        :
```

The access sequence `$Bname$` evaluates to `V2M-MPS3-SSE-300-FVP`.
I.e., in some places the dash (`-`) is replaced by an underscore (`_`).
Hence, the access sequences do not match the file system. And the file system contains a mixture.

**Expected behavior**

It is expected that the file system uses consistent naming and access sequences to reflect the naming to allow file access.
