### ISSUE TITLE
Potential issue: access sequence expands to `//` in a pathname

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1196]
Potential problem with path names as an access sequence expands to `//` in a pathname.

**To Reproduce**
Attached SimpleTZ example uses a shared directory for debug and release builds configured with `output-dirs:`
```
  output-dirs:
    outdir: ./out/$TargetType$/
```
[SimpleTrustZone.zip](https://github.com/Open-CMSIS-Pack/devtools/files/13334666/SimpleTrustZone.zip)

In this case `CM33ns.Debug+AVH.cbuild.yml` contains:
```
    - group: CMSE Library
      files:
        - file: ../out/AVH//CM33_s_CMSE_Lib.o
```

**Expected behavior**
```
        - file: ../out/AVH/CM33_s_CMSE_Lib.o
```

**Environment (please complete the following information):**
- csolution 2.2.0 pre-release
- Windows

**Comment by brondani** [comment]
@ReinhardKeil We don't see the reported issue, can you please check again how to reproduce it?

This is the cbuild.yml file in two different Windows PCs:
```
build:
  generated-by: csolution version 2.2.0-extgen3
  ...
  groups:
  ...
    - group: CMSE Library
      files:
        - file: ../out/AVH/CM33_s_CMSE_Lib.o
```
