### ISSUE TITLE
[cbuild-idx] Invalid schema definition

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1207]
The schema for the [cbuild-idx](https://github.com/Open-CMSIS-Pack/devtools/blob/ab7ac4632896a602b92b0b86a1d1f8b823b64ff1/tools/projmgr/schemas/cbuild-idx.schema.json#L12) seems to be invalid as it requires a field `build-idx` which is not defined in the schema.
Generated index file however, comprises this field :
e.g.
```yaml
 build-idx:
  generated-by: csolution version 2.1.0
  csolution: hello.csolution.yml
  cprojects:
    - cproject: hello.cproject.yml
  cbuilds:
    - cbuild: hello.Debug+B-U585I-IOT02A.cbuild.yml
      project: hello
      configuration: .Debug+B-U585I-IOT02A
    - cbuild: hello.Release+B-U585I-IOT02A.cbuild.yml
      project: hello
      configuration: .Release+B-U585I-IOT02A
```
