### ISSUE TITLE
`selected-by:` in `*.cbuild-pack.yml` file unclear

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1263]
**Describe The Problem To Be Solved**

The current implementation of `*.cbuild-pack.yml` file only records the explicit `pack:` statements. However in principal, packs are also selected by an `device:`, `board:`, or `component:` depending on the load strategy.

The content of attached example is:
[DualCore.zip](https://github.com/Open-CMSIS-Pack/devtools/files/13874313/DualCore.zip)

It can be generated with: 
```
csolution convert HelloWorld.csolution.yml --load all
```
and produces this `*.cbuild-pack.yml` file:
```
cbuild-pack:
  resolved-packs:
    - resolved-pack: ARM::CMSIS@6.0.0
    - resolved-pack: NXP::FRDM-K32L3A6_BSP@16.0.0
      selected-by:
        - NXP::FRDM-K32L3A6_BSP@16.0.0
    - resolved-pack: NXP::K32L3A60_DFP@16.0.0
      selected-by:
        - NXP::K32L3A60_DFP@16.0.0
```

**Suggest A Solution**

While I believe the current information is useful, it might be expanded in future versions.  For now, I suggest to change the name of `selected-by:` to `selected-by-pack:`.  This allows for future extensions where `selected-by-device:`, etc. could be introduced.

```
cbuild-pack:
  resolved-packs:
    - resolved-pack: ARM::CMSIS@6.0.0
    - resolved-pack: NXP::FRDM-K32L3A6_BSP@16.0.0
      selected-by-pack:
        - NXP::FRDM-K32L3A6_BSP@16.0.0
    - resolved-pack: NXP::K32L3A60_DFP@16.0.0
      selected-by-pack:
        - NXP::K32L3A60_DFP@16.0.0
```
