### ISSUE TITLE
Rework execution of programs during build

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1358]
**The Problem To Be Solved**
The `execute` command proposal under [Pre/Post build steps](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#prepost-build-steps) does not support `input:` and `output:` nodes. These nodes are useful to generate dependencies.  It would therefore indirectly specify a pre/post build step.

**Suggest A Solution**
A reworked proposal is here: https://github.com/brondani/devtools/blob/proposals/cmakelists/v0.9.3/tools/projmgr/docs/CMakeListsProposal/CMakeListsProposal.md#7-prepost-build-steps

For example a web server may need a compressed image that could be generated with:

```yml
project:
  executes:
    - execute: Compress Web Image 
      run: fcarm    # a tool that compresses web images into a single c source file
      input: 
        - index.htm
        - ad.cgi
        - ad.cgx
        - image.png
      output:
        - web-image.c              # generated output file

   groups:
     - group: web-image
       files:
         - file: web-image.c     # input file to compiler
```

Open questions from initial proposal [Pre/Post build steps](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#prepost-build-steps):

  - Is `os:` required to execute different commands based on an host operating system.  Which `os` strings should be pre-defined (Linux, Linux-X86, Linux-Arm, Mac, Win)?
  - Is `stop:`  required?  Alternatively we could stop when an output could not be generated. In above example it could stop when `web-image.c` failed to generate.
