### ISSUE TITLE
Extended `cbuild setup` command to identify compatible layers for Reference Examples

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1379]
**Problem To Be Solved**

With Reference Application Examples (RAE), it is possible to ship layers in packs that are selected by the user. 
This was described in the [TRM on 2024-03-05: slides 5 - 7](https://linaro.atlassian.net/wiki/spaces/CMSIS/pages/29189701665/Open-CMSIS-Pack+Technical+Meeting+2024-03-05).

**Solution**

To enable this workflow, the `cbuild setup` command should be extended for RAE as described in the following:

When a `target-type:` of a RAE has missing `variables:`, this should be detected by the first `csolution` invocation that is started by `cbuild setup`. In this case perform the following additional step:

- run command that is similar to `csolution list layer`
   - this should generate additional information in `*.cbuild-idx.yml`
   - this command should use `--load all` to ensure that all installed packs are scanned for layers.

```yml
build-idx:
  generated-by: csolution version 2.4.0
  cdefault: cdefault.yml
  csolution: fxls8962.csolution.yml
  configurations:
    - configuration:
      target-type: LPCXpresso54114
      variables:
        - Board-Layer:  ./layer/board/frdmk22f/frdmk22f.clayer.yml
        - Shield-Layer: ./layer/shield/agmp03/agmp03.clayer.yml
      settings:
        - set: Bus.SPI (FXLS8962 SPI Bus - Jumper configuration: I2C/SPI=SPI)
        - set: Bus.SPI (FXAS21002 SPI Bus - Jumper configuration: I2C/SPI=SPI)

    - configuration:
      target-type: LPCXpresso54114
      variables:
        - Board-Layer:  ./layer/board/frdmk22f/frdmk22f.clayer.yml
        - Shield-Layer: ./layer/shield/fxls8962/fxls8961.clayer.yml
```

**Comment by soumeh01** [comment]
I'd like to clarify something or rather ask questions. 

1. Does it make sense to organize configurations based on the target types? Would it enhance usability to arrange them according to ease of use, for e.g.

```
build-idx:
  generated-by: csolution version 2.4.0
  cdefault: cdefault.yml
  csolution: fxls8962.csolution.yml
  configurations:
    - target-type: LPCXpresso54114
      configuration:
        variables:
          - Board-Layer:  ./layer/board/frdmk22f/frdmk22f.clayer.yml
          - Shield-Layer: ./layer/shield/agmp03/agmp03.clayer.yml
        settings:
          - set: Bus.SPI (FXLS8962 SPI Bus - Jumper configuration: I2C/SPI=SPI)
          - set: Bus.SPI (FXAS21002 SPI Bus - Jumper configuration: I2C/SPI=SPI)

      configuration:
        variables:
          - Board-Layer:  ./layer/board/frdmk22f/frdmk22f.clayer.yml
          - Shield-Layer: ./layer/shield/fxls8962/fxls8961.clayer.yml

    - target-type: frdmk22f_agmp03
      configuration:
        variables:
          - Board-Layer: ../../../../../boards/frdmk22f/frdmk22f.clayer.yml
          - Shield-Layer: ../../../../../shields/agmp03/agmp03.clayer.yml
        settings:
          - set: Bus.I2C-Alt (FXLS8962 Alternate I2C Bus - Jumper configuration: I2C/SPI=I2C, I2C=I2C1)
          - set: Bus.I2C-Alt (FXAS21002 Alternate I2C Bus - Jumper configuration: I2C/SPI=I2C, I2C=I2C1)
          - set: Bus.I2C-Alt (MPL3115 Alternate I2C Bus - Jumper configuration: I2C/SPI=I2C, I2C=I2C1)
          - set: Bus.I2C-Alt (MAG3110 Alternate I2C Bus - Jumper configuration: I2C/SPI=I2C, I2C=I2C1)
```

2. Additionally, another question I have is: Does the settings node enclose all the consolidated connection settings for listed layers? Considering each layer has its own settings, would it be more logical to list settings per layer, for e.g.

```
configuration:
  variables:
    - Board-Layer:  ./layer/board/frdmk22f/frdmk22f.clayer.yml
      settings:
        - set: set1.select1 (connect A - set 1 select 1)
    - Shield-Layer: ./layer/shield/agmp03/agmp03.clayer.yml
      settings:
        - set: Bus.SPI (FXLS8962 SPI Bus - Jumper configuration: I2C/SPI=SPI)
        - set: Bus.SPI (FXAS21002 SPI Bus - Jumper configuration: I2C/SPI=SPI)
```
