### ISSUE TITLE
cbuild setup - error status reporting

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1385]
**The Problem To Be Solved**

The `cbuild setup` command is also used by the web infra structure to display examples that can build correctly (see #1177 and #1384).

To simplify this web infra structure, it might be beneficial that the file `cbuild-idx.yml` should also contain the error status. 
@acabarbaye please comment on this.

Today `cbuild setup` reports the error status already with exit status on the console with:
```
error cbuild: error generating build files
error cbuild: exit status 1
```

**Suggest A Solution**

IMHO, there are two different ways to report errors in `cbuild-idx.yml`

Solution 1: one `error` status at the end of the file.
```
build-idx:
  generated-by: csolution version 2.2.1
  cdefault: ${CMSIS_COMPILER_ROOT}/cdefault.yml
  csolution: TestM85.csolution.yml
  cprojects:
    - cproject: Project/Project.cproject.yml
  cbuilds:
    - cbuild: Project/Project.Debug+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Debug+SSE-310-MPS3_FVP
    - cbuild: Project/Project.Release+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release+SSE-310-MPS3_FVP
    - cbuild: Project/Project.Release2+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release2+SSE-310-MPS3_FVP
  errors: true
```

Solution 2: if this is easier one `error` status per project context.

```
build-idx:
  generated-by: csolution version 2.2.1
  cdefault: ${CMSIS_COMPILER_ROOT}/cdefault.yml
  csolution: TestM85.csolution.yml
  cprojects:
    - cproject: Project/Project.cproject.yml
  cbuilds:
    - cbuild: Project/Project.Debug+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Debug+SSE-310-MPS3_FVP
      errors: true
    - cbuild: Project/Project.Release+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release+SSE-310-MPS3_FVP
      errors: true
    - cbuild: Project/Project.Release2+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release2+SSE-310-MPS3_FVP
      errors: true
```

**Comment by soumeh01** [comment]
In considering the data utilization aspect, I am in favor of solution 2 due to its provision of context-specific error statuses. Additionally, I propose extending solution 2 to include the 'packs-missing' node for further enhancement and eliminating it from <context>.cbuild.yml.

```
build-idx:
  generated-by: csolution version 2.2.1
  cdefault: ${CMSIS_COMPILER_ROOT}/cdefault.yml
  csolution: TestM85.csolution.yml
  cprojects:
    - cproject: Project/Project.cproject.yml
  cbuilds:
    - cbuild: Project/Project.Debug+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Debug+SSE-310-MPS3_FVP
      errors: true
      packs-missing:
        - pack: ARM::CMSIS@5.9.0
        - pack: NXP::K32L3A60_DFP@16.0.0
    - cbuild: Project/Project.Release+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release+SSE-310-MPS3_FVP
    - cbuild: Project/Project.Release2+SSE-310-MPS3_FVP.cbuild.yml
      project: Project
      configuration: .Release2+SSE-310-MPS3_FVP
      errors: true
      packs-missing:
        - pack: ARM::CMSIS@5.9.0
```
