### ISSUE TITLE
Should `cbuild setup` also create `.clangd` for setting up Intellisense?

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1400]
**The Problem To Be Discussed**
Currently `cbuild setup` generates `compile_commands.json` for Intellisense in the `tmp` directory for the related context.

In VS Code using the CLang intellisense engine, there is also a file in the project root named `.clangd`. In some cases this file seems to contain define settings that communicate architecture specific defines. Such defines are used in CMSIS header files, so it is likely that intellisense fails without it.

For example a project targeting a Cortex-M85 contains in `clangd` this:

```
CompileFlags:
  CompilationDatabase: c:\Test\Test2\TestM85\tmp\Project\SSE-310-MPS3_FVP\Release
  Add:
    - '-D_ILP32=1'
    - '-D_USE_STATIC_INLINE=1'
    - '-D__APCS_32__=1'
    - '-D__ARMCC_VERSION=6210000'
    - '-D__ARMCOMPILER_VERSION=6210000'
    - '-D__ARMEL__=1'
    - '-D__ARM_32BIT_STATE=1'
    - '-D__ARM_ACLE=200'
    - '-D__ARM_ARCH=8'
    - '-D__ARM_ARCH_8_1M_MAIN__=1'
    - '-D__ARM_ARCH_EXT_IDIV__=1'
       :
```
My questions are therefore:
 - should the file `.clangd` generated by the `cbuild setup`?
 - is `.clangd` working across the different intellisense engines?
 - are settings in file `.clangd` compiler specific?
