### ISSUE TITLE
handling of relative paths with variables

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1401]
**Describe the bug**
A csolution project that uses sub-directories for cproject.yml files needs proper handling of variables.

**To Reproduce**
Take the following structure on disk:
```
.\USB.csolution.yml
.\Device\HID.cproject.yml
.\Layer\Board\MyBoard.clayer.yml
```

And this project:
```yml
solution:
  target-types:
    - type: xxx
      variables:
        - Board-Layer: .\Layer\Board\MyBoard.clayer.yml

  projects:
    - project: Device/HID.cproject.yml
```

```yml
project:
  layers:
    - layer: $Board-Layer$
```

Currently this fails, as the directory relative to `csolution.yml` is used in `cproject.yml` that has a different relative location.

**Expected behavior**
The project should translate.  A potential solution: convert relative paths that are assigned to variables internally to absolute paths.

**Environment (please complete the following information):**
- CMSIS-Toolbox 2.3.0-dev0
- MDK Middleware USB example
- Windows 11
