### ISSUE TITLE
cbuild-idx.yml does not expand variables

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1414]
**Describe the bug**
For layers, the cbuild-idx.yml does not expand variables

**To Reproduce**
Use the USB example with layers in the `csolution.yml`.

```yml
  target-types:
    - type: B-U585I-IOT02A
      board: STMicroelectronics::B-U585I-IOT02A
      variables:
        - Board-Layer: /Users/.../AppData/Local/Arm/Packs/Keil/B-U585I-IOT02A_BSP/2.0.0-dev0/Layers/IoT/Board.clayer.yml
```

The output in `cbuild-idx.yml` is:

```yml
build-idx:
  generated-by: csolution version 2.3.0-dev0
  cdefault: cdefault.yml
  csolution: USB.csolution.yml
  cprojects:
    - cproject: Device/HID/HID.cproject.yml
      clayers:
        - clayer: Device/HID/$Board-Layer$
```

**Expected behavior**

```yml
  cprojects:
    - cproject: Device/HID/HID.cproject.yml
      clayers:
        - clayer: /Users/.../AppData/Local/Arm/Packs/Keil/B-U585I-IOT02A_BSP/2.0.0-dev0/Layers/IoT/Board.clayer.yml
```

**Environment (please complete the following information):**

- solution version 2.3.0-dev0
- OS: Windows

**Comment by jkrech** [comment]
One remark: The variables most likely are context (target-type) specific.
This would require the variable definition to be added to the context/configuration information.

**Comment by ReinhardKeil** [comment]
@jkrech, you are correct - it is only relevant when the context is known.  Perhaps the layer information should be added under `cbuilds:` that list all the context. However it is not a bug.

**Comment by jkrech** [comment]
We could display the variable definitions only?
```
cbuilds:
  -cbuild: Device/HID/HID.Debug+B-U585I-IOT02A.cbuild.yml
    project: HID
    configuration: .Debub+B-U585I-IOT02A
    variables:
      - Board-Layer: /Users/.../AppData/Local/Arm/Packs/Keil/B-U585I-IOT02A_BSP/2.0.0-dev0/Layers/IoT/Board.clayer.yml
```
