### ISSUE TITLE
`[csolution/cbuild]` all contexts present in cbuild-idx.yml even if a particular context was selected

### ISSUE THREAD

**Issue by acabarbaye** [Open-CMSIS-Pack/devtools#1426]
**Describe the bug**
This is closely related to https://github.com/Open-CMSIS-Pack/devtools/issues/1210

cbuild/csolution were run for a particular context (here FRDM-K32L3A6.Debug+FRDM-K32L3A6):

the following is the content of the `cbuild-idx.yml` and all contexts are referenced; not just the one selected.

```yaml
build-idx:
  generated-by: csolution version 2.2.1
  csolution: ../workspace/workspace/Blinky_FRDM-K32L3A6/Blinky.csolution.yml
  cprojects:
    - cproject: ../workspace/workspace/Blinky_FRDM-K32L3A6/FRDM-K32L3A6.cproject.yml
  cbuilds:
    - cbuild: FRDM-K32L3A6.Debug+FRDM-K32L3A6.cbuild.yml
      project: FRDM-K32L3A6
      configuration: .Debug+FRDM-K32L3A6
    - cbuild: FRDM-K32L3A6.Release+FRDM-K32L3A6.cbuild.yml
      project: FRDM-K32L3A6
      configuration: .Release+FRDM-K32L3A6
```

from previous unrelated builds, other context's artefacts are also present in the output folder and so, it is impossible to distinguish from the listing in the index file what artefacts are the output of the job we just ran and which ones are the result of previous jobs

**Expected behavior**
Only list the data related to the context selected and job performed

**Environment (please complete the following information):**

cbuild 2.2
