### ISSUE TITLE
Implement access sequence $SolutionDir$ across all levels

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1428]
**Describe The Problem To Be Solved**
The access sequence $SolutionDir$ cannot be used in `*.clayer.yml` file. 

**Suggest A Solution**
It should be possible to use $SolutionDir$ in every YML input file.  Check also for restrictions on other access sequences.

**Comment by brondani** [comment]
`$SolutionDir()$` is already supported as documented in [Access Sequences](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#access-sequences), regardless of being in csolution.yml, cproject.yml or clayer.yml files.

Given the comments from the above mentioned related GH issue https://github.com/Open-CMSIS-Pack/devtools/issues/1429, it seems what is required is to support `$SolutionDir()$` in `variables`, for example:
```yml
solution:
  variables:
    - Board-Layer: $SolutionDir()$/layers/board.clayer.yml
---
project:
  layers:
    - layer: $Board-Layer$
```
