### ISSUE TITLE
Handling of relative paths with variables / layer paths delivered by cbuild setup

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1429]
**NOTE:** this was #1401

**Describe the bug**
A csolution project that uses sub-directories for cproject.yml files needs proper handling of variables.

**To Reproduce**
Take the following structure on disk:
```
./USB.csolution.yml
./Device/HID.cproject.yml
./Layer/Board/MyBoard.clayer.yml
```

And this project:
```yml
solution:
  target-types:
    - type: xxx
      variables:
        - Board-Layer: ./Layer/Board/MyBoard.clayer.yml

  projects:
    - project: Device/HID.cproject.yml
```

```yml
project:
  layers:
    - layer: $Board-Layer$
```

Currently this fails, as the directory relative to `csolution.yml` is used in `cproject.yml` that has a different relative location.

----

A similar problem exists for the paths to layers reported by `cbuild setup`. The intend here is that a user can copy the paths from the `*.cbuild-idx.yml` file to the `*.csolution.yml` file. Currently the path is reported as absolute path which makes the project dependent on a host computer. 

**Expected behavior**
The project should be independent from a host computer. Potential solutions:
 - convert relative paths that are assigned to variables internally to absolute paths.
 - implement an access sequence for `$CMSIS_PACK_ROOT$` and output this as part of cbuild setup

**Environment (please complete the following information):**
- CMSIS-Toolbox 2.3.0-dev0
- MDK Middleware USB example
- Windows 11

**Comment by ReinhardKeil** [comment]
Maybe this is an solution:

```yml
solution:
  target-types:
    - type: xxx
      variables:
        - Board-Layer: $SolutionDir$\Layer\Board\MyBoard.clayer.yml

  projects:
    - project: Device/HID.cproject.yml
```

**Comment by jkrech** [comment]
This last suggestion would be enabled by this issue https://github.com/Open-CMSIS-Pack/devtools/issues/1428
The `*.cbuild-idx.yml` should use the access sequence in it's output already.

**Comment by brondani** [comment]
@ReinhardKeil @jkrech What was the outcome of https://github.com/Open-CMSIS-Pack/devtools/issues/1413#issuecomment-2031298724?
I had the impression the suggested access sequence `$PackDir(<vendor>::<name>[@version])$` was more consistent for input files. Are we giving it up in benefit of a new access sequence `$CMSIS_PACK_ROOT$` that is actually very similar to the environment variable `${CMSIS_PACK_ROOT}` that we use in output files? It sounds confusing.

**Comment by jkrech** [comment]
Yes, I think we don't need an access sequence representing for the ${CMSIS_PACK_ROOT} environment variable value or the default location in case the variable is not set.

The proposal for extending the `*.cbuild-idx.yml` file is here: https://github.com/Open-CMSIS-Pack/devtools/issues/1464
and specified here: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#configurations

```
  configurations:
    - target-type: B-U585I-IOT02A
      target-configurations:
        - configuration:
            - variables:
                - Board-Layer:
                  value: /Users/.../Arm/Packs/Keil/B-U585I-IOT02A_BSP/2.0.0-dev0/Layers/IoT/Board.clayer.yml
```

For consistency with the `*.cbuild.yml` references into the CMSIS_PACK_ROOT the value could be better expressed like this:
```
                  value: ${CMSIS_PACK_ROOT}$/Keil/B-U585I-IOT02A_BSP/2.0.0-dev0/Layers/IoT/Board.clayer.yml
```

Assuming that the user wants to use a clayer as read-only reference into the pack via the `layer:` node in the `*.cproject.yml` input YAML file, I would recommend the use of a pack specific access sequence (optionally with or without a version)

```
  $Pack(Keil::B-U585I-IOT02A_BSP@2.0.0-dev0)$
```

Using the latter syntax in the `*.cbuild-idx.yml` may be confusing to people who do not expect any use of variables or access sequences in the `*.cbuild.yml` as they are targeted at consumers without any knowledge of the csolution processing.
