### ISSUE TITLE
[projmgr] csolution usage of local_repository.pidx packs for convert, list packs, list components

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/devtools#1430]
**Describe the bug**
Packs coming from `local_repository.pidx` is inconsistently handled for `convert`, `list packs`, `list components`

**To Reproduce**
toolbox, currently last commit:
```bash
csolution 2.3.0+p1-gd8c10078 (C) 2024 Arm Ltd. and Contributors
```

csolution:
```yml
solution:
    target-types:
        - type: cm33
          device: ARM::ARMCM33
    build-types:
        - type: debug
          compiler: GCC
    projects:
        - project: sw.cproject.yml
    packs:
        - pack: ARM::Cortex_DFP
        - pack: ARM::CMSIS
```

cproject:
```yml
project:
    components:
        - component: ARM::CMSIS:CORE
```

CMSIS_PACK_ROOT:
```
ARM.CMSIS.5.9.0 installed
ARM.Cortex_DFP.1.0.0 installed
ARM.CMSIS.6.0.0 via local_repository.pidx
```

**Expected behavior**

# csolution list packs
This command seems to be slightly odd.
It lists all three packs:
```bash
$ csolution list packs
ARM::CMSIS@6.0.0 (...SOMEWHERE.../armcmsis600/ARM.CMSIS.pdsc)
ARM::CMSIS@5.9.0 (...PACK_ROOT.../ARM/CMSIS/5.9.0/ARM.CMSIS.pdsc)
ARM::Cortex_DFP@1.0.0 (...PACK_ROOT.../ARM/Cortex_DFP/1.0.0/ARM.Cortex_DFP.pdsc)
```
The `ARM.CMSIS.5.9.0` is unexpected here since 6.0.0 is newer

# csolution list components
This command seems to work as expected, it lists components only from `ARM::CMSIS@6.0.0` and `ARM::Cortex_DFP@1.0.0`.
I.e. the "older" `ARM::CMSIS@5.9.0` is not read here since we are not using "--load all"

```bash
$ csolution list components
ARM::CMSIS Driver:CAN:Custom@1.0.0 (ARM::CMSIS@6.0.0)
... snip ...
ARM::Device:IRQ Controller:GIC@1.2.0 (ARM::CMSIS@6.0.0)
ARM::Device:Startup&C Startup@1.2.0 (ARM::Cortex_DFP@1.0.0)
ARM::Device:Startup&C Startup@2.2.0 (ARM::Cortex_DFP@1.0.0)
```

# csolution convert
For the different situations, there are a few different behaviours:

1. `no cbuild-pack.yml` -> `Issue`
	The csolution.yml `pack: ARM::CMSIS` is resolved to `ARM::CMSIS@5.9.0` for components, expected was `ARM::CMSIS@6.0.0`
2. `cbuild-pack.yml locking ARM::CMSIS@6.0.0` -> `OK` 
	The command correctly now resolves csolution.yml `pack: ARM::CMSIS` to `ARM::CMSIS@6.0.0`
3. `no cbuild-pack.yml` and `ARM::CMSIS@6.0.0` explicitly referenced in csolution.yml -> `Small issue`
	The command correctly now resolves csolution.yml `pack: ARM::CMSIS@6.0.0` to `ARM::CMSIS@6.0.0`
	But, the `cbuild-pack.yml` does not contain a `selected-by-pack` for the 6.0.0:
```yml
cbuild-pack:
  resolved-packs:
    - resolved-pack: ARM::CMSIS@6.0.0
    - resolved-pack: ARM::Cortex_DFP@1.0.0
      selected-by-pack:
        - ARM::Cortex_DFP
```
4. `no cbuild-pack.yml` and `no ARM.CMSIS.5.9.0 in CMSIS_PACK_ROOT` -> `Small issue`
	Identical to 3, The command correctly now resolves csolution.yml `pack: ARM::CMSIS@6.0.0` to `ARM::CMSIS@6.0.0`
	But, the `cbuild-pack.yml` does not contain a `selected-by-pack` for the 6.0.0.

**Environment (please complete the following information):**
- Version csolution 2.3.0+p1-gd8c10078
- OS: Linux x86_64
