### ISSUE TITLE
Change base name of `*.cgen.yml` file when generator component is in `*.clayer.yml` file

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1445]
**The Problem To Be Solved**

A layer is usable independent of a project and may be used by several projects. When a generator component is  part of a clayer.yml file , the `*.cgen.yml` file should be therefore not use the base name of the `cproject.yml` but instead the base name of the related `clayer.yml` file.

**Suggest A Solution**
When a component uses a generator is part of the `clayer.yml` file, use the base name of the `*.clayer.yml` file.  Consider to extend the `cbuild-gen.yml` file with a key for the `cgen-file:`, for example:

```yml
build-gen-idx:
  generated-by: csolution version 2.3.0-dev0
  generators:
    - id: CubeMX
      output: C:/Test/USBD/Board/B_U585/STM32CubeMX/B-U585I-IOT02A
      device: STM32U585AIIx
      board: B-U585I-IOT02A
      project-type: single-core
      cbuild-gens:
        - cbuild-gen: C:/Test/USBD/tmp/HID/B-U585I-IOT02A/Debug/HID.Debug+B-U585I-IOT02A.cbuild-gen.yml
          project: HID
          configuration: .Debug+B-U585I-IOT02A
          cgen-file: C:/Test/USBD/Board/B_U585/STM32CubeMX/B-U585I-IOT02A/Board.cgen.yml
```

The `component` node in the `*.cbuild.yml` file also contains a reference to the `*.cgen.yml` file that needs also to reflect the fact that it is called from a layer.

```yml
    - component: Keil::Device:Startup@1.2.0
      condition: STM32U5 CMSIS
      from-pack: Keil::STM32U5xx_DFP@3.0.0-extgen0
      selected-by: Keil::Device:Startup
      generator:
        id: CubeMX
        path: C:/Test/USBD/Board/B_U585/STM32CubeMX/B-U585I-IOT02A/Board.cgen.yml   # instead of HID.cgen.yml
```

This example [USBD.zip](https://github.com/Open-CMSIS-Pack/devtools/files/14999785/USBD.zip) allows to duplicate the issue.

Call generator with:
```
csolution run HID.csolution.yml -g CubeMX -c .Debug
```
