### ISSUE TITLE
[csolution] Add `<file category="other" ...` from `<component>` to `<context>.cbuild.yml `

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1488]
**Describe The Problem To Be Solved**
Debugger shall read the list of [**Software-Component-Viewer-Description**](https://arm-software.github.io/CMSIS-View/latest/SCVD_Format.html) (aka: SCVD) files from components included in the loaded application . SCVD files are listed in the pdsc files under category="other".
E.g. ARM::CMSIS-RTX 
https://github.com/ARM-software/CMSIS-RTX/blob/main/ARM.CMSIS-RTX.pdsc#L452
```
        <!-- RTX system view description -->
        <file category="other"   name="RTX5.scvd"/>
```

Files from category "other" are currently not included in the `<context>.cbuild.yml` files
Specified here: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#file-structure-of-cbuildyml files node:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#files-of-a-component

```
    - component: ARM::CMSIS:RTOS2:Keil RTX5&Source@5.8.0
      condition: RTX5
      from-pack: ARM::CMSIS-RTX@5.8.0
      selected-by: ARM::CMSIS:RTOS2:Keil RTX5&Source@5.8.0
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS-RTX/5.8.0/RTX5.scvd
          category: other
```
