### ISSUE TITLE
*.cbuild.yml file only contains board information

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1510]
**Describe the bug**
When just a board is selected the *.build.yml file only contains board information.
The import in uVision IDE fails for such projects as the device cannot be identified.

**To Reproduce**
Use https://github.com/ReinhardKeil/usbd

```
build:
  generated-by: csolution version 2.4.0-devint1
  solution: ../USB_Device.csolution.yml
  project: HID.cproject.yml
  context: HID.Debug+B-U585I-IOT02A
  compiler: AC6
  board: B-U585I-IOT02A
  board-pack: Keil::B-U585I-IOT02A_BSP@2.0.0-dev1
  device-pack: Keil::STM32U5xx_DFP@3.0.0-dev0
```

**Expected behavior**
list also the `device:` that is behind the `board:`.
