### ISSUE TITLE
Workflow for Layer detection: missing information when no matching layers are available

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1537]
**Problem To Be Solved**
The layer detection workflow works as described in [Reference Applications - Usage](https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/ReferenceApplications.md). 

However, when no matching layer is detected, the `*.cbuild-idx.yml` file does not get updated.

**Steps to Reproduce**

Use the following repos:
- https://github.com/ReinhardKeil/USBD/tree/main
- https://github.com/ARM-software/MDK-Middleware/tree/main
- https://github.com/Open-CMSIS-Pack/pack-examples/tree/main

Register the development versions of the packs with `cpackget add <path-to-pdsc>` and verify setup with:

```
>cpackget list
I: Listing installed packs
I: ARM::CMSIS-Compiler@2.1.0
I: ARM::CMSIS-RTX@5.9.0
I: ARM::CMSIS-View@1.2.0
I: ARM::CMSIS@6.1.0
I: Keil::B-U585I-IOT02A_BSP@2.0.0-dev1 (installed via C:\w\pack-examples\B-U585-IOT02_BSP\Keil.
I: Keil::MDK-Middleware@8.0.0-dev (installed via C:\w\MDK-Middleware\Keil.MDK-Middleware.pdsc)
I: Keil::NUCLEO-U031R8_BSP@1.0.0-dev0 (installed via C:\w\pack-examples\NUCLEO-U031R8_BSP\Keil.NUCLEO-I: Keil::STM32U5xx_DFP@3.0.0-dev0 (installed via C:\w\pack-xamples\STM32U5xx_DFP\Keil.STM32U5xx_DFP.pdsc)
```

Run:
```
>cbuild setup USB_Device.csolution.yml --packs
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$

To resolve undefined variables, copy the settings from cbuild-idx.yml to csolution.yml
error cbuild: error generating build files
error cbuild: exit status 2
```

This is the correct layer detection. The file `USB_Device.cbuild-idx.yml` shows the valid setup.

```
  configurations:
    - target-type: B-U585I-IOT02A
      target-configurations:
        - configuration: 
          variables:
            - Board-Layer: ${CMSIS_PACK_ROOT}/Keil/B-U585I-IOT02A_BSP/2.0.0-dev1/Layers/IoT/Board.clayer.yml
              description: B-U585I-IOT02A Board setup for IoT
              path: ${CMSIS_PACK_ROOT}/Keil/B-U585I-IOT02A_BSP/2.0.0-dev1/Layers/IoT
              file: Board.clayer.yml
              copy-to: .Board/U585
```

**So far so good, but here is the problem:**

Change target in `*.csolution.yml` to a board where not compatible layer exists as shown below.

```
  target-types:
#    - type: B-U585I-IOT02A
#      board: B-U585I-IOT02A         # name of a target board with layer
#     variables:
#       - Board-Layer: $SolutionDir()$\Board\B-U585I-IOT02A\Board.clayer.yml

   - type: LPC55S69-EVK            # name of a target board with layer
     board: LPC55S69-EVK
#     variables:
#       - Board-Layer: $SolutionDir()$\Board\LPC55S69-EVK\Board.clayer.yml
```

Run:
```
>cbuild setup USB_Device.csolution.yml --packs
error csolution: undefined variables in USB_Device.csolution.yml:
  - $Board-Layer$

error csolution: board 'LPC55S69-EVK' was not found
error cbuild: error generating build files
error cbuild: exit status 1
```

The `*.cbuild-idx.yml` is unchanged, which means the IDE cannot detect that there is no compatible selection.

**Suggest A Solution**

Even in this case the `*.cbuild-idx.yml` needs to be updated and an error indicator should be included.

Consider to list all error messages, i.e. with:

```yml
build-idx:
  messages:
    - error: undefined variables in USB_Device.csolution.yml
      detail: $Board-Layer$
    - error: board 'LPC55S69-EVK' was not found
```
