### ISSUE TITLE
cbuild: invalid layer detection variables when pack is on a different drive

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1543]
**Describe the bug**
`cbuild setup` detects valid layers from packs and writes the configuration variables to `*.cbuild-idx.yml`. However the variables are invalid when the pack is on a different drive than the project. Also an absolute path should be used when the relative path is not within the solution directory.

**To Reproduce**
Use an example which requires layer detection and put it on a different drive than the pack with the layer. Run `cbuild setup *.csolution.yml` and examine the configuration variables in `*cbuild-idx.yml`.

You can also use the following project and pack to reproduce this:

Project:
[FileSystem.csolution.yml](https://github.com/ARM-software/MDK-Middleware/blob/main/Examples/FileSystem/FileSystem.csolution.yml):
 - add under `target-types`:
   - type: H743
   - board: STMicroelectronics::STM32H743I-EVAL

[File_Demo.cproject.yml](https://github.com/ARM-software/MDK-Middleware/blob/main/Examples/FileSystem/File_Demo/File_Demo.cproject.yml):
 - remove `provides: - CMSIS-RTOS2` (not needed with the upcoming CMSIS-Toolbox 2.5.0)

Pack:
[STM32H743I-EVAL_BSP](https://github.com/Open-CMSIS-Pack/pack-examples/blob/main/STM32H743I-EVAL_BSP/Keil.STM32H743I-EVAL_BSP.pdsc): install as local pack

Run `cbuild setup FileSystem.csolution.yml`

`FileSystem.cbuild-idx.yml` contains the following when the pack is on a different drive than the project:

```
  variables:
    - Board-Layer: $SolutionDir()$/
      description: STM32H743I-EVAL board setup for IoT
      file: Board.clayer.yml
      copy-to: Board/STM32H743I-EVAL
```
`Board-Layer:` is invalid and `path` is missing.

`FileSystem.cbuild-idx.yml` contains the following when the pack is on the same drive as the project:

```
  variables:
    - Board-Layer: $SolutionDir()$/../../../../Open-CMSIS-Pack/pack-examples/STM32H743I-EVAL_BSP/Layers/IoT/Board.clayer.yml
      description: STM32H743I-EVAL board setup for IoT
      path: ../../../../Open-CMSIS-Pack/pack-examples/STM32H743I-EVAL_BSP/Layers/IoT
      file: Board.clayer.yml
      copy-to: Board/STM32H743I-EVAL
```
`Board-Layer:` and `path` are correct however they use a relative path. An absolute path should be used when the relative path is not within the solution directory.

**Expected behavior**
Variables should be correct regardless if the pack is installed on a different drive than the project. Also an absolute path should be used when the relative path is not within the solution directory.

**Environment:**
- [cbuild]
- Version 2.4.0
- OS: Windows
