### ISSUE TITLE
[csolution] Should a generator `*.cgen.yml` file be listed as `clayer:` in the `*.cbuild-idx.yml` file

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1550]
I have a CMSIS Solution project with a global generator component in a clayer:

```
build-idx:
  generated-by: csolution version 2.4.0
  cdefault: cdefault.yml
  csolution: USB_Device.csolution.yml
  cprojects:
    - cproject: HID/HID.cproject.yml
      clayers:
        - clayer: Board/B-U585I-IOT02A/Board.clayer.yml
  cbuilds:
    - cbuild: HID/HID.Debug+B-U585I-IOT02A.cbuild.yml
      project: HID
      configuration: .Debug+B-U585I-IOT02A
      clayers:
        - clayer: Board/B-U585I-IOT02A/Board.clayer.yml
        - clayer: Board/B-U585I-IOT02A/CubeMX/Board.cgen.yml
    - cbuild: HID/HID.Release+B-U585I-IOT02A.cbuild.yml
      project: HID
      configuration: .Release+B-U585I-IOT02A
```

Internally to `csolution` the `generator` YML file is treated like a `layer` but the clayer files are referenced explicitly while the cgen file is implicitly associated with the component referencing the global generator ID.

```
- clayer: Board/B-U585I-IOT02A/CubeMX/Board.cgen.yml
```

Does this confuse people reading it or should we filter out the information in the cbuild-idx.yml?
