### ISSUE TITLE
[csolution] Classic generator bootstrap component files are not listed

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1560]
Take for example the attached solution [Blinky.zip](https://github.com/user-attachments/files/15820530/Blinky.zip) where the following component is present in the PDSC (a.k.a. bootstrap):
`Keil::Device:STM32Cube Framework:STM32CubeMX@1.0.1`
And the generated component is described in the GPDSC with a lower version:
`Keil::Device:STM32Cube Framework:STM32CubeMX@0.1.0`

In this scenario it would be expected that the bootstrap component does not get replaced because it has a greater version, however both components are added to *.cbuild.yml and the bootstrap component files are not listed:
```
    - component: Keil::Device:STM32Cube Framework:STM32CubeMX@0.1.0
      condition: STCubeMX
      from-pack: Keil::FrameworkCubeMX@1.0.0
      selected-by: Keil::Device:STM32Cube Framework:STM32CubeMX
      generator:
        id: STM32CubeMX
        from-pack: Keil::STM32F7xx_DFP@2.16.0
    - component: Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0
      condition: STM32F7 Framework CubeMX
      from-pack: Keil::STM32F7xx_DFP@2.16.0
      selected-by: Keil::Device:STM32Cube Framework:STM32CubeMX
      generator:
        id: STM32CubeMX
        from-pack: Keil::STM32F7xx_DFP@2.16.0
```
**Environment:**
- csolution
- Version 2.4.0
- OS: windows
