### ISSUE TITLE
cbuild setup --context-set should only pickup the first project 

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1562]
**The Problem To Be Solved**

For MDK-Middleware reference applications, several similar examples are delivered as part of one csolution file.
This is confusing as typically only one example will be used at a time.

**Suggest A Solution**
When the file `*.cbuild-set.yml` is missing, only the first example should picked-up.

To duplicate use MDK-Middleware example as described here:
https://github.com/Open-CMSIS-Pack/Create-Scalable-SW/blob/main/Demo/MDK-MW_RefApp.md

```
cbuild setup USB_Device.csolution.yml --context-set
```

Should generate only:
```
cbuild-set:
  generated-by: csolution version 2.5.0-devint1
  contexts:
    - context: HID.Debug+B-U585I-IOT02A
```
