### ISSUE TITLE
[csolution] add support for LicenseSet description added to the PDSC specification

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1567]
Describe The Problem To Be Solved
The Open-CMSIS-Pack-Spec has been extended with [LicenseSets](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_licenseSets_pg.html)
This meta information needs to be processed by csolution and show in the `*.cbuild.yml` files.

**Suggest A Solution**
Example: `USB_Device.csolution.yml` + `MassStorage.Debug+B-U585I-IOT02A.cbuild.yml`

```yml
    - license: <unknown>                                             # These components have Apache-2.0 license
      packs:
        - pack: ARM::CMSIS-Driver_STM32@1.0.0-dev0
      components:
        - component: Keil::CMSIS Driver:GPIO@1.0.0
        - component: Keil::CMSIS Driver:SPI@3.0.0
        - component: Keil::CMSIS Driver:USART@3.0.0
        - component: Keil::CMSIS Driver:USB Device@3.0.0
    - license: Apache-2.0
      packs:
        - pack: ARM::CMSIS-Compiler@2.1.0
        - pack: ARM::CMSIS-RTX@5.9.0
        - pack: ARM::CMSIS@6.1.0
        - pack: Keil::B-U585I-IOT02A_BSP@2.0.0-dev
        - pack: Keil::STM32U5xx_DFP@3.0.0-dev
      components:
```
