### ISSUE TITLE
Setting `cprjdir` to `$ProjectDir()$/foo` will expand to the wrong path

### ISSUE THREAD

**Issue by Torbjorn-Svensson** [Open-CMSIS-Pack/devtools#1570]
**Describe the bug**
When using a csolution file like this:

```yaml
solution:
  output-dirs:
    intdir: $ProjectDir()$/build/$BuildType$
    outdir: $ProjectDir()$/build/$BuildType$
    cprjdir: $ProjectDir()$/baz
  generators:
    base-dir: $ProjectDir()$/generated
  build-types:
    - type: debug
      compiler: GCC
  target-types:
    - type: main
  projects:
    - project: foo/bar.cproject.yml
```
The expected place for the .cprj files are in `foo/baz/`, but it will be incorrectly expanded to `../../foo/baz/` (expressed relative to the .csolution.yml file).

**To Reproduce**
1. Save the above as `app.csolution.yml`
2. Create a sub-directory called `foo`.
3. Create a minimal cproject.yml and save it to `foo/bar.cproject.yml`.
4. Run `csolution convert -s /absolute/path/to/app.csolution.yml`

**Expected behavior**
The .cprj files should be placed in `foo/baz/`.

**Environment (please complete the following information):**

- csolution
- Version 2.4.0, but same with current `main` branch
- OS: Linux, but I doubt that the OS matters here.

**Additional context**
