### ISSUE TITLE
Undefined layer variables should be allowed

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#1620]
**Describe the bug**
A generic project might have multiple layers where some are optional. For example, a sensor project might have a board layer and an optional shield layer. The sensor might be on the board or on the shield. The layer discovery will identify if besides the board layer also the shield layer is needed. Therefore, it should be possible to have a project with multiple layers using variables and when a variable is not defined the layer should be skipped. However `cbuild` fails if a layer variable is not specified.

**To Reproduce**
Solution (.csolution.yml):
```
    - type: board_only
      board: <board>
      variables:
        - Board-Layer:  <board_layer>.clayer.yml
    - type: board_with_shield
      board: <board>
      variables:
        - Board-Layer:  <board_layer>.clayer.yml
        - Shield-Layer: <shield_layer>.clayer.yml
```
Project using layers (.cproject.yml):
```
  layers:
    - layer: $Board-Layer$
      type: Board
    - layer: $Shield-Layer$
      type: Shield
```

Building the target `board_only` with `cbuild` fails with the error `Shield-Layer` variable undefined.

**Expected behavior**
A layer with an undefined variable should be treated as a non-existing layer and build should not fail.

**Environment:**
- [cbuild]
- Version 2.5.0-devint3
- OS: Windows

**Comment by brondani** [comment]
As far as I can see this is implemented precisely as specified in https://github.com/Open-CMSIS-Pack/devtools/issues/1379.
To achieve the enhancement that is being requested in this issue the mechanism's design must be reworked.

**Comment by jkrech** [comment]
As a consequence, 

```
  layers:
    - layer: ""
      type: shield
```

is a valid statement.

**Comment by ReinhardKeil** [comment]
@TeoMahnic please provide steps to replicate this issue.  What packs are used, what example?

**Comment by TeoMahnic** [comment]
**Used development packs**
- https://github.com/Open-CMSIS-Pack/Sensor-SDK-Example
- https://github.com/RobertRostohar/NXP_Sensor_SDK/tree/main/packs/MIMXRT1062_DFP
- https://github.com/RobertRostohar/NXP_Sensor_SDK/tree/main/packs/EVK-MIMXRT1060_BSP

**Steps to reproduce the issue**
1. Create a new example for **EVK-MIMXRT1060** board using **fxos8700** reference example.
2. After layer discovery, there are two valid configurations:
   - Using both _Board-Layer_ and _Shield-Layer_,
   - Using only _Board-Layer_.

The second one should also have a _Shield-Layer_ defined as an empty string (https://github.com/Open-CMSIS-Pack/devtools/issues/1620#issuecomment-2208776514).

**Comment by ReinhardKeil** [comment]
The IDE does not know the variable names. There is entry required `- Shield-Layer: ""` (see below).

This is the [fxos8700.csolution.yml](https://github.com/user-attachments/files/16909248/fxos8700.csolution.zip) file after the IDE configuration step (device + pack entries).  I removed some of the options.

```yml
build-idx:
  generated-by: csolution version 2.5.0+p23-g22e50476
  cdefault: cdefault.yml
  csolution: fxos8700.csolution.yml
  tmpdir: tmp
  configurations:
    - target-type: MIMXRT1062DVL6A
      target-configurations:
        - configuration: 
          variables:
            - Board-Layer: $SolutionDir()$/../../w/NXP_Sensor_SDK/packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer/Board.clayer.yml
              description: EVK-MIMXRT1060 Development Board
              path: C:/w/NXP_Sensor_SDK/packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer
              file: Board.clayer.yml
              copy-to: Board/EVK-MIMXRT1060
            - Shield-Layer: $SolutionDir()$/../../w/Sensor-SDK-Example/shields/agm01/Shield.clayer.yml
              description: FRDM-STBC-AGM01 Sensor Shield Board
              settings:
                - set: AGM01_FXOS8700.Enabled (FXOS8700 Sensor Enabled)
                - set: "AGM01_COMM_IF.I2C0 (FXOS8700 I2C0 Communication Interface - Jumper configuration: I2C/SPI=I2C, I2C=I2C0)"
              path: C:/w/Sensor-SDK-Example/shields/agm01
              file: Shield.clayer.yml
              copy-to: Shield/FRDM-STBC-AGM01
        - configuration: 
          variables:
            - Board-Layer: $SolutionDir()$/../../w/NXP_Sensor_SDK/packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer/Board.clayer.yml
              description: EVK-MIMXRT1060 Development Board
              settings:
                - set: FXOS8700_OnBoard.Enabled (EVK-MIMXRT1060 FXOS8700 On-Board Sensor Enabled - Add preprocessor define FXOS8700_ON_BOARD)
              path: C:/w/NXP_Sensor_SDK/packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer
              file: Board.clayer.yml
              copy-to: Board/EVK-MIMXRT1060
            - Shield-Layer: ""
```
