### ISSUE TITLE
Variable description in YAML files is not backward/forward compatible

### ISSUE THREAD

**Issue by edriouk** [Open-CMSIS-Pack/devtools#1665]
Currently **variables** node in YAML files does provide a **variable name** implicitly.
For instance the variable name in the following example is **Board-Layer**:
```
     variables:
         - Board-Layer: $SolutionDir()$/../../packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer/Board.clayer.yml
           description: EVK-MIMXRT1060 Development Board
           file: Board.clayer.yml
           copy-to: Board/EVK-MIMXRT1060
```
There are only three ways to parse such YAML:
1. Parser knows the complete list of variable names
   adding a variable needs to update **all** parsers, not only csolution one! => not backward/forward compatible
2. Variable name is taken from the very first element 
    some  YAML parsers may sort map elements in an arbitrary order (e.g. alphabetically) => this might not work properly 
3. The name-value variable pair is discovered as an element with an unknown key 
    introducing new properties to a variable will brake the discovery mechanism
      
Suggestion: use explicitly **name** and **value** keys:
```
     variables:
         - name: Board-Layer: 
           value: $SolutionDir()$/../../packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer/Board.clayer.yml
           description: EVK-MIMXRT1060 Development Board
           file: Board.clayer.yml
           copy-to: Board/EVK-MIMXRT1060
```
This approach: 
- makes parsing easier and stable
- ensures backward and forward compatibility
- is consistent with other YAML elements

**Comment by brondani** [comment]
Looking at the schema the layer variable key in `cbuild-idx.yml` must have the pattern `^.*-Layer$`
https://github.com/Open-CMSIS-Pack/devtools/blob/schemas/projmgr/2.5.0/tools/projmgr/schemas/common.schema.json#L995
For this reason it should be reasonably easy to parse and distinguish this key from other current or future siblings.

However I tend to agree the proposed change makes it easier to parse and we could go further and handle any variable, waiving the requirement of a `-Layer` suffix. But such change would potentially break compatibility, old and new nodes would be needed until the next major version increment.

**Comment by ReinhardKeil** [comment]
Today only two different layers are used:
  - Board-Layer
  - Shield-Layer

A potential way to solve this in the long run is:

```
     variables:
         - layer: Board
           path: $SolutionDir()$/../../packs/EVK-MIMXRT1060_BSP/boards/evkmimxrt1060/layer/Board.clayer.yml
           description: EVK-MIMXRT1060 Development Board
           file: Board.clayer.yml
           copy-to: Board/EVK-MIMXRT1060
```
