### ISSUE TITLE
csolution v2.5.0: cmse-lib issue with non-secure projects

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#1715]
Hi

I am using a application with a secure and a non-secure project.
I can build it with 2.4.0 toolbox, but not with 2.5.0 yet.

In the secure side, I don't see any main difference.

In the non-secure side, I got now these errors:

```
  | error csolution: context 'secure' referenced by access sequence 'cmse-lib' does not exist or is not selected
```
```
  | *** ERROR M204:
  |   Path not found: 'C:/xxx/non_secure/$cmse-lib(secure)!
```

I can see a difference in the generated cbuild.yml file:

- with 2.4.0:
```
    - group: Non-secure Callable Secure Code Library (nsc_lib)
      files:
        - file: ../secure/debug_IAR/secure_CMSE_Lib.o
          category: object
```

- with 2.5.0:
```
    - group: Non-secure Callable Secure Code Library (nsc_lib)
      files:
        - file: $cmse-lib(secure)$
          category: other
```
