### ISSUE TITLE
Access Sequence `$Pack()$` should find local packs in different drives

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1737]
Requested by @RobertRostohar:

The access sequence `$Pack(vendor::name)$` expands to `.` when it points to a path in a different drive, for example when a local pack is not in the same drive as the solution.
This concerns exclusively local development so producing a non-portable absolute path in this case can be tolerated.

**Comment by RobertRostohar** [comment]
Seems to work for `files:` but not for `add-path:` and `add-path-asm:`.

Test environment:
- OS: Windows
- `CMSIS_PACK_ROOT` located on C drive (C:\Arm\Packs)
- local pack `ARM::CMSIS-Driver` on C drive (C:\GitHub\Arm-software\CMSIS-Driver)
- local pack `Keil::MDK-Middleware` on D drive (D:\GitHub\Arm-software\MDK-Middleware

Test solution:
```
  packs:
    - pack: ARM::CMSIS
    - pack: ARM::CMSIS-Driver
    - pack: Keil::MDK-Middleware
```
Test project:
```
  add-path:
    - $Pack(ARM::CMSIS)$/CMSIS/RTOS2/Include
    - $Pack(ARM::CMSIS-Driver)$/Config
    - $Pack(Keil::MDK-Middleware)$/Components/FileSystem/Include
  add-path-asm:
    - $Pack(ARM::CMSIS)$/CMSIS/RTOS2/Include
    - $Pack(ARM::CMSIS-Driver)$/Config
    - $Pack(Keil::MDK-Middleware)$/Components/FileSystem/Include

  groups:
    - group: Source Files
      files:
        - file: $Pack(ARM::CMSIS)$/CMSIS/RTOS2/Source/os_systick.c
        - file: $Pack(ARM::CMSIS-Driver)$/NAND/NAND_MemBus.c
        - file: $Pack(Keil::MDK-Middleware)$/Components/FileSystem/Source/fs_version.c
```

Test solution/project on C drive (C:\Temp\Test)
Generated cbuild.yml shows correct `files:` but the `add-path` and `add-path-asm` is wrong for the packs that are on the same drive as the project (first two items). 
```
  add-path:
    - Arm/Packs/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include
    - GitHub/ARM-software/CMSIS-Driver/Config
    - D:/GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Include
  add-path-asm:
    - Arm/Packs/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include
    - GitHub/ARM-software/CMSIS-Driver/Config
    - D:/GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Include

  groups:
    - group: Source Files
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Source/os_systick.c
          category: sourceC
        - file: ../../../GitHub/Arm-software/CMSIS-Driver/NAND/NAND_MemBus.c
          category: sourceC
        - file: D:/GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Source/fs_sys.h
          category: header
        - file: D:/GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Source/fs_sys.c
          category: sourceC
```

Test solution/project on D drive (D:\Temp\Test)
Generated cbuild.yml shows correct `files:` but the `add-path` and `add-path-asm` is wrong. It seems that `CMSIS_PACK_ROOT` is not used and path on the same drive should be either relative or absolute with a driver letter.
```
  add-path:
    - C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Arm/Packs/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include
    - C:/Users/user/AppData/Local/Programs/Microsoft VS Code/GitHub/ARM-software/CMSIS-Driver/Config
    - GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Include
  add-path-asm:
    - C:/Users/user/AppData/Local/Programs/Microsoft VS Code/Arm/Packs/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include
    - C:/Users/user/AppData/Local/Programs/Microsoft VS Code/GitHub/ARM-software/CMSIS-Driver/Config
    - GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Include

  groups:
    - group: Source Files
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Source/os_systick.c
          category: sourceC
        - file: C:/GitHub/Arm-software/CMSIS-Driver/NAND/NAND_MemBus.c
          category: sourceC
        - file: ../../../GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Source/fs_sys.h
          category: header
        - file: ../../../GitHub/ARM-software/MDK-Middleware/Components/FileSystem/Source/fs_sys.c
          category: sourceC
```
