### ISSUE TITLE
Make api documentation available in `*.cbuild.yml`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1741]
**The Problem To Be Solved**

The `*.cbuild.yml` file makes the API headers available, but does not provide a direct link to the API documentation.

**Suggestion**

Add node `api-doc:` as shown below.  As the API has also a version, we could consider to add `version:` information to the header file too.

```yml
   - component: ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0
      condition: RTX5
      from-pack: ARM::CMSIS-RTX@5.9.0
      selected-by: CMSIS:RTOS2:Keil RTX5&Source
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include/cmsis_os2.h
          category: api
          api-doc: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Documentation/html/RTOS2/index.html
          version: 2.3.0
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS-RTX/5.9.0/Documentation/index.html
          category: doc
          version: 5.9.0
```

Reference: MCUTO-338
