### ISSUE TITLE
When changing the number of `execute:` nodes, a CMake error is output.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1757]
**Describe the bug**

When a `execute:` node is added or removed the number of CMake projects changes. This creates a CMake error when `--rebuild` is not used.

**To Reproduce**

Add or remove the following section in a `csolution.yml` file and execute `cbuild`

```
  executes:
    - execute: touch-main
      run: ${CMAKE_COMMAND} -E touch $output$
      output: 
        - $SolutionDir()$/Project/main.c
      always:
```

It outputs:

```
CMake Error:
  Running

   'C:/Users/reikei01/.vcpkg/artifacts/2139c4c6/tools.ninja.build.ninja/1.12.0/ninja.exe' '-C' 'C:/Test/Blank4/tmp' '-t' 'restat' 'build.ninja'

  failed with:

   ninja: error: failed recompaction: Permission denied
```

**Suggested solution**

Set the `rebuild` node to trigger a rebuild.

**Environment (please complete the following information):**

- Cbuild 2.5.0-17-g40fe18b
- OS: Windows
