### ISSUE TITLE
[csolution]: $SolutionDir()$ is not expanded when used in cproject.yml `layer:` node

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1765]
**Describe the bug**

In cproject.yml files, the `layer:` node seems not to accept classic access sequences.

**To Reproduce**

Use a reference application and change the `layers:` in the `cproject.yml` file as follows:

```
  layers:
#   - layer: $Board-Layer$                                           # works
#   - layer: ../Board/B-U585I-IOT02A/Board.clayer.yml                # works
    - layer: $SolutionDir()$/Board/B-U585I-IOT02A/Board.clayer.yml   # fails
      type: Board
```

**Environment:**

- csolution 2.5.0+p43-gca002acf
- OS: Windows 11
