### ISSUE TITLE
Header files that are excluded by condition should not be in *.cbuild.yml files

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1800]
**Describe the bug**

The attached project is configured without TrustZone (this should be anyway default, but the cproject.yml specifies this explicit).

The CMSIS.pdsc defines:

```xml
   <component Cclass="CMSIS" Cgroup="CORE" Cversion="6.1.0"  condition="ARMv6_7_8-M Device" >
      <description>CMSIS-CORE for Cortex-M, SC000, SC300, Star-MC1, ARMv8-M, ARMv8.1-M</description>
      <files>
        <file category="header"  name="CMSIS/Core/Include/tz_context.h" condition="TrustZone"/>
```

**To Reproduce**

Use this project and run cbuild setup
[CubeMX.zip](https://github.com/user-attachments/files/17304595/CubeMX.zip)

**Expected behavior**

`tz_context.h` should not be included in *.cbuild.yml

```yml
  components:
    - component: ARM::CMSIS:CORE@6.1.0
      files:
        - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Core/Include/tz_context.h    # this is wrong
          category: header
          version: 6.1.0
```

**Environment (please complete the following information):**

- CMSIS-Toolbox v2.6.1
- OS: windows
