### ISSUE TITLE
APIs have no vendor information in `cbuild.yml` under `license:` node

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1821]
**The Problem To Be Solved**

I would recommend to add the vendor information to APIs in the `license:` node of the `cbuild.yml` files.

Currently this is the output:

```yml
    components:
        - component: ::CMSIS Driver:GPIO(API)
      :
        - component: ::CMSIS:RTOS2(API)
        - component: ARM::CMSIS-Compiler:CORE@1.1.0
        - component: ARM::CMSIS-Compiler:STDERR:Custom@1.1.0
```
