### ISSUE TITLE
Provide data for Software Bill of Materials (SBOM)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1829]
**The Problem To Be Solved**

Some development processes require the generation for a SBOM. There are existing frameworks such as [CycloneDX](https://cyclonedx.org/) that organize these data.

As the `cbuild.yml` files contain already information about license, pack, and software component, this information could be provided to such systems.  Below is an example:

Questions:

- what can be done by CMSIS-Toolbox to simplify generation of SBOMs?  Is there information missing that could be easily added?
- are there existing tools that help to collect the information?  Could these tools be used to extract the information from `cbuild.yml` or `.PDSC` XML files?

**Example of `cbuild.yml` license information**

```yml
  licenses:
    - license: <proprietary> END USER LICENSE AGREEMENT FOR ARM SOFTWARE DEVELOPMENT TOOLS
      license-agreement: ${CMSIS_PACK_ROOT}/Keil/MDK-Middleware/8.0.0/license_terms/license_agreement.txt
      packs:
        - pack: Keil::MDK-Middleware@8.0.0
      components:
        - component: Keil::USB&MDK:CORE@8.0.0
        - component: Keil::USB&MDK:Device:HID@8.0.0
        - component: Keil::USB&MDK:Device@8.0.0
    - license: Apache-2.0
      packs:
        - pack: ARM::CMSIS-Compiler@2.1.0
        - pack: ARM::CMSIS-Driver_STM32@1.0.0
        - pack: ARM::CMSIS-RTX@5.9.0
        - pack: ARM::CMSIS@6.1.0
        - pack: Keil::B-U585I-IOT02A_BSP@2.0.0
        - pack: Keil::STM32U5xx_DFP@3.0.0
      components:
        - component: ::CMSIS Driver:GPIO(API)
        - component: ::CMSIS Driver:I2C(API)
        - component: ::CMSIS Driver:SPI(API)
        - component: ::CMSIS Driver:USART(API)
        - component: ::CMSIS Driver:USB Device(API)
        - component: ::CMSIS Driver:VIO(API)
        - component: ::CMSIS-Compiler:STDERR(API)
        - component: ::CMSIS-Compiler:STDIN(API)
        - component: ::CMSIS-Compiler:STDOUT(API)
        - component: ::CMSIS:OS Tick(API)
        - component: ::CMSIS:RTOS2(API)
        - component: ARM::CMSIS-Compiler:CORE@1.1.0
        - component: ARM::CMSIS-Compiler:STDERR:Custom@1.1.0
        - component: ARM::CMSIS-Compiler:STDIN:Custom@1.1.0
        - component: ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0
        - component: ARM::CMSIS:CORE@6.1.0
        - component: ARM::CMSIS:OS Tick:SysTick@1.0.5
        - component: ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0
        - component: Keil::CMSIS Driver:GPIO@1.0.0
        - component: Keil::CMSIS Driver:I2C@3.0.0
        - component: Keil::CMSIS Driver:SPI@3.0.0
        - component: Keil::CMSIS Driver:USART@3.0.0
        - component: Keil::CMSIS Driver:USB Device@3.0.0
        - component: Keil::CMSIS Driver:VIO:Board@2.0.2
        - component: Keil::Device:CubeMX@1.0.0
 ```
