### ISSUE TITLE
Provide information for Debug tools and programmers

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1831]
**The Problem To Be Solved**

Debug tools and programmers require target information that is already present in the software packs (DFP, BSP). Can this be simplified by adding information i.e. to the `cbuild-idx.yml` file or the `cbuild.yml` files?

The packs contain:
- Flash algorithms
- Device parameters
- Device name
- Board parameters
- Board name
- Memory Information
- Debug connect information

How can this information be effectively provided to Debug tools and programmers?
In the VSCode this could be obtained using features, but that method fails in CLI usage.

What needs to be extended and how?

**Example `cbuild-idx.yml` information**

```yml
build-idx:
  generated-by: csolution version 2.6.0
  description: USB Device examples
  cdefault: cdefault.yml
  csolution: USB_Device.csolution.yml
  tmpdir: tmp
  cprojects:
    - cproject: HID/HID.cproject.yml
      clayers:
        - clayer: HID/$Board-Layer$
    - cproject: MassStorage/MassStorage.cproject.yml
      clayers:
        - clayer: MassStorage/$Board-Layer$
    - cproject: VirtualCOM/VirtualCOM.cproject.yml
      clayers:
        - clayer: VirtualCOM/$Board-Layer$
  cbuilds:
    - cbuild: HID/HID.Debug+STM32U585AIIx.cbuild.yml
      project: HID
      configuration: .Debug+STM32U585AIIx
      clayers:
        - clayer: Board/B-U585I-IOT02A/Board.clayer.yml
        - clayer: Board/B-U585I-IOT02A/CubeMX/Board.cgen.yml
```

**Example `cbuild.yml` information**

```yml
build:
  generated-by: csolution version 2.6.0
  solution: ../USB_Device.csolution.yml
  project: HID.cproject.yml
  context: HID.Debug+STM32U585AIIx
  compiler: AC6
  board: STMicroelectronics::B-U585I-IOT02A:Rev.C
  board-pack: Keil::B-U585I-IOT02A_BSP@2.0.0
  device: STMicroelectronics::STM32U585AIIx
  device-pack: Keil::STM32U5xx_DFP@3.0.0
  processor:
    dsp: on
    endian: little
    fpu: sp
    trustzone: off
    core: Cortex-M33
```

Relates to:
- https://github.com/ARM-software/vscode-cmsis-csolution/issues/44
