### ISSUE TITLE
`*.cbuild.yml` files do not link to documentation for generator components

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1836]
**The Problem To Be Solved**

In https://github.com/Open-CMSIS-Pack/STM32U5xx_DFP/blob/main/Keil.STM32U5xx_DFP.pdsc#L1909, the content includes:

```xml
      <files>
        <file category="doc" name="https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/CubeMX.md"/>
      </files>
```

But a `*.cbuild.yml` does not contain any information about this documentation.  VS Code can therefore not display the documentation link.

**Suggest A Solution**

I would have expected this content in `*.cbuild.yml`.

```yml
    - component: Keil::Device:CubeMX@1.0.0
      condition: STM32U5 CMSIS
      from-pack: Keil::STM32U5xx_DFP@3.0.0
      selected-by: Device:CubeMX
      generator:
        id: CubeMX
        path: ../Board/B-U585I-IOT02A/CubeMX/Board.cgen.yml
      files:
        - file: https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/CubeMX.md
          category: doc
          version: 8.0.0
```

**Environment:**
Windows, CMSIS-Toolbox 2.6.1
