### ISSUE TITLE
Proposal to add memory consumption linker options to `cdefault.yml`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1845]
**Describe The Problem To Be Solved**
Display memory consumption information as part of the linker execution.

**(Optional): Suggest A Solution**
Modify the cdefault.yml file https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/templates/cdefault.yml

```
  misc:
    - for-compiler: GCC
      Link:
        ...
        - -Wl,-Map=linker.map,--cref,-print-memory-usage,--gc-sections,--no-warn-rwx-segments
        # generate linker map
        # output a cross reference table
        # print memory usage to console
        # exclude unused sections from the imamge
        # suppress executable write segment warnings (used for ITCM)
```

see: https://github.com/ARM-software/vscode-cmsis-csolution/issues/89
