### ISSUE TITLE
[csolution] `Pre_Include_Global.h` and `Pre_Include_<Cclass>_<component>.h` are not listed in `*.cbuild.yml` when generated

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1868]
**Describe the bug**
When `csolution convert` is executed and the files Pre_Include_Global.h` and `Pre_Include_<Cclass>_<component>.h` are generated due to one or more selected components having the respective element, the generated header files are not listed in `*.cbuild.yml`.

**To Reproduce**
create a cproject.yml file selecting a component that contains:
```
<component ...>
  <Pre_Include_Global_h>
    // enabling global pre include
    #define GLOBAL_Component 0x8
  </Pre_Include_Global_h>
  ...
</component>
```
and
```
<component ...>
  <Pre_Include_Local_Component_h>
    // enabling local pre include
    #define Local_Component_Alpha 1
  </Pre_Include_Local_Component_h>
  ...
</component>
```

**Expected behavior**
Pre-Include files are added to the compiler command line 
They can be applied to all modules (Global)
- add new top level node: `pre-include:`
or only to modules of a specific component (Local)
- add new child node: `pre-include:` to `component:` node

- Tools: csolution Version 2.6.0
- OS: any

**Comment by brondani** [comment]
Take for example the following test data from the E2E tests which successfully run for several toolchains:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/tree/main/test/data/pre-include

Where the test components have the following sections:
``` xml
    <component Cclass="TestClass" Cgroup="TestGlobal" Cversion="1.0.0" condition="Test_Condition">
      <Pre_Include_Global_h>
        // enabling global pre include
        #define GLOBAL_TEST 0x1
      </Pre_Include_Global_h>
   ...  
    <component Cclass="TestClass" Cgroup="TestLocal" Cversion="1.0.0" condition="Test_Condition">
      <Pre_Include_Local_Component_h>
        // enabling local pre include
        #define LOCAL_TEST 0x2
      </Pre_Include_Local_Component_h>
```
The files `RTE/_AC6_ARMCM0/Pre_Include_Global.h` and `RTE/_AC6_ARMCM0/Pre_Include_TestClass_TestLocal.h` are created with the expected content and the cbuild.yml file is generated with the following information:
``` yml
  components:
  ...
    - component: ARM::TestClass:TestLocal@1.0.0
      files:
        ...
        - file: RTE/_AC6_ARMCM0/Pre_Include_TestClass_TestLocal.h
          category: preIncludeLocal
  ...
  constructed-files:
    - file: RTE/_AC6_ARMCM0/Pre_Include_Global.h
      category: preIncludeGlobal
```
Afterwards, when running a build, this info then appears in the generated CMakeLists, compile_commands.json and in the command line for each relevant file, for instance:
```
-include .../RTE/_AC6_ARMCM0/Pre_Include_Global.h
-include .../RTE/_AC6_ARMCM0/Pre_Include_TestClass_TestLocal.h
```
@Torbjorn-Svensson What am I missing?
