### ISSUE TITLE
Add device and board documentation to cbuild.yml

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1871]
Requested by @edriouk

The device and board documentation described in DFPs and BSPs `book` sections should be added to cbuild.yml.

PDSC specification:
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_book
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_book

Example of yml nodes:
``` yml
build:
  device-books:
    - name: https://developer.arm.com/documentation/dui0662
      title: Cortex-M0+ Processor Devices Generic Users Guide
  board-books:
    - category: manual
      name: https://www.st.com/resource/en/user_manual/um2839-discovery-kit-for-iot-node-with-stm32u5-series-stmicroelectronics.pdf
      title: User Manual
    - category: other
      name: ${CMSIS_PACK_ROOT}/Keil/B-U585I-IOT02A_BSP/2.0.0/Documents/README.md
      title: Guide
```
