### ISSUE TITLE
not required layers should be set to ""

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1873]
**Describe the bug**

This issue pops up again https://github.com/Open-CMSIS-Pack/devtools/issues/1620

When layers are not required, but expected to be set, the related variable should be set to "". This needs to be reflected in `*.cbuild.idx` in the `configurations:` section.

**To Reproduce**

1. use https://github.com/Arm-Examples/AWS_MQTT_Demo
2. Enter in `demo.csolution.yml`

```yml
    - pack: Keil::NUCLEO-F756ZG_BSP@2.0.0

  target-types:
    - type: MyBoard
      board: NUCLEO-F756ZG
```

After cbuild setup, the `*.cbuild.idx` content is:

```yml
  configurations:
    - target-type: MyBoard
      target-configurations:
        - configuration: 
          variables:
            - Board-Layer: $SolutionDir()$/Board/NUCLEO-F756ZG/Board.clayer.yml
            - Socket-Layer: $SolutionDir()$/Socket/FreeRTOS_Plus_TCP/Socket.clayer.yml
```

**Expected behavior**

`- Shield-Layer: ""` is missing.

**Environment:**

- CMSIS-Toolbox 2.6.1
