### ISSUE TITLE
Changing context target results in CMake Error: cache does not match

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1889]
A change to Target Type results in this error:

```
-- stderr output is:
CMake Error: The source "C:/w/AWS_MQTT_Demo/tmp/Demo.Debug+MyBoard/CMakeLists.txt" does not match the source "C:/w/AWS_MQTT_Demo/tmp/Demo.Debug+AVH/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

CMake Error at C:/w/AWS_MQTT_Demo/tmp/Demo.Debug+MyBoard/src/Demo.Debug+MyBoard-stamp/Demo.Debug+MyBoard-configure-.cmake:47 (message):
  Stopping after outputting logs.
```

**To Reproduce**

1. Use https://github.com/Arm-Examples/AWS_MQTT_Demo and modify `Demo.csolution.yml` as shown here:

```
  packs:
    - pack: ARM::V2M_MPS3_SSE_300_BSP@1.5.0
    - pack: Keil::NUCLEO-F756ZG_BSP@2.0.0 # Add BSP
    - pack: Keil::STM32F7xx_DFP@3.0.0
    - pack: ARM::CMSIS-Driver@2.10.0 # Add CMSIS-Driver for WiFi Shields

  
  target-types:
    # This target is a AVH-FVP simulation model that does not require hardware
    - type: AVH
      board: ARM::V2M-MPS3-SSE-300-FVP
      variables:
        - Board-Layer: $SolutionDir()$/Board/AVH_MPS3_Corstone-300/Board.clayer.yml
        - Shield-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/VSocket/Socket.clayer.yml

    - type: MyBoard
      board: NUCLEO-F756ZG
      variables:
        - Board-Layer: $SolutionDir()$/Board/NUCLEO-F756ZG/Board.clayer.yml
        - Shield-Layer: $SolutionDir()$/Shield/WiFi/Sparkfun_ESP8266/Shield.clayer.yml
        - Socket-Layer: $SolutionDir()$/Socket/WiFi/Socket.clayer.yml
```

2. Change Target-Type (using VS Code)

![image](https://github.com/user-attachments/assets/fb607ea3-96c1-4cee-83e5-1cfcbe3420fc)

This results in the error.

Note:  A click on the Status bar does not open Output - CMSIS Solution

**Environment:**

- cbuild: Build Invocation v2.6.1-25-g3f083c7
-
