### ISSUE TITLE
Layer detection should not require DFP to fullfil mounted device

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1890]
**The Problem To Be Solved**

In CMSIS-Toolbox 2.6.1 it was not required to specify the DFP as the mounted device was not checked during layer detection.

cbuild v2.6.1-25-g3f083c7 requires now the DFP, otherwise it reports:
```
error csolution: board mounted device STM32F756ZGTx not found
error csolution: no compatible software layer found. Review required connections of the project
```

**To duplicate**

Use https://github.com/Arm-Examples/AWS_MQTT_Demo and modify `Demo.csolution.yml` as shown here:

```
  packs:
    - pack: ARM::V2M_MPS3_SSE_300_BSP@1.5.0
    - pack: Keil::NUCLEO-F756ZG_BSP@2.0.0 # Add BSP
#    - pack: Keil::STM32F7xx_DFP@3.0.0
    - pack: ARM::CMSIS-Driver@2.10.0 # Add CMSIS-Driver for WiFi Shields

  target-types:

    - type: MyBoard
      board: NUCLEO-F756ZG
```

Related https://github.com/Open-CMSIS-Pack/devtools/issues/1889
