### ISSUE TITLE
Add "environment" node to `cbuild-set.yml` schema; don't check content

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1895]
**The Problem To Be Solved**

The `*.cbuild-set.yml` file is primarily controlled by an IDE to select the different context sets. 

We could consider this file to store settings for debug and run control information.  I suggest first to experiment with this feature. To enable this we should consider adding a node `enviornment:` that is not checked by the schema.

```yml
cbuild-set:
  generated-by: vscode-cmsis-csolution version 1.44.0
  contexts:
    - context: Demo.Debug+MyBoard

  environment:          # this section should not be checked by schema
    ide:
      any-settings:
```

In a later stage this file could be used to pass debug/run settings to a `cbuild-run.yml` file.
