### ISSUE TITLE
cbuild-idx: 'variables' should contain existing settings from csolution.yml

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1897]
**The Problem To Be Solved**

To just changing a board layer, in an existing setting, it is possible to comment the variable as shown below.

```yml
  target-types:
    - type: MyBoard
      board: NUCLEO-F756ZG
      variables:
    #   - Board-Layer: $SolutionDir()$/Board/NUCLEO-F756ZG/Board.clayer.yml
        - Shield-Layer: ""
        - Socket-Layer: $SolutionDir()$/Socket/FreeRTOS_Plus_TCP/Socket.clayer.yml
```

The tooling repeats then the variable evaluation and `build-idx.yml` shows potential options. Existing layer variables are copied 1:1 and then shown nicely in a selection dialog of VS Code. But the `empty` Shield layer is missing.
```
build-idx:
  generated-by: csolution version 2.6.0+p62-g973de907
  description: AWS Cloud Connector Example
  cdefault: ${CMSIS_COMPILER_ROOT}/cdefault.yml
  csolution: Demo.csolution.yml
  tmpdir: tmp
  configurations:
    - target-type: MyBoard
      target-configurations:
        - configuration: 
          variables:
            - Board-Layer: ${CMSIS_PACK_ROOT}/Keil/NUCLEO-F756ZG_BSP/2.0.0/Layers/Default/Board.clayer.yml
              description: Default NUCLEO-F756ZG board setup
              path: C:/Users/reikei01/AppData/Local/Arm/Packs/Keil/NUCLEO-F756ZG_BSP/2.0.0/Layers/Default
              file: Board.clayer.yml
              copy-to: Board/NUCLEO-F756ZG
#           - Shield-Layer: ""          # THIS IS MISSING    
            - Socket-Layer: $SolutionDir()$/Socket/FreeRTOS_Plus_TCP/Socket.clayer.yml
``` 

Test Project: https://github.com/Arm-Examples/AWS_MQTT_Demo

**Suggest A Solution**

Add also the empty variable to `cbuild-idx.yml` to avoid user confusion.
