### ISSUE TITLE
Unexpected: `/.cbuild-pack.yml - error csolution: file cannot be written` 

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1900]
**Describe the bug**
When using in csolution.yml file

```yml
 target-types:
    - type: MyBoard
      board: NUCLEO-F756ZG
      variables:
    #   - Board-Layer: $SolutionDir()$/Board/NUCLEO-F756ZG/Board.clayer.yml
#       - Shield-Layer: ""
#       - Socket-Layer: $SolutionDir()$/Socket/FreeRTOS_Plus_TCP/Socket.clayer.yml
```

This error is shown:

```
Execute: cbuild setup c:\w\AWS_MQTT_Demo\Demo.csolution.yml --context-set --packs --update-rte
C:/w/AWS_MQTT_Demo/Demo.csolution.yml:43:7 - error csolution: unexpected instance type
/.cbuild-pack.yml - error csolution: file cannot be written
```
Expected is the 'unexpected instance type"
Unexpected is: `/.cbuild-pack.yml - error csolution: file cannot be written` 

Test Project: https://github.com/Arm-Examples/AWS_MQTT_Demo
