### ISSUE TITLE
[csolution] pack providing the board not listed in cprj

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#191]
In my csolution I select a board:

```
solution:
  target-types:
    - type: B-U585I-IOT02A
      board: B-U585I-IOT02A
```

And I do not use any element from the pack defining this board in my project.
When I generate the cprj:

```
  <packages>
    <package name="CMSIS" vendor="ARM" version="5.8.0"/>
    <package name="STM32U5xx_DFP" vendor="STMicroelectronics" version="0.0.1"/>
  </packages>
```

The package defining the board is not listed here.
