### ISSUE TITLE
[experimental] Initial implementation of `cbuild-run.yml` generation

### ISSUE THREAD

**Issue by brondani** [Open-CMSIS-Pack/devtools#1912]
As requested in https://github.com/Open-CMSIS-Pack/devtools/issues/1867:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/Experimental-Features.md#run-and-debug-management

Implementation:
https://github.com/Open-CMSIS-Pack/devtools/pull/1896

Initially supported nodes:
``` yaml
cbuild-run:
  generated-by:
  solution:
  target-type:
  compiler:
  device:
  device-pack:
  board:
  board-pack:
  programming:
    - algorithm:
      start:
      size:
      default:
  system-descriptions:
    - file:
      type: svd
  output:
    - file:
      type: elf
```

Additional `memory` node accepted in `csolution.yml`:
``` yaml
solution:
  target-types:
    - memory:
        - start:
          size:
          name:
          access:
          algorithm:
```
