### ISSUE TITLE
[csolution] `add_path:` duplicate paths not checked, absolute paths not added

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1938]
A *.cproject.yml that contains the following `add-path:`

```yml
  setups:
    - setup: Options for Target_1
      processor:
        fpu: "off"
      add-path:
        - $Pack(Microchip::SAME70_DFP)$/same70b/include
        - C:/Users/reikei01/AppData/Local/Arm/Packs/Microchip/SAME70_DFP/4.11.257/same71b/include
```

Generates this `*.cbuild.yml` output:
```yml
  add-path:
    - ${CMSIS_PACK_ROOT}/Microchip/SAME70_DFP/4.11.257/same70b/include
    - RTE/CMSIS
    - RTE/_Debug_Target_1
    - ${CMSIS_PACK_ROOT}/ARM/CMSIS-RTX/5.9.0/Include
    - ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Core/Include
    - ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/RTOS2/Include
    - ${CMSIS_PACK_ROOT}/Microchip/SAME70_DFP/4.11.257/same70b/include     # !!! Duplicate
```

It has:
  - a duplicate path name (which is flagged by the schema)
  - misses the absolute include path ` C:/Users/reikei01/AppData/Local/Arm/Packs/Microchip/SAME70_DFP/4.11.257/same71b/include`

The  `warning csolution: absolute path 'C:/Users/reikei01/AppData/Local/Arm/Packs/Microchip/SAME70_DFP/4.11.258/same70b/include' is not portable, use relative path instead` is informative, but still the path should be in cbuild.yml `add-path:`.

**To Reproduce**

Use [test.zip](https://github.com/user-attachments/files/18590266/test.zip) and use `cbuild test.csolution.yml --context-set`

**Environment:**

- CMSIS-Toolbox 2.7.0
- OS: Windows
