### ISSUE TITLE
[csolution] Use cprj in MDK-5.36 requires setting c99

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#194]
When  I open the cprj generated with csolution for AC6, by default the C language is C90 and all warnings are turned on.

I need to change it manually like this:

![image](https://user-images.githubusercontent.com/8255133/157485998-8fc85da7-0742-4061-a46e-272a220ca455.png)

I do not find how I can tune this from the yml definition ?

**Comment by fred-r** [comment]
My csolution is like this:

```
solution:
  target-types:
    - type: B-U585I-IOT02A
      board: B-U585I-IOT02A
      # device: STM32U585ZITx
      processor:
        trustzone: off          # TrustZone disabled for this project
      defines:
        # - STM32U585xx
        # - USE_FULL_LL_DRIVER
        - USE_HAL_DRIVER

  build-types:
    - type: AC6
      compiler: AC6
      misc:
        - C*:
          - -std=C99
    - type: GCC
      compiler: GCC
      misc:
        - C*:
          - -std=C99    

  # packs:
    # specify the DFP pack to avoid selecting the U5 device from Keil DFP pack
    # - pack: STMicroelectronics::STM32U5xx_DFP
  projects:
    - project: ./gpio-toggle.cproject.yml
```

Then I convert to cprj:
```
frq09468@LMECWL0888 MINGW64 /c/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects (main)
$ csolution -s gpio-toggle.csolution.yml convert
C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.csolution.yml - warning csolution: yaml schemas were not found, file cannot be validated
C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.csolution.yml:8:7 - warning csolution: key 'processor' was not recognized
C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.cproject.yml - warning csolution: yaml schemas were not found, file cannot be validated
C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.AC6+B-U585I-IOT02A.cprj - info csolution: file generated successfully
C:/Cube20/stm32cube_fw_all/examples/hal/gpio/toggle/projects/gpio-toggle.GCC+B-U585I-IOT02A.cprj - info csolution: file generated successfully
```

But the crpj does not contain the c99 settings:
```
  <compilers>
    <compiler name="AC6" version="6.16.0"/>
  </compilers>

  <target Ddsp="DSP" Dfpu="SP_FPU" Dname="STM32U585ZITx" Dsecure="TZ-disabled" Dtz="TZ" Dvendor="STMicroelectronics:13">
    <output intdir="gpio-toggle.AC6+B-U585I-IOT02A_IntDir/" name="gpio-toggle.AC6+B-U585I-IOT02A" outdir="gpio-toggle.AC6+B-U585I-IOT02A_OutDir/" type="exe"/>
    <ldflags compiler="AC6" file="RTE/Device/STM32U585ZITx/stm32u585xx_flash.sct"/>
    <defines>USE_HAL_DRIVER</defines>
  </target>
```
