### ISSUE TITLE
Handling of `*.dbgconf` files

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1946]
The `*.dbgconf` file is part of the PDSC device element and specified in [debugvars](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_debugvars). It typically configures trace pins but may be also used for other control functions as it interacts with the [Debug Setup](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/coresight_setup.html).

`*.dbgconf` can be pname specific and has version numbers.  It is therefore required to implement a PLM similar to other RTE files.
Suggestion is therefore to copy the device specific `*.dbgconf` into the `\RTE\Device\<device>` directory with the same [PLM version handling](https://open-cmsis-pack.github.io/cmsis-toolbox/build-overview/#plm-of-configuration-files) as other RTE files.

To make these files accessible to the user, the file should be exposed in VS Code CMSIS-View under Device. In this way the same PLM handling as for other config files could be implemented.

![Image](https://github.com/user-attachments/assets/02813d00-bde6-407f-a7d0-ac62cff8a6b0)

The `*.dbgconf` file should be therefore listed in the `*.<build-type>+<target-type>.cbuild.yml`. Format similar to [component files](https://open-cmsis-pack.github.io/cmsis-toolbox/YML-CBuild-Format/#files-of-a-component) with `- file`, `base`, `update`, `status`.

Example:

```
  device: ADuCM410
  device-pack: AnalogDevices::ADuCM410_DFP@1.7.0
  device-books:
    - name: ${CMSIS_PACK_ROOT}/AnalogDevices/ADuCM410_DFP/1.7.0/Documentation/arm_cortex_m33_dgug_100235_0002_00_en.pdf
      title: Cortex-M33 Generic User Guide
  dbgconf:
     - file: M410.dbgconf
       version: 1.0.0
       base: M410.dbgconf@1.0.0
       update: M410.dbgconf@1.1.0
       status: update recommended
```

As version is optional for `*.dbgconf` files the base file is only generated when a version is specified and the file is copied the first time. Inherently it could be assumed that the base version is 0.0.0 in this case.

**Comment by ReinhardKeil** [comment]
@brondani good point, maybe we add the debugger that the config file applies to.  Something like this:

```yml
dbgconf:
     - file: M410.dbgconf
       version: 1.0.0
       base: M410.dbgconf@1.0.0
       update: M410.dbgconf@1.1.0
       status: update recommended
       debugger:
          - CMSIS-DAP
          - JLINK
     - file: M410-UL.dbgconf
       debugger:
          - ULINK

```

**Comment by jkrech** [comment]
```
 dbgconf:
    - file: RTE/Device/STM32F207IGHx/STM32F205_207_215_217.dbgconf
      version: 0.9.0
      base: RTE/Device/STM32F207IGHx/STM32F205_207_215_217.dbgconf.base@0.9.0
      update: RTE/Device/STM32F207IGHx/STM32F205_207_215_217.dbgconf.update@1.0.0
      status: update required
```

![Image](https://github.com/user-attachments/assets/5b54752b-cc56-49a7-9602-21b17eceab34)
