### ISSUE TITLE
Handling of Debugger Configuration

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1947]
# How to get parameters for the Debugger?

## CMSIS-Pack Content

DFP: [debug-config](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_debugconfig) contains default connection parameters for a device.

BSP: [debug-probe](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board_debugProbe) contains debugger information for a board.

## Initial implementation

Expose this information in `*.cbuild-run.yml` under `debugger:` node.

Example:

```yml
debugger:
  name: CMSIS-DAP     # name from BSP, if not known use "<default>"
  port: jtag          # value from BSP (debugLink), if not present from DFP (default)
  clock: 10000000     # value from BSP (debugClock), if not present from DFP (clock)
  dbgconf: RTE/Device/lpc4300/lpc4300.dbgconf   # described in #1946
 ```
For `dbgconf` see #1946  

## Debugger Information in `csolution.yml`

This information could be also supplied in a `csolution.yml` file with a `debugger:` node.

`debugger:`                                               |             | Content
:---------------------------------------------------------|-------------|:------------------------------------
`- name:`                                                 |**Required** | Identifies the debug configuration.
&nbsp;&nbsp;&nbsp; `info:`                                |  Optional   | Brief description of the connection
&nbsp;&nbsp;&nbsp; `port:`                                |  Optional   | Selected debug port (jtag or swd).
&nbsp;&nbsp;&nbsp; `clock:`                               |  Optional   | Selected debug clock speed.
&nbsp;&nbsp;&nbsp; `dbgconf:`                             |  Optional   | Debugger configuration file (pinout, trace).

With this information `*.cbuild-run.yml` contains

Example:

```yml
debugger:
  - name: CMSIS-DAP     # name of csolution, if not given name from BSP, if not known use "<default>"
    info:               # value of csolution
    port: jtag          # value of csolution, if not given value from BSP (debugLink), if not present from DFP (default)
    clock: 10000000     # value of csolution, if not given value from BSP (debugClock), if not present from DFP (clock)
    dbgconf: RTE/Device/lpc4300/lpc4300.dbgconf  #  value of csolution, if not given as describe in #1946 
 ```

## Usage of debugger information

The following are potential ways to use this debugger information:

1.  Expose all potential debuggers in `cbuild-run.yml`. Depending on the name, the debugger uses a configuration
        - If the connected debugger is not known, specified the debugger to use on the command-line of the debugger.
2.  Select the debugger at csolution level with nodes under `target-type:` or command line option on cbuild.

My preference is (1).

**Comment by ReinhardKeil** [comment]
@brondani this is a revised specification with `for-context:` and `not-for-context:`. 

All `debugger:` configurations should be in `*.cbuild-run.yml`

**Comment by brondani** [comment]
@ReinhardKeil, @jreineckearm
Concerning the `port:` possible values, can we safely restrict the schema to `jtag` and `swd` or should we also expect that in DFPs it can be set to `cjtag` as listed in the following table?
https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DebugProtocolEnum

**Comment by ReinhardKeil** [comment]
For now we can remove `cjtag` as we don't see real usage of it.

**Comment by jkrech** [comment]
validating nightly build.
 ```
 debugger:
    - name: ST-Link
      port: swd
      clock: 10000000
      dbgconf: MassStorage/RTE/Device/STM32U585AIIx/STM32U535_545_575_585_59x_5Ax.dbgconf
```
