### ISSUE TITLE
[csolution] does not check if the specified linker script file is present

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1952]
**Describe the bug**
`csolution` does not check if the linker script file is present. Instead an error at CMake build level is generated that is misleading.  

```
ninja: error: 'C:/w/csolution-examples/CubeMX/RTE/Device/STM32U585AIIx/ac6_linker_script.sct.srcx', needed by 'C:/w/csolution-examples/CubeMX/out/CubeMX/MyBoard_ROM/Debug/CubeMX.axf', missing and no known rule to make it
```

**To Reproduce**

Use csolution-examples CubeMX and change `*.cproject.yml` the linker script file name, i.e. 

```yml
  linker:
    - script: RTE/Device/STM32U585AIIx/ac6_linker_script.sct.srcx
    - regions: $regions_header$
      for-compiler: AC6
```

**Expected behavior**
Missing source files are flagged by csolution.  Implement a similar behavour for linker script file.

**Environment (please complete the following information):**

- CMSIS-Toolbox 2.7.0
- Windows
