### ISSUE TITLE
Implement `system-resources`, `debug-vars`, and `debug-sequences`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#1953]
To complete the `*.cbuild-run.yml` information for pyOCD implement `system-resources`, `debug-vars`, and `debug-sequences` as documented in
https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/Experimental-Features.md#run-and-debug-management

**Comment by brondani** [comment]
From https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/Experimental-Features.md#debug-vars:
> Additional node vars: is kept to allow for future extensions.

Thinking on future extensions, should `debug-vars` be an array like this?
```yml
debug-vars:
  - vars:
```

**Comment by ReinhardKeil** [comment]
@brondani - Here are my answers:

1. I used your proposal (even when there is currently only one `- vars:`
2. Yes this is inconsistent, but it starts in the DFP/BSP where memory and algorithm are disconnected.  I believe we should define for external memory an algorithm in the same field.
3. `memory:` is now corrected.
4. In practice `debug-vars` is not used with `pname:`.  Only an iMX7 has used this feature and a close look shows that this is not required. Recommend to deprecate `pname` in debug-vars as otherwise the config file management would become even more complicated.

**Comment by jkrech** [comment]
Device STMicroelectronics:STM32F207IGHx

`*.cbuild-run.yml`

lists debug-vars from PDSC:
```
debug-vars:
    vars: |
      __var DbgMCU_CR      = 0x00000007;   // DBGMCU_CR: DBG_SLEEP, DBG_STOP, DBG_STANDBY
      __var DbgMCU_APB1_Fz = 0x00000000;   // DGBMCU_APB1_FZ: All Peripherals Operate as in Normal Mode
      __var DbgMCU_APB2_Fz = 0x00000000;   // DGBMCU_APB2_FZ: All Peripherals Operate as in Normal Mode
      __var TraceClk_Pin   = 0x00040002;   // PE2
      __var TraceD0_Pin    = 0x00040003;   // PE3
      __var TraceD1_Pin    = 0x00040004;   // PE4
      __var TraceD2_Pin    = 0x00040005;   // PE5
      __var TraceD3_Pin    = 0x00040006;   // PE6
```

lists debug-sequences from PDSC -> translated to YAML:

```
debug-sequences:
    - name: DebugDeviceUnlock
      blocks:
        - execute: |
            Sequence("CheckID");
    - name: DebugCoreStart
      blocks:
        - execute: |
            // Replication of Standard Functionality
            Write32(0xE000EDF0, 0xA05F0001);                                        // Enable Core Debug via DHCSR
        - info: DbgMCU registers
          execute: |
            Write32(0xE0042004, DbgMCU_CR);                                         // DBGMCU_CR: Configure MCU Debug
            Write32(0xE0042008, DbgMCU_APB1_Fz);                                    // DBGMCU_APB1_FZ: Configure APB1 Peripheral Freeze Behavior
            Write32(0xE004200C, DbgMCU_APB2_Fz);                                    // DBGMCU_APB2_FZ: Configure APB2 Peripheral Freeze Behavior
   ...
```

system-resources from pdsc file `<memory>` 
```
 system-resources:
    memory:
      - name: IROM1
        start: 0x08000000
        size: 0x00100000
        default: true
        startup: true
        from-pack: Keil::STM32F2xx_DFP@2.11.0
      - name: IRAM1
        start: 0x20000000
        size: 0x00020000
        default: true
        from-pack: Keil::STM32F2xx_DFP@2.11.0
```
