### ISSUE TITLE
[csolution] Add `overview:` node to `*.cbuild.yml` files with a reference to the "Overview" MD file specified in the package description file

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1963]
**Describe The Problem To Be Solved**
Allow an IDE to display the "Overview" MarkDown file optionally specified in the "overview=" attribute of the [`<description>` tag](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/element_package_description.html) in the package description file (`*.pdsc`)

**Suggested Solution**
a) Extend the `device-pack:` node with an `overview:` subnode in the [`*cbuild.yml`](https://open-cmsis-pack.github.io/cmsis-toolbox/YML-CBuild-Format/#cbuildyml) to provide this information. 

```
cbuild:
  device: ARM::SSE-300-MPS3
  device-pack: ARM::V2M_MPS3_SSE_300_BSP@1.5.0
    - overview: ${CMSIS_PACK_ROOT}/ARM/V2M_MPS3_SSE_300_BSP/1.5.0/Documents/overview.md
  device-books:
    - name: ${CMSIS_PACK_ROOT}/ARM/V2M_MPS3_SSE_300_BSP/1.5.0/Documents/arm_corstone_sse-300_example_subsystem_technical_reference_manual_101773_0001_03_en.pdf
      title: Arm® SSE-300 - Technical Reference Manual
```
Extend the  `board-pack:` node accordingly.

b) Add an `overview:` sub-node to the [`pack:` node](https://open-cmsis-pack.github.io/cmsis-toolbox/YML-CBuild-Format/#packs) similar to `path:` if an overview is specified for a pack.

```
 packs:
    - pack: ARM::CMSIS-FreeRTOS@10.4.6
      path: ${CMSIS_PACK_ROOT}/ARM/CMSIS-FreeRTOS/10.4.6
      overview: ${CMSIS_PACK_ROOT}/ARM/CMSIS-FreeRTOS/10.4.6/docs/overview.md
       :
    - pack: MDK-Packs::IoT_Socket@1.3.1
      path: ../IoT_Socket
```

The drawback of a) is that this will not make `overview.md` files accessible, for Software Packs that are neither Board nor Device packs.
The drawback of b) is that it requires an additional level of indirection to locate the file reference for a device / board.

We could implement a) and b) accepting redundant information in `*.cbuild.yml`.
