### ISSUE TITLE
Document how to write CMSIS Solution Templates with multiple targets using `${Name}`

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#1998]
**Describe The Problem To Be Solved**
Allow to specify CMSIS Solution templates with multiple targets

**(Optional): Suggest A Solution**

```yml
  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: %Name%_ROM
      variables:
        - LinkerScript: <script_for_ROM>

    - type: %Name%_RAM
      variables:
        - LinkerScript:: <script_for_RAM>
```

* Details of the technical implementation
Support added in CMSIS Solution 1.50 https://github.com/ARM-software/vscode-cmsis-csolution/issues/96
* Caveats and considerations for the future

If there are multiple solutions, please present each one separately. Save comparisons for the very end.
