### ISSUE TITLE
optimize level for layers

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2002]
**The Problem To Be Solved**

A layer that contains a ML model should be optimized for SIZE while the rest of the application is developed and uses optimize debug settings.  

```yml
layer:
  type: Edge Impulse layer
  description: Edge Impulse layer

  optimize: size   # this creates currently an error

  packs:
    - pack: EdgeImpulse::Tutorial_Continuous_motion_recog@162.0.0
      path: .

  components:
    - component: EdgeImpulse:model:Tutorial_Continuous_motion_recog@162.0.0
```

**Suggest A Solution**

The setting `optimize:` is currently rejected with an error.  It should be possible.

**Version**

CMSIS-Toolbox 2.8

**Comment by brondani** [comment]
A top level translation control node in a layer is a **context leve**l control, as it is for project, setup, solution, build-type and target-type controls.

Redefinition of `optimize` is not allowed: if conflicting values are declared it will result in an error.
For example:
``` yml
solution:
  build-types:
    - type: Debug
      optimize: debug
---
layer:
  optimize: size
```

It will result in a redefinition error:
```
error csolution: redefinition from 'debug' into 'size' is not allowed
```

**Comment by jkrech** [comment]
What is the alternative if I only want to change the optimization for all modules specified under `files:` and `components:`?
It seems like we are looking for build control options that only inherit downwards and not upwards.
For files one could create a `group:` to set options for all `files` in that group, something similar does not exist for `components`.
Does it make sense to add build control nodes for `components:` nodes?

**Comment by brondani** [comment]
> What is the alternative if I only want to change the optimization for all modules specified under `files:` and `components:`?

Set the options for each relevant `group:` (or `file:` for finer granularity) and for each `component:`.
In this issue's example the layer would look like this:
``` yml
layer:
  components:
    - component: EdgeImpulse:model:Tutorial_Continuous_motion_recog@162.0.0
      optimize: size
```

> Does it make sense to add build control nodes for `components:` nodes?

The options description would be more compact when all groups or all components require the same customization, but its behavior might not be obvious: should the options be applied for all `groups` or `components` for a given layer/project or for a given context regardless of it being spread across multiple files?
