### ISSUE TITLE
Schema Check on cbuild files fails on version MAROR.MINOR format for components

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2015]
**Describe the bug**

Some packs use for components only MAJOR.MINOR version (this is permitted according PDSC specification).
However the schema check of the *.cbuild*.yml files rejects this.

**Solution**

Schema check for *.cbuild*.yml should accept also the format MAJOR.MINOR.

Workaround: use CMSIS-Toolbox 2.7 until this problem is addressed.

** Version**

CMSIS-Toolbox 2.8

**Comment by jkrech** [comment]
I am unable to reproduce this. The following snippet from my `*cbuild.yml` does not fail for me in CMSIS Solution Extension 1.50 shipped schema with this origin:
https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/2.8.0/tools/projmgr/schemas/cbuild.schema.json"

```
    - component: Keil::CMSIS Driver:I2C@2.10
      condition: STM32F2 CMSIS_Driver I2C
      from-pack: Keil::STM32F2xx_DFP@2.11.0
      selected-by: Keil::CMSIS Driver:I2C
      implements: CMSIS Driver:I2C@2.4.0
      files:
        - file: ${CMSIS_PACK_ROOT}/Keil/STM32F2xx_DFP/2.11.0/CMSIS/Driver/I2C_STM32F2xx.c
          category: source
          version: 2.10.0
```
