### ISSUE TITLE
Generated cbuild-run.yml issue with Flash algorithms on multi-processor

### ISSUE THREAD

**Issue by RobertRostohar** [Open-CMSIS-Pack/devtools#2026]
**Describe the bug**
`Pname` attribute in the pdsc [algorithm element](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_algorithm) is optional. It is only mandatory for devices that embed multiple processors that require different algorithms. Based on that, it should be allowed to not specify the `Pname` attribute for multi-processor which can use the same algorithm. If`Pname` attribute is not specified in the pdsc, then also the node `algorithm` in the generated `cbuild-run.yml` should not list the `pname` node. Currently the generated node `algorithm` does include the `pname` node, which wrongly limits the algorithm to a single processor.

**To Reproduce**

- Create a project for NXP K32L3A60VPJ1A device (using the K32L3A60_DFP)
- Build the project to get the cbuild-run.yml file generated

K32L3A60_DFP contains the following:
```
<processor Pname="cm0plus" Dcore="Cortex-M0+" ...>
<processor Pname="cm4" Dcore="Cortex-M4" ...>
<algorithm name="devices/K32L3A60/arm/K32L3A60_P1024_4KB_SEC.FLM" start="0x00000000" size="0x00100000" RAMstart="0x20000000" RAMsize="0x00002000" default="1"/>
<algorithm name="devices/K32L3A60/arm/K32L3A60_P256_2KB_SEC.FLM"  start="0x01000000" size="0x00040000" RAMstart="0x20000000" RAMsize="0x00002000" default="1"/>
```
Note that `algorithm` elements have no `Pname` attribute.

Generated `cbuild-run.yml` contains the following:
```
  programming:
    - algorithm: ${CMSIS_PACK_ROOT}/NXP/K32L3A60_DFP/18.0.0/devices/K32L3A60/arm/K32L3A60_P1024_4KB_SEC.FLM
      start: 0x00000000
      size: 0x00100000
      ram-start: 0x20000000
      ram-size: 0x00002000
      default: true
      pname: cm4
    - algorithm: ${CMSIS_PACK_ROOT}/NXP/K32L3A60_DFP/18.0.0/devices/K32L3A60/arm/K32L3A60_P256_2KB_SEC.FLM
      start: 0x01000000
      size: 0x00040000
      ram-start: 0x20000000
      ram-size: 0x00002000
      default: true
      pname: cm4
```

Node `pname: cm4` should not be there.

**Environment:**
- CMSIS-Toolbox
- Version 2.8.0
- OS: Windows

**Comment by RobertRostohar** [comment]
It seems that this behavior is not limited to Flash algorithms only but to other nodes also (memory, debug sequences, ...).

**Comment by brondani** [comment]
@RobertRostohar Can you please share the cbuild-set.yml file of your solution?
Please note cbuild-run.yml is generated for the contexts selected by `cbuild-set` so for such a multi-core solution it should look like this:
```yml
cbuild-set:
  contexts:
    - context: cm0plus.Debug+K32L3A60VPJ1A
    - context: cm4.Debug+K32L3A60VPJ1A
```
