### ISSUE TITLE
Add peripheral memory to `cbuild-run.yml`

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2033]
**The Problem To Be Solved**

Debug Tools require information about the peripheral memory that is available in devices.

**Suggest A Solution**

The *.PDSC file allow to specify [memory](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_memory) however most devices do not contain any memory with access type `p`. 
When the *.PDSC file contains any memory with access type `p`, this memory should be exposed in cbuild-run.yml.  

For *.PDSC files that **do not contain** any memory with access type `p`, the csolution tool should add default peripheral memory regions to *.cbuild-run.yml [system resources](https://open-cmsis-pack.github.io/cmsis-toolbox/YML-CBuild-Format/#system-resources). 

@jreineckearm please provide a table with default peripheral regions for the various Cortex-M processors.

**Comment by jreineckearm** [comment]
Default memory map for v6-M (same for v7-M/v8-M): https://developer.arm.com/documentation/ddi0419/c/System-Level-Architecture/System-Address-Map/The-system-address-map

Device related regions
* Peripheral: 0x40000000 - 0x5FFFFFFF
* Device (shareable): 0xA0000000 - 0xBFFFFFFF
* Device (non-shareable): 0xC0000000 - 0xDFFFFFFF
* System - PPB: 0xE0000000 - 0xE00FFFFF
* System - Vendor_SYS: 0xE0100000 - 0xFFFFFFFF

**Comment by ReinhardKeil** [comment]
This would then translate into:

```yml
  memory:

**Comment by RobertRostohar** [comment]
Probably it makes sense to either provide both device areas or none of them (just peripherals).
```
system-resources:
  memory:
    - name: Peripherals
      access: rwp
      start: 0x40000000
      size: 0x20000000
    - name: Devices-Shareable
      access: rwp
      start: 0xA0000000
      size: 0x20000000
    - name: Devices-NonShareable
      access: rwp
      start: 0xC0000000
      size: 0x20000000
    - name: System-Peripherals
      access: rwp
      start: 0xE0000000
      size: 0x20000000
```
