### ISSUE TITLE
cbuild-run.yml: debug-topology: requires information about all processors

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2041]
**Describe the bug**

The `debug-topology:` needs to list complete information about the debugports: and processors:.
Currently the processor information is missing when a pname is not used in the current context.

Use an Alif example to reproduce.

```yml
 debug-topology:
    debugports:
      - dpid: 0
        accessports:
          - apid: 0
            address: 0x00200000
          - apid: 1
            address: 0x00300000
    processors:
      - pname: M55_HP
        apid: 0
      - pname: M55_HE    # this is missing when csolution only uses M55_HP
        apid: 1
    dormant: true
    sdf: ../alif_ensemble-cmsis-dfp/Debug/SDF/E7/Ensemble E7.sdf
```
