### ISSUE TITLE
cbuild-run.yml: debug-topology: does not contain information from <debug> element.

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2042]
**Describe the bug**

MCXN947_DFP\19.0.0 contains in the PDSC:

```xml
<debug svd="devices/MCXN947/MCXN947_cm33_core0.xml" Pname="cm33_core0" __dp="0" __ap="0"/>
<debug svd="devices/MCXN947/MCXN947_cm33_core1.xml" Pname="cm33_core1" __dp="0" __ap="1"/>
```

From that information the following information should be generated in cbuild-run.yml:

```yml
  debug-topology:
    debugports:
      - dpid: 0
        accessports:
          - apid: 0
            index: 0
          - apid: 1
            index: 1
    processors:
      - pname: cm33_core0
        apid: 0
      - pname: cm33_core1
        apid: 1
```

**Comment by ReinhardKeil** [comment]
I just learn this also that there are two ways to define the same thing. 

@jreineckearm can you confirm that @brondani assumption is correct.

**Comment by jreineckearm** [comment]
We initially only worked with `__ap` where the value is an AP selection index. This is always APv1 and predates extensions that came with ADIv6.
The old mechanism cannot be mixed with `accessportV1` and `accessportV2` elements.

> Should I assume the PDSC element....

The assumption is a good start. But back then, one could freely assign an index to `__ap` in sequence implementations without defining it in a `<debug>` node. It mapped directly through to HW.
Need to think about how to cover such cases without parsing sequence implementations for `__ap` assignments. Where `__ap` values may be dynamically calculated (there was nothing hindering this).
Let's discuss tomorrow.

**Comment by ReinhardKeil** [comment]
This are the default values

```yml
debug-topology:
  dormant: false
  swj: true
  debugports:
    - dpid: 0
      jtag:
        tapindex: 0
      swd:
        targetsel: 0
      accessports:
        - apid: 0
          index: 0
```

There are two sources for values:

1. Using [\<debug\>](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_debug) element.
   - `__ap` attribute adds more accessports, where index=ap value.  The value apid=ap;
   - if `__ap` is used `__dp=0` is required and does add any new information.

2. Using \<accessportV1\>, \<accessportV2\>, and \<debugport\> element in PDSC.
