### ISSUE TITLE
cbuild-run.yml: system-descriptions: contains same file multiple times

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2043]
**Describe the bug**

The MCXN947 dual core example lists the cmsis_vio.svd file twice. 

We need to add pname information for svd files, as svd files may relate to just one target.
Type needs to become an array in case that the same svd file is used in multiple projects that refer different pname's.

```yml
  system-descriptions:
    - file: ${CMSIS_PACK_ROOT}/NXP/MCXN947_DFP/19.0.0/devices/MCXN947/MCXN947_cm33_core0.xml
      type: svd
      pname: cm33_core0
    - file: ${CMSIS_PACK_ROOT}/NXP/MCXN947_DFP/19.0.0/devices/MCXN947/MCXN947_cm33_core1.xml
      type: svd
      pname: cm33_core1
    - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Driver/VIO/cmsis_vio.scvd
      type: scvd
    - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS-RTX/5.9.0/RTX5.scvd
      type: scvd
    - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Driver/VIO/cmsis_vio.scvd   # file listed twice
      type: scvd
```

**Comment by brondani** [comment]
Note the duplicated file is not an `svd` but an `scvd` file for the `CMSIS Driver:VIO` API.
There are probably multiple components that implement this API being added to the solution, for example `CMSIS Driver:VIO:Custom` and `CMSIS Driver:VIO:Virtual`.

**Comment by ReinhardKeil** [comment]
Yes this component is in two projects

**Comment by brondani** [comment]
Fixed in https://github.com/Open-CMSIS-Pack/devtools/pull/2044 present in [CMSIS Toolbox nightly #444](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/runs/14394311789#artifacts)

**Comment by jkrech** [comment]
Using cmsis toolbox nightly: csolution 2.8.0+p37-gfd5df25b the output is correct:

```
  system-descriptions:
    - file: ${CMSIS_PACK_ROOT}/NXP/MCXN947_DFP/19.0.0/devices/MCXN947/MCXN947_cm33_core0.xml
      type: svd
      pname: cm33_core0
    - file: ${CMSIS_PACK_ROOT}/NXP/MCXN947_DFP/19.0.0/devices/MCXN947/MCXN947_cm33_core1.xml
      type: svd
      pname: cm33_core1
    - file: ${CMSIS_PACK_ROOT}/ARM/CMSIS/6.1.0/CMSIS/Driver/VIO/cmsis_vio.scvd
      type: scvd
```
