### ISSUE TITLE
csolution: only add algorithms that have default set

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2047]
Currently all algorithms are added.  However there are devices that have optional algorithms (i.e. for connecting external memory). These algorithms are overlapping and should not be added by default.

Recommended change in v2.9:
 - csolution should only add algorithms that have attribute [default=true](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_algorithm) in the PDSC

Future improvements:
- csolution should get a command to list all algorithms that are registered. This might be a server command. VS Code could then get a similar dialog as we have today in uVision.

**Comment by ReinhardKeil** [comment]
The behavior is no clearified in https://github.com/ReinhardKeil/cmsis-toolbox/blob/main/docs/YML-CBuild-Format.md#programming

**Comment by brondani** [comment]
Implemented in https://github.com/Open-CMSIS-Pack/devtools/pull/2051, available in [CMSIS Toolbox nightly #448](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/actions/runs/14405963234#artifacts)

**Comment by jkrech** [comment]
```
cbuild-run:
  generated-by: csolution version 2.8.0+p37-gfd5df25b
...
  programming:
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/STM32L5x_512_0C00.FLM
      start: 0x0C000000
      size: 0x00080000
      ram-start: 0x20000000
      ram-size: 0x00008000
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/STM32L5x_512_0800.FLM
      start: 0x08000000
      size: 0x00080000
      ram-start: 0x20000000
      ram-size: 0x00008000
```

with 2.8.0 release also the onboard memory flash algorithms are displayed which do not have default attribute set.
```
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/MX25L51245G_STM32L5_OSPI.FLM
      start: 0x90000000
      size: 0x04000000
      ram-start: 0x20000000
      ram-size: 0x00008000
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/STM32L552E_EVAL_MX25L51245G.FLM
      start: 0x90000000
      size: 0x04000000
      ram-start: 0x20000000
      ram-size: 0x00008000
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/STM32L562E_DK_MX25L51245G.FLM
      start: 0x90000000
      size: 0x04000000
      ram-start: 0x20000000
      ram-size: 0x00008000
    - algorithm: ${CMSIS_PACK_ROOT}/Keil/STM32L5xx_DFP/1.4.0/CMSIS/Flash/STM32L5x_OPT.FLM
      start: 0x1FF00000
      size: 0x00000030
      ram-start: 0x20000000
      ram-size: 0x00008000
```

Fixed confirmed.
