### ISSUE TITLE
Layer Search requires that the pack is included in the solution

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#2089]
The problem description below is misleading.

Important is that the pack is listed in the csolution.yml or cproject.yml, otherwise layers are not searched.
This needs to be part of the documentation.

**Describe The Problem To Be Solved**

On my computer there is a development versions of the SDS pack registers with local pack 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<index schemaVersion="1.1.0">
 <vendor>local repository</vendor>
 <url>file://localhost/C:/Users/reikei01/AppData/Local/Arm/Packs</url>
 <pindex>
  <pdsc url="file://localhost/C:/w/SDS-Framework/" vendor="ARM" name="SDS" version="2.0.0-dev"></pdsc>
 </pindex>
</index>
```

Using csolution list layers, these layers are correctly reported.

```shell
>csolution list layers       
C:/Users/reikei01/AppData/Local/Arm/Packs/Keil/B-U585I-IOT02A_BSP/2.0.0/Layers/Default/Board.clayer.yml (layer type: Board)
 : 
C:/w/SDS-Framework/layer/sdsio/filesystem/sdsio_fs.clayer.yml (layer type: SDSIO)
C:/w/SDS-Framework/layer/sdsio/network/sdsio_network.clayer.yml (layer type: SDSIO)
C:/w/SDS-Framework/layer/sdsio/usb/sdsio_usb.clayer.yml (layer type: SDSIO)
```

Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.

However, these layers are not considered.  When configuring the SDS.csolution.yml with:

```yml
  # List different hardware targets that are used to deploy the solution.
  target-types:
    - type: STM32U585AIIx
      device: STM32U585AIIx
      board: B-U585I-IOT02A:Rev.C
    :
  packs:
    - pack: Keil::B-U585I-IOT02A_BSP
    - pack: Keil::STM32U5xx_DFP
```

Instead an error is reported.
```shell
csolution list layers SDS.csolution.yml                                
error csolution: undefined variables in SDS.csolution.yml:
  - $Board-Layer$
  - $SDSIO-Layer$
```

When adding the path it works as expected. However this considers also layers that are in the pack for other reasons (fvp layer).

```shell
csolution list layers SDS.csolution.yml -L c:\w\SDS-Framework
```

**Suggest A Solution**

The layers registered in the PDSC of local registered packs should be also considered. This would avoid that the pack needs to be installed and supports development of new packs.

**Duplicate**

Install the SDS development pack from https://github.com/ARM-software/SDS-Framework

**Version**
CMSIS-Toolbox 2.9
