### ISSUE TITLE
[csolution] no IAR version in cprj ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#217]
yml file:
```
  build-types:
    - type: AC6
      compiler: AC6
      misc:
        - C*:
          - -std=c99
    - type: GCC
      compiler: GCC
      misc:
        - C*:
          - -std=c99
    - type: IAR
      compiler: IAR
      misc:
        - C*:
          - -std=c99          
```

cprj file:
```
  <compilers>
    <compiler name="IAR" version="0.0.0"/>
  </compilers>
```

==> I would have expected version 8.50.6 as we have IAR.8.50.6.cmake
