### ISSUE TITLE
[solution] can we accept wild cards in for-type 

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#259]
I need to define build types for my project that do not depend only on the compiler:
```
  build-types:
    - type: AC6_UART
      compiler: AC6
      misc:
        - C*:
          - -std=c99
    - type: GCC_UART
      compiler: GCC
      misc:
        - C*:
          - -std=c99
    - type: IAR_UART
      compiler: IAR
      misc:
        - C*:
          - -std=c99
    - type: AC6_ITM
      compiler: AC6
      misc:
        - C*:
          - -std=c99
    - type: GCC_ITM
      compiler: GCC
      misc:
        - C*:
          - -std=c99
    - type: IAR_ITM
      compiler: IAR
      misc:
        - C*:
          - -std=c99  
```

So basically, it is compiler_function where function is either UART or ITM.

I tried this:
```
    - group: Simple Trace
      files:
        - file: ../Src/stm32_simple_trace_UART.c
          for-type: *_UART
        - file: ../Src/stm32_simple_trace_ITM.c
          for-type: *_ITM
```

But got this error:
```
> csolution.exe list dependencies -s test.csolution.yml
C:/Cube/simple_trace/internal/test.cproject.yml:29:21 - error csolution: yaml-cpp: error at line 29, column 21: the referenced anchor is not defined: _UART
```
