### ISSUE TITLE
[solution] add-paths rejected in files ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#260]
I tried this:
```
      files:
        - file: ./main.c
        - file: ./test.c
        add-paths: .
```

And got this:
```
> csolution.exe list dependencies -s test.csolution.yml
C:/Cube2/simple_ytrace/test.cproject.yml:26:9 - error csolution: yaml-cpp: error at line 26, column 9: end of map not found
```

Line 26, column 9 is the  beginning of  add-paths directive

**Comment by jkrech** [comment]
I am not sure whether you want to add the include for an individual file (test.c) or the whole group? Here is the whole group but you need to obeye the syntax in any case!
```
      files:
        - file: ./main.c
        - file: ./test.c
      add-paths: 
      - ./
```

**Comment by fred-r** [comment]
I think in the spec the "add-paths" is below "files"

**Comment by brondani** [comment]
It can be set for a [group](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#groups) and/or for a [file](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#files), but please observe the [add-paths](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#add-paths) format ( it must be an YAML sequence) and indentation.

For example in this way:
```
files:
  - file: ../../TEST.c
    add-paths:
      - .
```
Or in this way:
```
files:
  - file: ../../TEST.c
    add-paths: [ . ]
```
