### ISSUE TITLE
[solution] for-type not taken into account ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#261]
I have a csolution defining these build-types:
```
  build-types:
    - type: AC6_UART
      compiler: AC6
      misc:
        - C*:
          - -std=c99
    - type: GCC_UART
      compiler: GCC
      misc:
        - C*:
          - -std=c99
    - type: IAR_UART
      compiler: IAR
      misc:
        - C*:
          - -std=c99
    - type: AC6_ITM
      compiler: AC6
      misc:
        - C*:
          - -std=c99
    - type: GCC_ITM
      compiler: GCC
      misc:
        - C*:
          - -std=c99
    - type: IAR_ITM
      compiler: IAR
      misc:
        - C*:
          - -std=c99
```

Then mycproject is like this:
```
  components:
    - component: STMicrolectronics::Utility:Debug:simple trace&UART
      for-type: .GCC_UART, .IAR_UART, .AC6_UART
    - component: Utility:Debug:simple trace&ITM
      for-type: .GCC_ITM, .IAR_ITM, .AC6_ITM
    - component: Board Support&B-U585I-IOT02A:Board Resource
    - component: Device:STM32 HAL:Common
    - component: CMSIS:CORE
    - component: Device:STM32 HAL:Cortex
    - component: Device:STM32 HAL:RCC
    - component: Device:STM32 HAL:PWR
    - component: Device:STM32 HAL:GPIO
    - component: STMicroelectronics::Device:Startup
```

Then I do the check:
```
> csolution.exe list dependencies -s test.csolution.yml -c test.GCC_UART+B-U585I-IOT02A
```

No error reported though I have not installed the pack with the simple_trace component.

If I do this change:
```
  components:
    - component: STMicrolectronics::Utility:Debug:simple trace&UART
      # for-type: .GCC_UART, .IAR_UART, .AC6_UART
    - component: Utility:Debug:simple trace&ITM
      for-type: .GCC_ITM, .IAR_ITM, .AC6_ITM
    - component: Board Support&B-U585I-IOT02A:Board Resource
    - component: Device:STM32 HAL:Common
    - component: CMSIS:CORE
    - component: Device:STM32 HAL:Cortex
    - component: Device:STM32 HAL:RCC
    - component: Device:STM32 HAL:PWR
    - component: Device:STM32 HAL:GPIO
    - component: STMicroelectronics::Device:Startup
```

Then:
```
> csolution.exe list dependencies -s test.csolution.yml -c test.GCC_UART+B-U585I-IOT02A
error csolution: no component was found with identifier 'STMicrolectronics::Utility:Debug:simple trace&UART'
error csolution: processing dependencies list failed
```

So, to me, it looks like the for-type is ignored in this case.
