### ISSUE TITLE
[solution] Did something wrong (again) with add-paths ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#263]
I tried this:
```
  groups:
    - group: Test code
      files:
        - file: ./main.c
        - file: ./test.c
        - file: ./main.h
        - file: ./test.h
          # add-paths: [.]
    - group: Generated code
      files:
        - file: ./targets/B-U585I-IOT02A/stm32_system.c
        - file: ./targets/B-U585I-IOT02A/stm32_usart1.c
        - file: ./targets/B-U585I-IOT02A/stm32_usart1.h
        - file: ./targets/B-U585I-IOT02A/stm32_target.h
        - file: ./targets/B-U585I-IOT02A/stm32u5xx_hal_conf.h
          # add-paths: [./targets/B-U585I-IOT02A]
```

With add-paths instead of file for the .h file I end-up with this:
```
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Cube/background/embsw_archi_studies/simple_trace/internal/test.AC6_UART+B-U585I-IOT02A_IntDir
[1/18] Building C object CMakeFiles/test.AC6_UART+B-U585I-IOT02A.dir/C_/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.o
FAILED: CMakeFiles/test.AC6_UART+B-U585I-IOT02A.dir/C_/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.o
C:\Keil_v5\ARM\ARMCLANG\bin\armclang.exe --target=arm-arm-none-eabi  -IC:/Cube/background/embsw_archi_studies/simple_trace/internal/RTE/Device/STM32U585ZITx -IC:/Cube/background/embsw_archi_studies/simple_trace/internal/RTE/Utility -IC:/Cube/background/embsw_archi_studies/simple_trace/internal/RTE/_test.AC6_UART_B-U585I-IOT02A -IC:/CMSIS_PACKS/ARM/CMSIS/5.8.0/CMSIS/Core/Include -IC:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_DFP/0.1.0-alpha1/Include -IC:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Inc -IC:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Inc/Legacy -IC:/CMSIS_PACKS/STMicroelectronics/board_resources_B-U585I-IOT02A/0.0.1 -IC:/Cube20/background/embsw_archi_studies/simple_trace/Inc -mcpu=Cortex-M33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DSTM32U585xx -D_RTE_ -DUSE_HAL_DRIVER   --target=arm-arm-none-eabi -c -std=c99 -isystem "C:/Keil_v5/ARM/ARMCLANG/bin/../include" -MD -MT CMakeFiles/test.AC6_UART+B-U585I-IOT02A.dir/C_/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.o -MF CMakeFiles\test.AC6_UART+B-U585I-IOT02A.dir\C_\CMSIS_PACKS\STMicroelectronics\STM32U5xx_Drivers\0.1.1\Src\stm32u5xx_hal.o.d -o CMakeFiles/test.AC6_UART+B-U585I-IOT02A.dir/C_/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.o -c C:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.c
In file included from C:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Src/stm32u5xx_hal.c:36:
C:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Inc\stm32u5xx_hal.h:30:10: fatal error: 'stm32u5xx_hal_conf.h' file not found
#include "stm32u5xx_hal_conf.h"
```

**Comment by brondani** [comment]
In your example you are adding include paths into the compilation of header files, it does not make much sense.

Looking at the error message it fails when compiling the file `stm32u5xx_hal.c` which I believe is part of the `Device:STM32Cube HAL:Common` component.
Assuming the missing file `stm32u5xx_hal_conf.h` is in the `./targets/B-U585I-IOT02A` folder, I guess you want the following:
```
components:
  - component: Device:STM32Cube HAL:Common
    add-paths: [./targets/B-U585I-IOT02A]
```

**Comment by fred-r** [comment]
But then, why add-paths in files ?

The spec says:
<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: inherit; padding: 0px 0.2em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">files:</code></h2>

files: |   | Content
-- | -- | --
- file: | Required | Name of the file.
for-type: | Optional | Include file for a list of build and target types.
not-for-type: | Optional | Exclude file for a list of build and target types.
optimize: | Optional | Optimize level for code generation.
debug: | Optional | Generation of debug information.
defines: | Optional | Define symbol settings for code generation.
undefines: | Optional | Remove define symbol settings for code generation.
add-paths: | Optional | Additional include file paths.
del-paths: | Optional | Remove specific include file paths.
misc: | Optional | Literal tool-specific controls.


</body>
</html>files:
files:		Content
[- file:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#file)	Required	Name of the file.
   [for-type:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#for-type)	Optional	Include file for a list of build and target types.
   [not-for-type:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#not-for-type)	Optional	Exclude file for a list of build and target types.
   [optimize:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#optimize)	Optional	Optimize level for code generation.
   [debug:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#debug)	Optional	Generation of debug information.
   [defines:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#defines)	Optional	Define symbol settings for code generation.
   [undefines:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#undefines)	Optional	Remove define symbol settings for code generation.
   [add-paths:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#add-paths)	Optional	Additional include file paths.
   [del-paths:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#del-paths)	Optional	Remove specific include file paths.
   [misc:](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#misc)	Optional	Literal tool-specific controls.

The hal_conf.h is not really linked to a component but more the project.

**Comment by brondani** [comment]
`add-paths` is not accepted for `files` (plural), but for a specific `file` (singular), for a specific `group` (which in practice is a group of files), for a specific `component`, as well as for a `project`, `layer`, `solution`, `built-type` and `target-type`.

**Comment by fred-r** [comment]
Ok, I get it, if I want add-paths for a set of files then I need to put it at group level.

My way of reading the spec was wrong, I thought that whatever was in the same table was at the same level.
In fact the "top" element has the "-" and the other elements in the table are "sub-elements" of this top item, ok.

**Comment by fred-r** [comment]
@brondani : I have one more question to make sure I understand how it works.

If I do this:
```
    - group: Generated code
      add-paths: [./targets/B-U585I-IOT02A]
      files:
        - file: ./targets/B-U585I-IOT02A/stm32_system.c
        - file: ./targets/B-U585I-IOT02A/stm32_usart1.c
        # - file: ./targets/B-U585I-IOT02A/stm32_usart1.h
        # - file: ./targets/B-U585I-IOT02A/stm32_target.h
        # - file: ./targets/B-U585I-IOT02A/stm32u5xx_hal_conf.h
          # add-paths: [./targets/B-U585I-IOT02A]
```

Then my compilation fails:
C:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Inc\stm32u5xx_hal.h:30:10: fatal error: 'stm32u5xx_hal_conf.h' file not found

But it works if I list the hal_conf.h file explicitely:
- file: ./targets/B-U585I-IOT02A/stm32u5xx_hal_conf.h

So I think that:
- if I use add-paths at group level it applies only for the group
- if I list the header file then it is available for the entire compilation flow (all components)

Then I tried at project level:
```
project:
  optimize: size                   # Code optimization: emphasis code size
  debug: on                        # Enable debug symbols
  add-paths: [.]
  add-paths: [./targets/B-U585I-IOT02A]
```

But I encounter the same compilation error:
C:/CMSIS_PACKS/STMicroelectronics/STM32U5xx_Drivers/0.1.1/Inc\stm32u5xx_hal.h:30:10: fatal error: 'stm32u5xx_hal_conf.h' file not found

So, how can I declare an include path for an entire project (all components) ?
