### ISSUE TITLE
Support project customized config file replacement of specific SW pack component

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#296]
When developers construct project, no matter from projmgr yml or CPRJ or keil .uvprojx, they need a way to use customized config file to replace provided config file for specific component from some certain SW pack.

Here is real case:
MK64F12 DFP provides component Board Support::SDK Project Template::project_template, like:
```xml
    <component Cclass="Board Support" Cgroup="SDK Project Template" Csub="project_template" Cvariant="MK64F12" Cversion="1.0.0" condition="device.MK64F12_AND___component.serial_manager_AND_utility.debug_console__OR_utility.debug_console_lite__AND_component.uart_adapter_AND_device.MK64F12_startup_AND_driver.adc16_AND_driver.clock_AND_driver.common_AND_driver.dspi_AND_driver.gpio_AND_driver.i2c_AND_driver.port_AND_driver.rtc_AND_driver.smc_AND_driver.uart" isDefaultVariant="1">
      <description>Devices_project_template MK64F12; {for-development:SDK-Manifest-ID: project_template.MK64F12.MK64F12}</description>
      <files>
        <file category="header" attr="config" name="project_template/board.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/board.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/clock_config.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/clock_config.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/pin_mux.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/pin_mux.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/peripherals.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/peripherals.c" version="1.0.0"/>
      </files>
    </component>
```
In one example, I need a specific pin mux configuration which is not provided by default pin mux.h inside Board Support::SDK Project Template::project_template. Under such condition, I prepare a pin_mux.h for this example. I need open CMSIS tools/KEIL IDE's to use this customized pin mux to replace existing one in SW when construct project.

I don't want any generator because I don't have generator. Many developers don't have either.
Many SW components will provide "config" head, but it is just default selection. Examples which involve these components often provide a customized one to replace it.

Something like this(a rough idea to demo the request):
```yaml
project:
  device: MK64FN1M0VLL12
  compiler: AC6
  components:
    - component: ARM::CMSIS:CORE
    - component: NXP::Device:CMSIS:MK64F12_header
    - component: NXP::Device:CMSIS:MK64F12_system
    - component: NXP::Device:SDK Drivers:clock
    - component: NXP::Device:SDK Drivers:common
    - component: NXP::Device:SDK Drivers:flash
    - component: NXP::Device:SDK Drivers:gpio
    - component: NXP::Device:SDK Drivers:lists
    - component: NXP::Device:SDK Drivers:port
    - component: NXP::Device:SDK Drivers:smc
    - component: NXP::Device:SDK Drivers:uart
    - component: NXP::Device:SDK Drivers:uart_adapter
    - component: NXP::Device:SDK Utilities:assert_lite
    - component: NXP::Device:SDK Utilities:debug_console_lite
    - component: NXP::Device:Startup
    - component: NXP::Board Support:SDK Project Template:project_template
  groups:
    - group: Source Files
      files:
        - file: ./source/hello_world.c
        - file: ./board/clock_config.h
          # type: config
          for_component: NXP::Board Support:SDK Project Template:project_template
```

**Comment by tcsunhao** [comment]
@fred-r 
```
"Looks like you want to modify a component content without using a generator."
```
Yes we don't want to use generator. My opinions are 1. generator way is one comparatively high threshold/complex way. Many developers don't have generator. 2. For many cases, config is only related to several Marco definitions difference, it is easier to directly provide a config file.

```
"Why is the config or template type not matching your needs ?
I mean your config file can be copied in your project (components section) or the template file can be copied in your user section.
Then, you adapt it."
```
It is one working scenario which needs your manually adapt generated project file as you mention "Then, you adapt it".  Your way is like "prepare yml + source code" => generation => open and adapt config in generated project => build.

What we expect and what we regularly doing is "prepare yml + source code + config code" => generation => build. It makes sense developers at the first step to finish the config by provide customized config file . Developers don't need to maintain output generated project file for later open and adapt. They just need to maintain "yml + source code + config code(if needed)" in the gitrepo in their daily development. When release, needed projects will be generated/tested/deliveried.

For CI, usually a vendor SDK has thousands of examples, it could be time consuming to launch generator again and again(maybe you have some dedicated optimization).

I think open CMSIS should support both scenarios. In component configuration(after component selection) in project construction, various ways should be supported for developers to choose based on their situation.

**Comment by fred-r** [comment]
What we expect and what we regularly doing is "prepare yml + source code + config code" => generation => build. It makes sense developers at the first step to finish the config by provide customized config file 

==> I agree with you that we need a way to deliver already configured code.
This "configured ocde" has been written manually by someone in your case (not a generator) and it has to be shared with other people, ok.
Today, the way to deliver code is via packs.

So to me what you want to do is:
- deliver a component with configuration files ==> already supported
- but also deliver modified configuration files for a given project ==> to me this is the purpose of adding layers in packs

@ReinhardKeil : what do you think ?

**Comment by jkrech** [comment]
@tcsunhao a cproject or clayer does not only contain the respective yml file as well as the project local modules, but also the "RTE" directory with the config files of all selected components. Whether or not these config files are "unchanged default" or "modified" config files is up to the maintainer of the cproject / clayer.
You could also specify multiple component variants which only differ in the settings in an otherwise identical configuration file, however I don't think this scales very well. The benefit of a pre-configured clayer is that it can provide aligned configuration settings across multiple components.

**Comment by ReinhardKeil** [comment]
@fred-r the delivery of pre-configured configuration files is indeed what we plan with layers in packs.

**Comment by tcsunhao** [comment]
@jkrech  Thanks for the explanation.
```
a cproject or clayer does not only contain the respective yml file as well as the project local modules, but also the "RTE" directory with the config files of all selected components. Whether or not these config files are "unchanged default" or "modified" config files is up to the maintainer of the cproject / clayer.
(Note: You could also specify multiple component variants which only differ in the settings in an otherwise identical configuration file, however I don't think this scales very well)
```
I have checked again the [PLM of configuration files](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#plm-of-configuration-files), so if 
```c
./RTE/component_class/ConfigFile.h
```
is prepared well under project structure root, then it will be used as customized project configuration for specific component, no yml settings needed, right(or Do I miss anything)?

**Comment by jkrech** [comment]
Your understanding is complete and correct.

**Comment by tcsunhao** [comment]
I have to reopen this issue.

My aim is to provide pre-configured project csolution/cproject in later NXP Open-CMSIS-Pack so that customers can directly import any demo projects to build/debug without any more step configuration as they do today. And I don't rely on "Generator". 
Directly, I need Open-CMSIS-Pack to provide a way to modify/replace(replace is better) default-provided "config" file of specific component for certain project. 
For the time being, there is way to achieve this which is preparing customized config file inside "RTE" folder of project. I think it is not a regular approach. The "RTE" folder should be generated by tools, please correct me if I have made a mistake.

I expect "delivery of pre-configured configuration files is indeed what we plan with layers in packs."

This feature is key to NXP middleware examples. Many NXP middleware component will provide a default "config" file, but it cannot meet many specific cases, so in many board examples, developers will provide a customized config file for certain component in projects.

**Comment by ReinhardKeil** [comment]
>This feature is key to NXP middleware examples. 

@tcsunhao we have the same goal here, and yes this is what layers should deliver. It should be possible to deliver a default "config" that fits for a layer.   We need however to develop the process to get to layers including distribution and maintenance.

This work most likely results in changes to the RTE directory.  

>Directly, I need Open-CMSIS-Pack to provide a way to modify/replace(replace is better) default-provided "config" file of >specific component for certain project.

I agree on that statement, and for that reason, the proposal https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/134 has already provisions for Product Life Cycle management. However there is still work to do in the detail, and IMHO we need a prototype to explore these details.

**Comment by tcsunhao** [comment]
Thanks @ReinhardKeil for the explanation. 
I have checked again the layer described in [layer](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#layer) and also check real case of layer inside https://github.com/ReinhardKeil/IoT_App. I get the impression that layer is pre-prepared data set(device/board/Component, etc) for csolution/cproject to invoke which means data/settings inside a layer actually can be directly placed under cproject/csolution directly as well. So I would think "customized component config file of project" can be irrelevant to layer, it is actually a setting related invoked components inside a project. Please correct me if I have made a mistake.

**Comment by tcsunhao** [comment]
Hi @ReinhardKeil and @jkrech, any updates for this topic? This is critical to NXP adoption for Open-CMSIS-Pack because of https://github.com/Open-CMSIS-Pack/devtools/issues/296#issuecomment-1189987003.

For project provided customized config file for certain component, yes we can put them in advance in "RTE" folder, tools(no matter Open-CMSIS-Pack or vendors tools) can take higher priority for config files inside prestored "RTE" over the same-name config file from component's Inside pack. But cproject/csolution yml should maintain such information so that all tools can get known config file status directly(data driven) instead of checking physical "RTE" folder on disk to find which config files are provided in advance, something like this way:
```yaml
project:
  device: MK64FN1M0VLL12
  compiler: AC6
  components:
    - component: ARM::CMSIS:CORE
    - component: NXP::Device:CMSIS:MK64F12_header
    - component: NXP::Device:CMSIS:MK64F12_system
    - component: NXP::Device:SDK Drivers:clock
    - component: NXP::Device:SDK Drivers:common
    - component: NXP::Device:SDK Drivers:flash
    - component: NXP::Device:SDK Drivers:gpio
    - component: NXP::Device:SDK Drivers:lists
    - component: NXP::Device:SDK Drivers:port
    - component: NXP::Device:SDK Drivers:smc
    - component: NXP::Device:SDK Drivers:uart
    - component: NXP::Device:SDK Drivers:uart_adapter
    - component: NXP::Device:SDK Utilities:assert_lite
    - component: NXP::Device:SDK Utilities:debug_console_lite
    - component: NXP::Device:Startup
    - component: NXP::Board Support:SDK Project Template:project_template
      RTE-config: clock_config.h # This line tells that project specific clock_config.h is put in advance in RTE folder to replace component one.
  groups:
    - group: Source Files
      files:
        - file: ./source/hello_world.c
```
SDK Project Template:project_template is defined like:
```xml
    <component Cclass="Board Support" Cgroup="SDK Project Template" Csub="project_template" Cvariant="MK64F12" Cversion="1.0.0" condition="device.MK64F12_AND___component.serial_manager_AND_utility.debug_console__OR_utility.debug_console_lite__AND_component.uart_adapter_AND_device.MK64F12_startup_AND_driver.adc16_AND_driver.clock_AND_driver.common_AND_driver.dspi_AND_driver.gpio_AND_driver.i2c_AND_driver.port_AND_driver.rtc_AND_driver.smc_AND_driver.uart" isDefaultVariant="1">
      <description>Devices_project_template MK64F12; {for-development:SDK-Manifest-ID: project_template.MK64F12.MK64F12}</description>
      <files>
        <file category="header" attr="config" name="project_template/board.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/board.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/clock_config.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/clock_config.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/pin_mux.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/pin_mux.c" version="1.0.0"/>
        <file category="header" attr="config" name="project_template/peripherals.h" version="1.0.0"/>
        <file category="sourceC" attr="config" name="project_template/peripherals.c" version="1.0.0"/>
      </files>
    </component>
```
cc: @fred-r
