### ISSUE TITLE
Use ARM assembler instead of GNU

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#312]
I try to build an example project for an older STM32F103 MCU. I use the official ST device startup. Compilation fails with

```
E:/GIT/gitlab/embedded/templates/uvision-template/build/generated-uv-projects/uvision-template.Debug+Production-HW/RTE/Device/STM32F103TB/startup_stm32f10x_md.s:2:2: error: unexpected token at start of statement
;* File Name          : startup_stm32f10x_md.s
```
(and much more errors)

It seems like `;` is a comment only in ARM assembler, so I guess the file is compiled as GNU assembler. How I change that?

csolution.yml:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/0.9.4/tools/projmgr/schemas/csolution.schema.json

solution:
  target-types:
    - type: Production-HW
      device: STM32F103TB

    # - type: Board
    #   board: NUCLEO-L552ZE-Q      # just an example

    # - type: Virtual
    #   board: VHT-Corstone-300     # Virtual Hardware platform (appears as board)

  build-types:
    - type: Debug
      compiler: AC6
      debug: on
      misc:
        - C*:
            - -O1
            - -g

    - type: Test
      compiler: AC6
      debug: on
      misc:
        - C*:
            - -O3

    - type: Release
      compiler: AC6
      misc:
        - C*:
            - -O3

# multiple projects can be used here!
  projects:
    - project: uvision-template.cproject.yml
```
cproject.yml:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/Open-CMSIS-Pack/devtools/schemas/projmgr/0.9.4/tools/projmgr/schemas/cproject.schema.json

project:
  groups:
    - group: src
      files:
        - file: ./src/te_main.c
        - file: ./src/file1.c

    - group: inc
      files:
        - file: ./inc/file1.h

    - group: Test-Interface
      for-type: .Test
      files:
        - file: ./test/test1.c

  components:
    - component: ARM::CMSIS:CORE@5.5.0
    - component: Device:Startup
    - component: Device:GPIO
    - component: Keil::Compiler&ARM Compiler:Event Recorder&DAP@1.5.1
    - component: Keil::Device:DMA
    - component: Keil::CMSIS Driver:CAN
    - component: ARM::CMSIS:DSP&Source          # not added for build type: Test
      not-for-type: .Test   
```
