### ISSUE TITLE
`execute` flag schema not correct

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#318]
According to https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#execute, it should be possible to run a post-build script like that:

```
solution:
  :
  :
  projects:
    - execute: Generate Keys for TF-M
      os: Linux
      run: KeyGen.exe
    - project: /security/TFM.cproject.yml
    - project: /application/MQTT_AWS.cproject.yml
    - execute: Copy output files
      run: cp *.out .\output
```

but at least in VSCode, an error in schema validation is thrown:

![image](https://user-images.githubusercontent.com/12893844/166701405-e0e878b2-61c5-47b6-901d-691c14d97a5e.png)
![image](https://user-images.githubusercontent.com/12893844/166701434-60c854c9-c91f-4369-9f64-23ee29666910.png)

Am I missing something?
Thanks :)
