### ISSUE TITLE
Cproject/Csolution should support to specify connection/dependency between project and build-types

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#332]
For example, take multicore example hello_world_cm4 and hello_world_cm0plus of LPC54114 as an example, the cm4 core hello_world binary will include(INCBIN)
cm0plus core hello_world binary. In NXP, we specify hello_world_cm4 depends on hello_world_cm0plus so that our tools know these 2 projects need to be constructed together and build with sequence.

Usually, it doesn't make sense if we only construct one project without the depended one because it cannot build/link pass anyway. It is convenient for customers/users to construct projects with dependency together once OR at least tools should info customers/users about the project dependency and give them tickbox to choose.

It is also important for CI, depended project should be built firstly otherwise there maybe errors.

This dependency should be extended to build-types too, if 4 build-types are provided:
```yaml
  build-types:
    - type: Debug
      compiler: AC6
    - type: Release
      compiler: AC6
    - type: DDR_Debug
      compiler: AC6
    - type: DDR_Release
      compiler: AC6
```

Tools should be able to know the relations like DebugVSRelease DDR_DebugVSDDR_Release explicitly and directly from the Cproject/Csolution yml data.

**Comment by jkrech** [comment]
@tcsunhao could you please read through the section about [access-sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#access-sequences). Note that due to the lack of the mcprj and required CMSIS-Build extensions to generate a CMakelists.txt covering all project contexts, this is only theory at the moment and we may miss support for use cases.

**Comment by jkrech** [comment]
@tcsunhao, in the last meeting I suggested to create an example where multiple dependent projects are shown.
We do have a testproject here:
https://github.com/Open-CMSIS-Pack/devtools/tree/main/tools/projmgr/test/data/TrustZoneSolution
In the project: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/test/data/TrustZoneSolution/NonSecureCode/NonSecure.cproject.yml line 8: you find a file reference
```
- file: $Output(Secure)$_CMSE_Lib.o
```
which is referencing the output file and folder from the 'Secure' project with the corresponding target- and build-type.

**Comment by tcsunhao** [comment]
@jkrech , I have to say that this kind reference/information to specify relations between 2 projects is not direct and clear enough. 
If I provide 2 pairs examples inside the csolution yml, just a little different between them, then how to tell between them? 
```yaml
  projects:
    - project: ./SecureCode/Secure.cproject.yml
    - project: ./NonSecureCode/NonSecure.cproject.yml
    - project: ./SecureCode1/Secure1.cproject.yml
    - project: ./NonSecureCode1/NonSecure1.cproject.yml
```

What our tool/IDE expect is straight information, so that at the first step without analyze the data we can know about project relations to show:
![image](https://user-images.githubusercontent.com/3381677/169784530-b1407fde-ff5b-4f72-a184-2f9ab551f1d7.png)
