### ISSUE TITLE
YML : for-type cannot be used to control defines ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#345]
Looks like for-type does not apply to defines.

How can we control the compiler switches for the various build-types ? (like release/debug)

**Comment by jkrech** [comment]
@fred-r could you please give an example.
e.g. defines could be specified in the scope of the build-type definition

see: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#build-types

But I guess you have a different need.

**Comment by jkrech** [comment]
Maybe this is what you are trying to achieve to limit the define e.g. to a component (or group or file) and yet make it specific to a certain build type.

```
components:
    - component: CMSIS:CORE
      for-type: .Release
      defines:
        - foo=1
    - component: CMSIS:CORE
      for-type: .Debug
      defines: 
        - bar=1
```

**Comment by fred-r** [comment]
Hi Joachim,

yes the build-type can do the job and it is probably the best option.

Actually my point was to say that for a given build-type defined at solution level, then each cproject may tune the switches.

So I was looking for something like:
```
project:
  defines:
    - USE_FEATURE_X
      for-type: .debug
```
