### ISSUE TITLE
csolution and for-type

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#347]
In my cproject.yml:
```
    - group: GCC_sys
      for-type: .GCC, .GCC_STATUS
      files:
        - file: ./syscalls.c
```

gives:
```
.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x16): undefined reference to `_exit'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
error cbuild: error executing 'cmake' build
```

because syscalls.c is not compiled.

If I have only one build type:
```
    - group: GCC_sys
      for-type: .GCC
      files:
        - file: ./syscalls.c
```

then it succeeds:
```
info cbuild: build finished successfully!
```

Finally, this works:
```
    - group: GCC_sys
      for-type: .GCC
      files:
        - file: ./syscalls.c
    - group: GCC_sys2
      for-type: .GCC_STATUS
      files:
        - file: ./syscalls.c  
```

**Comment by tcsunhao** [comment]
for-type should support one line contains multiple types, like 
```
    - group: GCC_sys
      for-type: .GCC, .GCC_STATUS
      files:
        - file: ./syscalls.c
```
Of course delimiter can be different.
