### ISSUE TITLE
Proper way to support compiler specific sources, macro definitions, etc.

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#356]
There are many cases about compiler specific sources for one project.
One common example is linker. Based on existing mechanisms provided in csolution/cproject yml, followings are one way to support specify it:
Under cproject.yml, using for-type
```
    - group: linker
      files:
        - file: ./iar/MK64FN1M0xxx12_flash.icf
          for-type: +iar
        - file: ./mdk/MK64FN1M0xxx12_flash.scf
          for-type: +mdk
        - file: ./armgcc/MK64FN1M0xxx12_flash.ld
          for-type: +armgcc
```
under csolution.yml, define the target-type:
```
  target-types:
    - type: mdk
      device: MK64FN1M0VLL12
      compiler: AC6
    - type: iar
      device: MK64FN1M0VLL12
      compiler: IAR
    - type: armgcc
      device: MK64FN1M0VLL12
      compiler: GCC
```

However, there is a defect in such way, per my understand that, cproject is used to define project contents. csolution is used to define solution. So one cproject may need to be used in many csolutions. So if we used targets defined in one csolution in cproject, then if other csolution uses this cproject again, then it may needs to update the cproject yml data. This coupling between cproject and csolution affects the reuse of cproject.

Any other better/proper way to support compiler specific sources/files?

**Comment by tcsunhao** [comment]
Another possible compiler specific configuration is macro definitions. One real case is that In NXP MCUXpresso SDK project, sometimes in armgcc we define __STARTUP_CLEAR_BSS which is not needed in other compiler. Based on existing mechanism, one possible way is to define it under "target-types", like
```
  target-types:
    - type: mdk
      device: LPC55S69JEV98
      compiler: AC6
    - type: iar
      device: LPC55S69JEV98
      compiler: IAR
    - type: armgcc
      device: LPC55S69JEV98
      compiler: GCC
      defines:
        - __STARTUP_CLEAR_BSS
```
Again, I think this way couples target-type to certain compiler to contain compiler specific configuration.

Perhaps we could extend "MiscType" to add in "groups" and "defines" to support compiler specific sources/macros, maybe other more which may be compiler specific. So that we could use "MiscType" to contain all compiler specific stuffs.

**Comment by jkrech** [comment]
With the specification of a target-type and a build-type you have two dimensions of contexts you can create. Only the target-type can specify the HW, however everything else is up to the user to decide.
In the above example you can also specify the compiler as part of the build-types. In case of specifying `debug` and `release` build-types this doubles the number of build types.
One alternative is to use a cdefault.yml file where the compiler specific macro is being set.

**Comment by fred-r** [comment]
> So one cproject may need to be used in many csolutions.

I'm still not comfortable with this statement.
We also have the need for standalone projects:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/93

So, to me, csolution and cproject go "together".
I do not think a csolution should reference cprojects from anywhere.

**Comment by tcsunhao** [comment]
@fred-r , if csolution and cproject need to go "together", then why provide both csolution and cproject? Just one definition is enough.

I don't say csolution always should refer cproject from anywhere, but Open-CMSIS-Pack mechanism may need to provide alternatives to achieve this.

**Comment by tcsunhao** [comment]
@jkrech , do you have any real example about "One alternative is to use a cdefault.yml file where the compiler specific macro is being set.", thank you very much.

**Comment by tcsunhao** [comment]
@jkrech, I propose to extend MiscType to add "groups" and "defines" to support compiler specific sources and macro definitions.
```
    "MiscType": {
      "type": ["object", "null"],
      "properties": {
        "compiler":   { "$ref": "#/definitions/CompilerType" },
        "groups":     { "$ref": "#/definitions/GroupsType" },
        "defines":    { "$ref": "#/definitions/DefinesType" },
        "C":          { "$ref": "#/definitions/ArrayOfStrings", "description": "List of C flags" },
        "CPP":        { "$ref": "#/definitions/ArrayOfStrings", "description": "List of CPP flags" },
        "C*":         { "$ref": "#/definitions/ArrayOfStrings", "description": "List of C & CPP flags" },
        "ASM":        { "$ref": "#/definitions/ArrayOfStrings", "description": "List of ASM flags"  },
        "Link":       { "$ref": "#/definitions/ArrayOfStrings", "description": "List of Linker flags" },
        "Lib":        { "$ref": "#/definitions/ArrayOfStrings", "description": "List of Library Manager or Archiver flags" }
      },
      "additionalProperties": false
    }
```

Typical case is linker file and compiler specific macro definition:
```
  misc:
    - compiler: AC6
      defines:
        - <MDK specific>
      groups:
        - group: linker
          files:
          - file: ./mdk/MK64FN1M0xxx12_flash.scf
      C:
        - ......
      CPP:
        - ......
      Link:
        - ......
```
This is the easiest way I can think to support compiler specific data without coupling csolution and cproject.
