### ISSUE TITLE
Floating-point ABI

### ISSUE THREAD

**Issue by tarek-bochkati** [Open-CMSIS-Pack/devtools#359]
Currently in project format we have `fpu` enumeration under `ProcessorType`  node.

There is some cases where we need to explicitly specify the FP-ABI mode, to resolve linkage issues.
This could be solved by misc options, but this cannot solve the linkage issue with libraries coming from components.

So what we need to achieve is to introduce a new property `fp-abi` that precedes the `fpu` property and permitting to specify 
> whether to use hardware instructions or software library functions for floating-point operations, and which registers are used to pass floating-point parameters and return values.

```yaml
# `ProcessorType` is used in `TargetType`, `BuildType`, `SolutionDescType`, `ProjectDescType` and `LayerDescType`
"ProcessorType": {
  # ...
  "properties": {
    "fp-abi": {
      "enum": [ "soft", "hard", "mixed" ],
      "description": "Controls FP HW or SW instructions usage for floating-point operations,
                      and if FPU registers are used in function calls"
    },
    "fpu": {
      "enum": [ "on", "off" ],
      "description": "Controls usage of FPU registers (S-Registers that are used for Helium and FPU hardware): on | off"
    },
    # ...
  }
},
```

**Note** : there is a possibility that `fp-abi` can override the `fpu` property
| FP-ABI                                          | soft | hard | mixed | 
|:------------------------------------|:-----:|:-----:|:-------:|
| FPU instructions                          | off    | on   | on       | 
| FPU regs usage in function calls | off    | on    | off      |
