### ISSUE TITLE
Debug binaries created with `cbuild` in µVision

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#397]
I'm trying to debug an .axf file, generated by cbuild in ARM µVision. It loads properly but I can't set any breakpoints:

![image](https://user-images.githubusercontent.com/12893844/178798435-45562290-80b8-46e2-b2f3-5ea4cb850cac.png)

Build and linker options:

```
      misc:
        - C:
            - -O1
            # - -g # gdwarf-4
            - -gdwarf-3
            - -std=c99
            - -Wno-packed -Wno-missing-variable-declarations -Wno-missing-prototypes -Wno-missing-noreturn -Wno-sign-conversion -Wno-nonportable-include-path -Wno-reserved-id-macro -Wno-unused-macros -Wno-documentation-unknown-command -Wno-documentation -Wno-license-management -Wno-parentheses-equality
            - -ffunction-sections # for optimization
            # - -fno-function-sections # disable section optimization
            - -fno-rtti # compatibility to µVision
            - -funsigned-char
            # - -mfloat-abi=soft
            - -ffp-mode=std # do not use NAN or INF!
            # - -ffp-mode=full
            - -fno-short-enums # 32 bit enums
            - -fno-short-wchar # 32 bit wchars
            - -D__MICROLIB # define ONLY if using microlib in linker!
        - ASM:
            - -masm=auto
            - -D__MICROLIB # define ONLY if using microlib in linker!
        - Link:
            - --info=summarystack,stack,unused,sizes,any,common,debug,inputs,summarysizes,totals,veneers
            - --summary_stderr
            - --callgraph
            - --strict # more warnings
            - --list jlg-redundant-tilt.map
            - --scatter $Source(jlg-redundant-tilt)$/../jlg-redundant-tilt.sct
            - --library_type=microlib # define ONLY if using microlib in linker!
            - --debug
            - --any_sort_order=descending_size
            - --any_placement=worst_fit # https://developer.arm.com/documentation/100070/0612/linker-command-line-options/--any-placement-algorithm?lang=en
            - --sort=Lexical
            - --map
            - --load_addr_map_info
            - --xref
            - --symbols
            - --any_contingency
```

As you can see, I'm trying tons of flags to create compatibility with µVision generated files, but still no success :( 
The axf files and map files are also slightly different. 
Exactly the same code is used.

Any help is very much appreciated!

UPDATE: there seems to be a difference between Linux and Windows. We're building the firmware in a CI/CD pipeline on Linux and try to use µVision on Windows to debug them. This seems not to work. Even `cbuild` generates different binaries on both platforms. Is that intended?

Thanks
