### ISSUE TITLE
Access Sequence for RTE folder

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/devtools#409]
It would be great to have an [access sequence](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#access-sequences) to link to the current RTE folder, e.g. for manual config header files.

BTW, should `$Bname$`, `$Dname$` etc work with the current release? For me, only `$OutDir(project[.build-type][+target-type])$` seems to work.

**Comment by brondani** [comment]
@jankap Thanks for the suggestion concerning the RTE folder access sequence.
`$Bname$` and `$Dname$` should work with the current release, for example the following nodes in the cproject.yml:
```
  board: STM32F4-Discovery
  groups:
    - group: Source
      files:
        - file: $Bname$/$Dname$.c
```
result in the following section in the generated CPRJ:
```
  <files>
    <group name="Source">
      <file category="sourceC" name="STM32F4-Discovery/STM32F407VGTx.c"/>
    </group>
  </files>
```
If it does not work for you, could you please share a reproducer?
