### ISSUE TITLE
Could we get rid of compiler if `build-type` ?

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#411]
Looking at #355 &  [tools/projmgr/test/data/TestProjectSetup/setup-test.csolution.ym](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/test/data/TestProjectSetup/setup-test.csolution.yml) I was wondering if we could improve a bit still `build-type` related proposal if `csolution` in the light of `setup` & `for-compiler` introduction.

Right now having:
`  build-types:`
`    - type: Debug`
`    - type: Release`

is leading to `error csolution: compiler: value not set` processing `csolution` file

Considering #179 purpose is to get some compiler agnostic project files, sounds to me like a pain to force `compiler` requirement ...

I would promote **if "basic" project**:

- cdefault.yml
```
default:
  compiler: GCC
```
- csolution.yml
```
  build-types:
    - type: Debug
         debug: on
         optimize: none
    - type: Release
         debug: off
         optimize: size
```
- cproject.yml
```
<possibly nothing related to toolchain setup>
```
I would promote if **"complex"** project:
- cdefault.yml
```
<possibly nothing related to toolchain setup or something claiming running IDE is only supporting one toolchain kind ... >
```
- csolution.yml
```
  build-types:
    - type: .Debug
    - type: .Release
```
- cproject.yml
```
setups:
    - setup: AC6
      for-compiler: AC6
      misc:
        - C-CPP:
            - -std=c99
    - setup: GCC
      for-compiler: GCC
      misc:
        - C:
            - -std=gnu11
        - CPP:
            - -std=gnu++14
        - C-CPP:
            - -Og
    - setup: GCC.Debug
      for-compiler: GCC
      for-type: .Debug
      misc:
        - C-CPP:
            - -Og
    - setup: GCC.Release
      for-compiler: GCC
      for-type: .Release
      misc:
        - C-CPP:
            - -Os
    - setup: IAR
      for-compiler: IAR
```
