### ISSUE TITLE
*.cbuild-index.yml + *.cbuild.yml as long term replacement for *.CPRJ + Proposal for use as lockfile + Generator input

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#434]
This proposal is to replace (over time) the `*.CPRJ` file(s) with a single `*.cbuild.yml` file that:

 - contains the build instructions for the whole application.  A new `cbuild` tool could selectively generate one project or all projects.
 - uses controls that are identical with csolution.yml, but no `build/target types` (and the related `for-type:`)
 - compiler is fixed for a project (therefore no `for-compiler:`)
 - component files are explicitly stated (which removes the need to manage components at `cbuild` tool-level)
 - additional information (such as `from-pack:`) is stated for each component
 - `clayer.yml`/`cdefault.yml` information is included (no reference to other files - all self-contained in `*.cbuild.yml` file)
 - lists all `packs:` with explicit version number (this can be used as loop-back file to csolution tool to lock the pack versions)

The file would be generated by the `csolution` tool.

Example: 
```yml
# section that defines global setup for all projects (initally only packs: would be listed here)

  packs:  # all packs used in the projects (exception when a project uses a different pack version the packs: would be also under project)
    - pack: ARM::CMSIS@5.9.0
    - pack: ARM::CMSIS-Driver@2.7.2
    - pack: ARM::CMSIS-FreeRTOS@10.4.6
    - pack: ARM::mbedTLS@1.7.0
    - pack: AWS::AWS_IoT_Over-the-air_Update@3.0.0-Beta
    - pack: AWS::backoffAlgorithm@1.0.0-Beta
    - pack: AWS::coreJSON@3.0.0-Beta
    - pack: AWS::coreMQTT@1.1.0-Beta
    - pack: AWS::coreMQTT_Agent@1.0.1-Beta
    - pack: AWS::corePKCS11@3.0.0-Beta
    - pack: AWS::FreeRTOS-Plus-TCP@2.3.2-Beta
    - pack: Arm-Packs::PKCS11@1.0.0
    - pack: Keil::ARM_Compiler@1.3.0
    - pack: MDK-Packs::IoT_Socket@1.3.0
    - pack: MDK-Packs::TinyCBOR@1.0.1
    - pack: ARM::V2M_MPS3_SSE_300_BSP@1.2.0    # DFP and BSP packs might need some special handling
    - pack: Keil::STM32U5xx_DFP@2.0.0
    - pack: Keil::B-U585I-IOT02A_BSP@1.0.0

#project specific section; almost identical with cproject, except all types are explicit, components are expanded 

  project:  MQTT_MutualAuth_Demo.Debug+AVH_MPS4_Corstone-300
    compiler: AC6@6.18   

    board: B-U585I-IOT02A

    device: SSE-300-MPS3     # assuming that all projects use the same device

    add-paths:
      - ./config_files
      - ./amazon-freertos/demos/include
      - ./amazon-freertos/demos/network_manager
  
    defines:
      - CONFIG_CORE_MQTT_MUTUAL_AUTH_DEMO_ENABLED

    components:
      - component: ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M
        from-pack: ARM::CMSIS-FreeRTOS@10.4.6
        files:
          - file: %CMSIS_PACK_ROOT%/ARM/CMSIS-FreeRTOS/10.4.6/CMSIS/RTOS2/FreeRTOS/Source/ARM/clib_arm.c
          - file: %CMSIS_PACK_ROOT%/ARM/CMSIS-FreeRTOS/10.4.6/CMSIS/RTOS2/FreeRTOS/Source/cmsis_os2.c
          - file: %CMSIS_PACK_ROOT%/ARM/CMSIS-FreeRTOS/10.4.6/CMSIS/RTOS2/FreeRTOS/Source/os_systick.c
      - component: ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2
        from-pack: ARM::CMSIS-FreeRTOS@10.4.6
        files:
          - file: ./RTE/RTOS/FreeRTOSConfig.h
            config-version: 1.2.3                   # identifies local config files along with version number

      - component: ARM::Security:mbed TLS
        from-pack: ARM::mbedTLS@1.7.0
        defines:
          - MBEDTLS_CONFIG_FILE="aws_mbedtls_config.h"
        files:
          ..

    groups:
      - group: Documentation
        files: 
          - file: ./README.md
      - group: main
        files:
          - file: ./app_main.c
          - file: ./tfm_ns_interface_freertos.c

  project: # next project
```

Note: this example is inspired by https://github.com/MDK-Packs/TrustZone

There are for sure things to be discussed such as:
  - why a single file for all build/target-types: this makes it easier to use it as loop back file.  Selection of projects to build could be at cbuild tool-level instead.
  - should we add options to build just a selection of build/target-types: perhaps - not sure about this
  - as this file is generated by the `csolution` tool, a back-up of the `*.cbuild.yml` could be used to identify the effect of changes in the `csolution` input file(s).

**Comment by slhultgren** [comment]
To connect the dots with https://github.com/Open-CMSIS-Pack/devtools/issues/119 I'll try to give some feedback.

# cbuild.yml and lockfile usage
* I think I agree that it might be a good thing to use a format closer to the csolution/cproject format, although the extreme case that was raised in 119 is that: If we include everything about build in this file, why not instead just generate a CMakeLists.txt directly that relies on $CMSIS_PACK_ROOT variables and relative paths, where important information is stored in CMake-variables that could be parsed and used by csolution tooling as loop back? Maybe we should consider this as well, effectively it would even eliminate the need for another tool.
* The `packs` list I suppose also can point to local packs with `relative paths` as in the csolution.yml today?
* For `components` and `files` I think we should also keep the `conditionid` stored since this helps with uniquely identifying which component of the PDSC was used. Can be helpful when creating packs to debug conditions, and during review to see which parts of the project actually changes. I would propose to extend the ComponentID format with a `#` separator for the conditionid part, basically extend [current](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Format.md#component-name-conventions) to
  * `[Cvendor::] Cclass [&Cbundle] :Cgroup [:Csub] [&Cvariant] [@[~ | >=]Cversion] [#conditionid]`
  * For files, the `condition` property could be added
* `constructed` files should somehow be visible here as well, (RTE_Components.h, RTE_PreInclude.h etc)
* I think we should also show the origin ComponentID reference so that it is trivial to see that e.g. `CMSIS:RTOS2` from the YML resolved to `ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M`


# Generator input file usage
The format in this issue is also a good fit for the generator input file to replace the current [`*.generate.yml`](https://github.com/Open-CMSIS-Pack/devtools/blob/1bb0c166d3e85a550a958409c2e2e3b05262977d/tools/projmgr/src/ProjMgrYamlEmitter.cpp#L62) file if we do the following changes when using it for the generator input file specifically:
* Only a single project context would be listed
* All Packs should point to `absolute paths`, no CMSIS_PACK_ROOT lookup should be necessary
* Each component should also have the `generator` kept from the PDSC definition so that the generator can identify its' own components
* Files should keep all information from PDSC, so `attr`, `category`, path in pack, and RTE-Path. (Only conditionally true files should be included)

**Comment by jkrech** [comment]
Regarding `CMSIS_PACK_ROOT` my suggestion is to include a line in the lockfile somewhere at the beginning reporting the value of the variable at the time the file got processed. So at least the information is preserved and could become useful for tools (e.g. generators) to use the same CMSIS_PACK_ROOT value. I am not sure yet whether to make the storing optional due to your privacy concerns. How real are these?

**Comment by ReinhardKeil** [comment]
We discussed that in technical review meeting on 30. Aug.
- we will use *.yml format and not implement CMakeLists.txt output
- we will use %CMSIS_PACK_ROOT% as an abstract path to the global pack directory of the host comput

Problems with a generator will be reviewed once we have the first version of the file available.

**Comment by jkrech** [comment]
We are closing this issue now and plan to develop the lockfile writer based on the documentation here: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-CBuild-Format.md

**Comment by brondani** [comment]
Feedback concerning the [current proposed format](https://github.com/Open-CMSIS-Pack/devtools/blob/78c0abe36fd652531314748b26a3a0a85f194f99/tools/projmgr/docs/Manual/YML-CBuild-Format.md) of the cbuild.yml file:
- The `projects`/`project` keywords refer actually to project contexts.
Isn't it inconsistent to reuse these keywords since they are already used in csolution.yml?
- Each project context may require different packs, but in cbuild.yml there is only a common list of `packs` valid for the whole solution.

**Comment by ReinhardKeil** [comment]
>The projects/project keywords refer actually to project contexts. Isn't it inconsistent to reuse these keywords since they are already used in csolution.yml?

Agreed, we should rename projects/project to contexts/context.

> Each project context may require different packs, but in cbuild.yml there is only a common list of packs valid for the whole solution.

Under `build:` a list of common packs is presented (packs that can be used across the csolution).  However, each context may have a separate pack list.

**Comment by jkrech** [comment]
Let's keep it open for capturing additional feedback. Once we have a PR we should move discussions there.

**Comment by slhultgren** [comment]
A few more comments on [the current proposed format](https://github.com/Open-CMSIS-Pack/devtools/blob/78c0abe36fd652531314748b26a3a0a85f194f99/tools/projmgr/docs/Manual/YML-CBuild-Format.md)

* `selected-by: MyProject.cproject.yml#55` A reference is a good thing, but line numbers are a bit too detailed I think and will likely be out-of-date/needing update a lot more frequently than keeping only the `component reference` i.e. `CMSIS:CORE` here, e.g.
  ```yml
    components:
    - component: ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M
      from-pack: ARM::CMSIS-FreeRTOS@10.4.6
      selected-by: CMSIS:RTOS2:FreeRTOS   # What was written in the component list in cproject.yml
  ```
  so I would vote for removing the optional "file#num" part
* `output-dirs` should have the `rtedir` and `gendir` properties as well I believe
* `local-repository` if this is absolute path, then the .cbuild.yml will not easily be shareable. So would the recommendation be here that `if you want to share your cbuild.yml, don't use local_repository.pidx`?
* `%CMSIS_PACK_ROOT%` usage may be misleading for `project local packs` (not talking about local_repository.pidx). This seems a bit more generic:
```yml
component-files:
      - file: %PACK_LOCATION%/CMSIS/RTOS2/FreeRTOS/Source/ARM/clib_arm.c
```
Or we could allow both forms of strings



# Generator input file version of `cbuild.yml`
It would be very nice if the following properties of the cbuild.yml would always be expanded to absolute paths:
* All packs in the pack list would have the `path` property set with absolute paths, both for local packs and for "installed" packs.
* All files use resolved values for `%PACK_LOCATION%` / `%CMSIS_PACK_ROOT%`
* `path to cproject file` should be there as well
* `path to csolution file` should be there as well
* `destination` property should be there (from `output-dirs[gendir]` from current context, so could be skipped if the full output-dirs is provided in the context already)
* the generator input file might not include all contexts (maybe only one at a time?)
