### ISSUE TITLE
how to compile a library project ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#542]
if we describe a library project through a cproject.yml, how can we generate the binary today ?

**Comment by brondani** [comment]
Example:
```yml
---
# csolution.yml
solution:
  compiler: AC6
  packs:
     - pack: ARM::CMSIS
  projects:
    - project: library.cproject.yml
    - project: app.cproject.yml

---
# library.cproject.yml
project:
  device: ARMCM0
  output-type: lib
  components:
    - component: ARM::CMSIS:CORE
  groups:
    - group: Files
      files: 
        - file: library.c
        - file: interface.h

---
# app.cproject.yml
project:
  device: ARMCM0
  output-type: exe
  groups:
    - group: Files
      files:
        - file: main.c
        - file: interface.h
        - file: $Output(library)$.lib
```
Command line to convert and build this solution:
`csolution -s csolution.yml convert && cbuild library.cprj && cbuild app.cprj`
