### ISSUE TITLE
Proposal `output-dir:` -> `output:`, add control for `target-name:`, rename `intdir:` -> `tmpdir:`, change in default settings

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#558]
Currently there is no way to control the output name (target-name) of the project.

My suggestion for [`output-dir:`](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output-dirs) is therefore to change it as below (with default settings):

```yml
output:                          # was previously `output-dir:`
   build-dir: $ProjectDir$       # was previously `cprjdir`, specifies directory of `*.CPRJ`, `*.cbuild.yml` files, default location of the `*.cproject.yml`
   rte-dir: $ProjectDir$/RTE     # specifies directory for RTE configuration files.
   tmp-dir: $ProjectDir$/tmp/$TargetType/$BuildType   # was previously `intdir:`, but default is `tmp` as directory name
   out-dir: $ProjectDir$/out/$TargetType/$BuildType   # specifies the directory for the build output
   target-name: $Project$        # specifies the base name of the output files
```
>Note: the proposal also adds `-` before `dir:` to make it easier to understand.

As a result of this proposal, I suggest to add to [Access Sequences](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#access-sequences) the following

Access Sequence                                | Description
:----------------------------------------------|:--------------------------------------
`$ProjectDir$`                                      | Directory path to the `*.cproject.yml` file; always refers to the currently processed project file

 This changes would simplify further the directory structure.
