### ISSUE TITLE
[csolution] Add separate 'define' and 'add-path' for assembler files (`define-asm`, `add-path-asm`)

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#607]
Macro defines under 'define' is populated into all sub compilers. For example, if we have following 'setup'
```yaml
  setups:
    - setup: AC6
      for-compiler: AC6
      for-type: .debug
      defines:
      - DEBUG
      - CPU_MK64FN1M0VLL12
      - PRINTF_FLOAT_ENABLE=0
      - SCANF_FLOAT_ENABLE=0
      - PRINTF_ADVANCED_ENABLE=0
      - SCANF_ADVANCED_ENABLE=0
      - FRDM_K64F
      - FREEDOM
      - MCUXPRESSO_SDK
```

If we build with -v, we can get this 
```
[2/21] C:\Keil_v5\ARM\ARMCLANG\bin\armclang.exe  -ID:/ocpa1/unzipped_packs/FRDM-K64F_BSP/demo_apps/hello_world/RTE/mdk/_hello_world.debug_mdk -IC:/opencmsispackroot/ARM/CMSIS/5.8.0/CMSIS/Core/Include -IC:/opencmsispackroot/NXP/MK64F12_DFP/14.0.0 -IC:/opencmsispackroot/NXP/MK64F12_DFP/14.0.0/components/lists -IC:/opencmsispackroot/NXP/MK64F12_DFP/14.0.0/components/uart -IC:/opencmsispackroot/NXP/MK64F12_DFP/14.0.0/drivers -IC:/opencmsispackroot/NXP/MK64F12_DFP/14.0.0/utilities/debug_console_lite -ID:/ocpa1/unzipped_packs/FRDM-K64F_BSP/demo_apps/hello_world -mcpu=Cortex-M4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mlittle-endian -DCPU_MK64FN1M0VLL12 -D_RTE_ -DDEBUG -DPRINTF_FLOAT_ENABLE=0 -DSCANF_FLOAT_ENABLE=0 -DPRINTF_ADVANCED_ENABLE=0 -DSCANF_ADVANCED_ENABLE=0 -DFRDM_K64F -DFREEDOM -DMCUXPRESSO_SDK  --target=arm-arm-none-eabi -c -c -o CMakeFiles/hello_world.debug+mdk.dir/D_/ocpa1/unzipped_packs/FRDM-K64F_BSP/demo_apps/hello_world/RTE/mdk/Device/MK64FN1M0VLL12/startup_MK64F12.o D:/ocpa1/unzipped_packs/FRDM-K64F_BSP/demo_apps/hello_world/RTE/mdk/Device/MK64FN1M0VLL12/startup_MK64F12.S
```
You can see that all 'defines' are populated into assemble startup_MK64F12.S which is obviously unnecessary and wrong. 

One way to avoid this is to use MiscType because MiscType has sub compiler categories like asm/c/cpp. It is mentioned in https://github.com/Open-CMSIS-Pack/devtools/issues/276.
However, sine all toolchains: MDK/IAR/Eclipse based all support such asm/c/cpp sub compiler categories, then we can regard that asm/c/cpp specific defines are commonly and widely used in embedded world. At least for assemble and c, they usually don't share macro defines which means we have to move all macro defines into MiscType, and it makes the common 'define' useless. And to define macros inside MiscType is unconvenient and indirect.

The same issue applis for include path.

Suggestion: support asm/c/cpp specific defines and macros like
asm-define
c-define
cpp-define
asm-include
c-include
cpp-include
