### ISSUE TITLE
Maps between target-types and build-types are missing

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#608]
Maps between target-types and build-types are missing

The NXP Open-CMSIS-Pack cproject/csolution could be like this way:

cproject.yml
```yaml
---
project:
  device: MK64FN1M0VLL12
  components:
  - component: NXP::Device:SDK Utilities:debug_console_lite
    ...
  groups:
  - group: source
    files:
    - file: boards/src/demo_apps/hello_world/hello_world.c
  - group: board
    files:
  - group: MK64F12/iar
    files:
    - file: devices/MK64F12/iar/MK64FN1M0xxx12_flash.icf
      for-type:
      - ".debug"
      - ".release"
      for-compiler:
      - IAR
  - group: MK64F12/arm
    files:
    - file: devices/MK64F12/arm/MK64FN1M0xxx12_flash.scf
      for-type:
      - ".debug"
      - ".release"
      for-compiler:
      - AC6
  - group: MK64F12/gcc
    files:
    - file: devices/MK64F12/gcc/MK64FN1M0xxx12_flash.ld
      for-type:
      - ".debug"
      - ".release"
      for-compiler:
      - GCC
  setups:
  - setup: IAR
    for-compiler: IAR
    for-type: ".release"
    misc:
    - ASM:
      C:
      CPP:
  - setup: IAR
    for-compiler: IAR
    for-type: ".debug"
    misc:
    - ASM:
      C:
      CPP:
  - setup: AC6
    for-compiler: AC6
    for-type: ".release"
    misc:
    - ASM:
      C:
      CPP:
      Link:
  - setup: AC6
    for-compiler: AC6
    for-type: ".debug"
    misc:
    - ASM:
      C:
      CPP:
      Link:
  - setup: GCC
    for-compiler: GCC
    for-type: ".debug"
    misc:
    - ASM:
      C:
      CPP:
      Link:
  - setup: GCC
    for-compiler: GCC
    for-type: ".release"
    misc:
    - ASM:
      C:
      CPP:
      Link:
```

csolution.yml
```yaml
solution:
  target-types:
    - type: mdk
      compiler: AC6
    - type: armgcc
      compiler: GCC
    - type: iar
      compiler: IAR

  output-dirs:
    outdir: ./$TargetType$/$BuildType$
    rtedir: ./RTE/$TargetType$

  build-types:
    - type: debug
    - type: release


  projects:
    - project: hello_world.cproject.yml
```

This way is generally compatible with NXP SDK database.
But there are some examples that different compilers don't share same build-types.
In some cases(real world case), IAR/MDK support ram_0x1400_debug/ram_0x1400_release/debug/release, but armgcc just supports debug/release. Looks like there is no way in exsiting mechanism to support such cases because build-types are for all target-types. Obviously, armgcc+ram_0x1400_debug and armgcc+ram_0x1400_release cannot build passed.

Suggestion: add for-type inside build-types to specify the target-types OR add for-type inside target-types to specify the build-types

**Comment by mcgordonite** [comment]
Is it possible to use the (not-)for-type filter on the project level for this? For example, if mdk is not compatible with debug:
```yaml
solution:
  target-types:
    - type: mdk
    - type: iar
  build-types:
    - type: debug
    - type: release
  projects:
    - project: hello_world.cproject.yml
      not-for-type: +mdk.debug
```
If I understood correctly, that could be functionally what you need if not especially clear semantically.
