### ISSUE TITLE
[csolution] Provide a way to further specify build output: format and filename in cproject/csolution

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#618]
We have such data in csolution.yml
```yaml
solution:
  target-types:
    - type: mdk
      compiler: AC6

  build-types:
    - type: debug
      defines:
        - DEBUG
      misc:
        - compiler: AC6
          C*:
            - -g
            - -O1
    - type: release
      defines:
        - NDEBUG
      misc:
        - compiler: AC6
          C*:
            - Oz

  output-dirs:
    outdir: ./$Project$/$TargetType$/$BuildType$
    rtedir: ./RTE/$TargetType$
```

The build outputs are:
hello_world_s/iar/debug/hello_world_s.debug+iar.bin
hello_world_s/iar/debug/hello_world_s.debug+iar.clog
hello_world_s/iar/debug/hello_world_s.debug+iar.hex
hello_world_s/iar/debug/hello_world_s.debug+iar.out
hello_world_s/iar/debug/hello_world_s.debug+iar_CMSE_Lib.o

For the final object/binary name, debug+iar(build-type+target_type) is unnecessary, for example, hello_world_s.debug+iar_CMSE_Lib.o should be renamed to hello_world_s_CMSE_Lib.o ($Project$_CMSE_Lib.o). In hello_world_ns, what is linked is hello_world_s_CMSE_Lib.o

Is there any way to achieve that in cproject/csolution data setting?
