### ISSUE TITLE
Feedback: *.genlayer.yml proposal lacks option to specify dependencies on components

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#637]
todo

**Comment by ReinhardKeil** [comment]
@slhultgren does this solve the fundamental issue?

**Comment by iomint** [comment]
Reinhard,
One comment: To my understanding in your example above 'component' is pointing to software components, I think it is interesting to put this in perspective with the proposal from my ST colleagues posted in the [issue #182](https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/182)

**Comment by ReinhardKeil** [comment]
Eric,

So, you would suggest to specify also `hardware-part:` in addition to `component:`.   Maybe it should be named `hw-component:` so that all is applicable under `components:`.  Below is a possible example:

```yml
generator:
  generated-by: STM32CubeMX <command-line>
  for-device: STM32F407IGHx    # only for consistency check
  for-board: NucleoF407        # only for consistency check

  packs:                       # packs that are used by the generator (consistency check, but may supply version information)
    - pack: Keil::STM32F4xx_DFP@2.16.1
    - pack: Keil::STM32F4xx_BSP@2.1.1

  components:               # components that have a genid and are specified in *.cproject.yml / *.clayer.yml must be in this list
                            # but additional components can be supplied by the generator
    - component: Device:STM32Cube HAL:Common
      require:                                           # here both components are required
        - component: CMSIS:CORE
        - hw-component: ST::USART-COM               
        - component: Device:Startup 
      deny:                                               # using this component would create an error at csolution convert
        - component: CMSIS:DSP
    - component: Board:LED
      require:
         - component: Driver:GPIO, Virtual-Driver:GPIO    # either Driver:GPIO or Virtual-Driver:GPIO is required
    - component: Device:HAL:UART
    - hw-component: ST::I2S               
      require: 
        - component: Driver:I2S
```

**Comment by jkrech** [comment]
I recommend to replace the term `hw-component` with the `part` since this is the term we are using the [Open-CMSIS-Pack Specification](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_parts_pg.html). Probably it should be listed under `parts:` rather than `components:`

**Comment by ReinhardKeil** [comment]
Yes there are several options to specify parts.  We just should agree on one.

Here the version with `part:` instead of `hw-component`.  

```yml
generator:
  generated-by: STM32CubeMX <command-line>
  for-device: STM32F407IGHx    # only for consistency check
  for-board: NucleoF407        # only for consistency check

  packs:                       # packs that are used by the generator (consistency check, but may supply version information)
    - pack: Keil::STM32F4xx_DFP@2.16.1
    - pack: Keil::STM32F4xx_BSP@2.1.1

  components:               # components that have a genid and are specified in *.cproject.yml / *.clayer.yml must be in this list
                            # but additional components can be supplied by the generator
    - component: Device:STM32Cube HAL:Common
      require:                                           # here both components are required
        - component: CMSIS:CORE
        - part: ST::USART-COM               
        - component: Device:Startup 
      deny:                                               # using this component would create an error at csolution convert
        - component: CMSIS:DSP
    - component: Board:LED
      require:
         - component: Driver:GPIO, Virtual-Driver:GPIO    # either Driver:GPIO or Virtual-Driver:GPIO is required
    - component: Device:HAL:UART
    - part: ST::I2S               
      require: 
        - component: Driver:I2S
```

Another way might be to extend the name convents for components to specify parts.

```yml
generator:
  generated-by: STM32CubeMX <command-line>
  for-device: STM32F407IGHx    # only for consistency check
  for-board: NucleoF407        # only for consistency check

  packs:                       # packs that are used by the generator (consistency check, but may supply version information)
    - pack: Keil::STM32F4xx_DFP@2.16.1
    - pack: Keil::STM32F4xx_BSP@2.1.1

  components:               # components that have a genid and are specified in *.cproject.yml / *.clayer.yml must be in this list
                            # but additional components can be supplied by the generator
    - component: Device:STM32Cube HAL:Common
      require:                                           # here both components are required
        - component: CMSIS:CORE
        - component part{ST::USART-COM}
        - component: Device:Startup 
      deny:                                               # using this component would create an error at csolution convert
        - component: CMSIS:DSP
    - component: Board:LED
      require:
         - component: Driver:GPIO, Virtual-Driver:GPIO    # either Driver:GPIO or Virtual-Driver:GPIO is required
    - component: Device:HAL:UART
    - component: part{ST::I2S}               
      require: 
        - component: Driver:I2S
```
