### ISSUE TITLE
IAR linker file extension '.icf' is not supported by projmgr exe 

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#667]
IAR linker file extension '.icf' is not supported by projmgr which results in IAR project build failure.

In cproject yml, we have 
```yaml
  - group: MIMXRT1064/iar
    files:
    - file: iar/MIMXRT1064xxxxx_ram.icf
      for-type:
      - ".debug"
      - ".release"
      for-compiler:
      - IAR
    - file: iar/MIMXRT1064xxxxx_sdram.icf
      for-type:
      - ".sdram_debug"
      - ".sdram_release"
      for-compiler:
      - IAR
    - file: iar/MIMXRT1064xxxxx_flexspi_nor.icf
      for-type:
      - ".flexspi_nor_debug"
      - ".flexspi_nor_release"
      for-compiler:
      - IAR
```

In the translated cprj, the data is 
```xml
    <group name="MIMXRT1064/iar">
      <file category="other" name="iar/MIMXRT1064xxxxx_ram.icf"/>
    </group>
```
file category shall be 'linkerScript'.
