### ISSUE TITLE
csolution: `device: <dname>:<pname>` and `$Dname$` placeholder

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#675]
There is an inconsistency in the dynamic placeholder `$Dname$` when a user explicitly defines the processor name for a target like this:
```yaml
solution:
target-types:
    - device: ARMCM33:CM33_0
      type: CM33
```
And later wants to use the placeholder `$Dname$` to refer to device specific files like this:
```yaml
project:
  groups:
    - group: main
      files: 
        - file: $Dname$_ac6.sct
```
The placeholder expands to `ARMCM33:CM33_0` containing invalid file name character `:`.

We need to clarify about the content of `$Dname$`:
- Either it is really just the device name, i.e., `ARMCM33`, and we add `$Pname` in case someone needs the processor name.
- Or the `:` character needs to be replaced with `_` when the placeholder is used for a file/directory name.
