### ISSUE TITLE
[csolution] Add support for linker script preprocessing in cproject.yml and cbuildgen

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#705]
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/655
Overview: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Linker-Script-Management.md
Linker node:
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#linker

Step one: manual specification of script running pre-include pre-processing with existing/user specified `regions_<device>.h` or `regions_<board>.h`

**Comment by jkrech** [comment]
Included in CMSIS-Toolbox starting 1.7.0

**Comment by jkrech** [comment]
@ReinhardKeil could you please add this new node to the documentation:

Under `misc:` a node `Library:` was added to the schema and processing.

example:
```
 build-types:
    - type: Debug
      compiler: GCC
      misc:
        - Library:
          - -lm
          - -lc
          - -lgcc
          - -lnosys
```

schema:
```
"Library": { "$ref": "#/definitions/ArrayOfStrings", "description": "List of Linker flags for libraries handling" },
```
