### ISSUE TITLE
[RTE Model/csolution] Add generator files from selected components to cbuild.yml (extended: FileCategoryType)

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/devtools#722]
Implements: https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/168
Specification: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileCategoryEnum
New component files which are exclusively for use by the associated generator:
`category="genSource"`
`category="genHeader"`
`category="genParams"`
`category="genAsset"`

These files need to be added by csolution to the cbuild.yml file which is passed via `$G` to the generator launch command line.

**Comment by edriouk** [comment]
@jkrech, where in cbuild .yml should those files be added? Do we have actual schema with dedicated positions?

**Comment by jkrech** [comment]
As far as I can see, these files belong to `files` under `generator:` within the `- component:`
```
  components:
    - component: Keil::Device:STM32Cube Framework:STM32CubeMX@1.1.0
      condition: STM32L4
      from-pack: Keil::STM32L4xx_DFP@2.6.1
      selected-by: Device:STM32Cube Framework:STM32CubeMX
      files:
        - file: RTE/Device/STM32L476RGTx/STCubeGenerated/Src/stm32l4xx_hal_msp.c
          category: source
      generator:
        id: STM32CubeMX
        files:
          - file: ${CMSIS_PACK_ROOT}/Keil/STM32L4xx_DFP/2.6.1/MDK/CubeMX/run_STM32CubeMX.c
            category: source
            version: 1.0
          - file: ...
            category: genSource
          - file: ...
            category: genHeader
          - file: ...
            category: genParams
          - file: ...
            category: genAsset

       ...

```

Please review!
