### ISSUE TITLE
[buildmgr] GNU Linker flags order when linking libraries (e.g., libmath)

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/devtools#735]
Projects that require additional libraries to be linked (such as libmath `-lm`) currently fail to build with GCC due to "wrong" command line flag ordering:
```
ARMCM0.GCC/math_helper.c:103: undefined reference to `log10'
```

The reason is the today such additional linker flags can only be provided through misc flags:
```yaml
    - type: GCC
      compiler: GCC
      misc: 
        - Link: 
          - -lm
```

All misc flags are put in front (before all the user objects) of the linker command line. To solve this linker issue, one would need to put the libraries to the end (behind the user objects) of the command line.

We might need to enhance the yaml syntax to specify required libraries explicitly and map them to `target_link_libraries` in CMake instead of `LINK_FLAGS`. The yaml could look like the following:
```yaml
    - type: GCC
      compiler: GCC
      misc: 
        - Library: 
          - m
```
