### ISSUE TITLE
[projmgr] Open door to vendor specific data (& processing) addon

### ISSUE THREAD

**Issue by VGRSTM** [Open-CMSIS-Pack/devtools#83]
As common good practice we have to find a way to allow vendor specific data addon to project manager metadata (*.yml files).
See https://github.com/Open-CMSIS-Pack/devtools/pull/77/files#r787702533

Intention is to get Open-CMSIS project manager as smart as possible but just incase we cannot anticipate all vendor specific corner cases / integration context etc. 
Even thinking continuous improvement of devtools, sounds nice to consider a contributor may first Thanks some official backdoor validate (possibly in production) its future addon to main solution.

I guess if we want to ensure a robust solution, no choice, *.yml stuff has to be validated up front against a schema. So I do not foresee any chance to support custom material addon to common basis. 

Do we have then to add as an option which is part of main schema some include like statement ? Such include statement may allow to get a vendor specific *.\<vendor\>.yml close to and referenced by related main *.yml file.

`solution:`
`- project: ./SWProject_1/SWProject_1.cproject.yml`
`- project: ./SWProject_2/SWProject_2.cproject.yml`
**`vendor-extension: ./.extended.csolution.yml`**

Today produces `.csolution.yml:4:1 - warning projmgr: key 'vendor-extension' was not recognized`
Good is no blocking process but long run I would prefer to block it (more robust) preventing at same time spurious trace.
Primary *.yml has to be validated strictly against an Open-CMSIS schema. Vendor specific part if under vendor responsibility.

**Comment by ReinhardKeil** [comment]
I would like to understand this proposal.  Is it basically a suggestion to add in each *.yml file the possibility to add a section "vendor-extension:" as shown below.  This would of course apply to *.csolution.yml, *.cproject.yml, and *.clayer.yml files.

```yml
solution:
  compiler: AC6

  target-types:
    - type: Board
      board: NUCLEO-L552ZE-Q

    - type: Production-HW
      device: STM32L552XY         # specifies device

    - type: Virtual
      board: VHT-Corstone-300     # Virtual Hardware platform (appears as board)
      
  build-types:
    - type: Debug
      optimize: debug
      debug: on

  vendor-extension:                   # start of vendor extensions
                                                  # a section that is not checked by the tool
```

**Comment by VGRSTM** [comment]
@ReinhardKeil yes purpose is to add "vendor-extension:". My proposal including a vendor specific file is way I foresee to support addon without breaking schema check.

**Comment by ReinhardKeil** [comment]
We could do something similar like misc: https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#misc

```yml
extensions:                   # start of extensions section          
   - vendor: ST               # extensions specific to vendor ST
     any-key: value           # key/value pairs for this vendor
```

This would allow for vendor specific extension in the *.yml file that could be interpreted differently, but I'm unsure if we should actually use `- vendor` or `- tool` as I believe extensions will be tool specific and perhaps less vendor specific.

We might be better of, to do it like this (even when this looks like a detail right now).

```yml
extensions:                   # start of extensions section          
   - tool: STCube             # extensions specific to tool
     any-key: value           # key/value pairs for this vendor
```

If we agree, next step would be to ask the team to investigate in feasibility. Maybe we should also consider to use the `misc:` section instead and add a `-tool: value` to it. `misc:` is already planned and seems the more natural place to me.
