### ISSUE TITLE
[csolution] Support standard cpp regex regular expressions in context condition specification

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#840]
It might be useful to have the ability to specify * to match any string in ‘for-context’ and in ‘not-for-context’.

Use case:  A fixed layer with Debug and Release libraries
``` yml
    - component: Keil::Network&MDK-Plus:CORE&IPv4 Debug
      for-context: .*Debug
    - component: Keil::Network&MDK-Plus:CORE&IPv4 Release
      not-for-context: .*Debug
```
A generic application would typically have a ‘Debug’ and ‘Release’ build type. But it could have different build types, ex: ‘Socket Debug’, ‘VCom Debug’, ‘Socket Release’, ‘VCom Release’, …

If we would prescribe that a build type containing ‘Debug’ at the end would indicate that also fixed layers would use a debug variant (which might provide Event Recorder Events as it is case with our MDK-Middleware)
