### ISSUE TITLE
cdefault.yml, map file

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#841]
1. To get meaningful context in the map file, the misc options can be used in `.cdefault.yml:`

```yml
  misc:
    - for-compiler: AC6
      Link:
        - --map     // suggest to add this directive to .cdefault.yml
```

2. a meaningful `cdefault.yml` file should go into directory .\etc. 

3. the path to the `cdefault.yml` file should be listed with the command `list config`

4. Open issue: How to achieve this with GCC without explicitly specifying a fixed name in the ‘misc’ options?  By default no map file is generated when using GCC.

**Comment by JonatanAntoni** [comment]
I have the following in some of the projects so far:
```
default:
  compiler: GCC

  misc:
    - for-compiler: GCC
      C:
        - -std=gnu11
      Link:
        - --specs=nano.specs
        - --specs=rdimon.specs

    - for-compiler: AC6
      C-CPP:
        - -ffunction-sections
        - -Wno-macro-redefined
        - -Wno-pragma-pack
        - -Wno-parentheses-equality
      C:
        - -std=gnu11
      Link:
        - --entry=Reset_Handler
        - --map
        - --info summarysizes

    - for-compiler: IAR
      C-CPP:
        - --dlib_config DLib_Config_Full.h
      Link:
        - --semihosting
```

Settings like semihosting (e.g. `--specs`) are somewhat project specific. Hence, I doubt *the* global `.cdefault.yml` can be achieved. We need to clearly decide and document how we assume users to customize. I guess the approach is to have reasonable defaults in `etc` and ask the user to copy the file into the solution folder if required. Should this default include semihosting?
