### ISSUE TITLE
cbuild.yml : cprj file is not correct

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#891]
Issue started to be discussed in #860 

hal_gpio_exti.csolution.yml
```
  target-types:
    - type: B-U585I-IOT02A
  build-types:
    - type: AC6
  projects:
    - project: ./hal_gpio_exti.cproject.yml
  output-dirs:
    intdir: $BuildType$
    outdir: $BuildType$
```

There is some issue in the generated `hal_gpio_exti.AC6+B-U585I-IOT02A.cbuild.yml`
"AC6+B-U585I-IOT02A.cprj" => should be "hal_gpio_exti.AC6+B-U585I-IOT02A.cprj"
