### ISSUE TITLE
Rework `output:` and `output-type:` node

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#895]
I personally believe we should rework [output](https://github.com/ReinhardKeil/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#output) and provide the following:

```yml
output:   # request generation of output artificats
  - base-name: <base-file-name> # for all output artifacts
  - type: hex   # generate a HEX file 
  - type: bin   # generate a BIN file 
    offset:     # potential options for BIN file generation
```

There is also an option to combine `output-type:` and `output:` as when requesting `type: lib` there is a conflict when at the same time `elf:` is requested.  So we could have `elf` as default, that is overwritten by `lib` (making it the impossible to request `bin` and  `hex`

To select library as output, it would be:

```yml
output:
  - type: lib
```

This would generate an error:

```yml
output:
  - type: lib
  - type: hex    # impossible to generate a hex file when type: lib is selected
```
