### ISSUE TITLE
What is the link between a layer and its type ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/devtools#918]
I can see these layer types: board, socket
And the related access-sequences maybe ? 

```
  layers:
    - layer: $Board-Layer$
      type: Board
    - layer: $Shield-Layer$
      type: Shield

```

So what are we allowed to use ?
Free strings ?
How are the access-sequences built ? Or is it variables ?
https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#variables

Are we allowed to have several times the same layer type ?

So basically everything is user-controlled ?
We  define the variables that match the types ?

**Comment by jkrech** [comment]
@fred-r this is variables - as you already point the the documentation of them.
Assume that you have a set of projects in your solution. Instead of changing the filenames of the clayers in all referenced cproject files they just use the same variable names. Also you don't need to specify different sets of layer names per target-type as the variables get set for each target-type.
```
  target-types:
    - type: frdmk22f_agmp03
      board: NXP::FRDM-K22F
      variables:
        - Board-Layer:  ../../../../../boards/frdmk22f/frdmk22f.clayer.yml
        - Shield-Layer: ../../../../../shields/agmp03/agmp03.clayer.yml
    - type: lpcxpresso54114_agmp03
      board: NXP::LPCXpresso54114
      device: NXP::LPC54114J256BD64
      variables:
        - Board-Layer:  ../../../../../boards/lpcxpresso54114/lpcxpresso54114.clayer.yml
        - Shield-Layer: ../../../../../shields/agmp03/agmp03.clayer.yml
```
The variable names themselves have no particular semantic, but good names help the readability.

_Are we allowed to have several times the same layer type ?_
No, the algorithm combining the layers is expecting a set of distinct layer type names under `layers:`, even if two had the same `connections`.
One thing we are discussing at the moment is whether we should be able to mark a layer optional. E.g. if a required sensor is mounted on the board and no shield is required. Having the same sensor on the board as well as on a shield will create a problem, since the connections are point to point (unique) in this case, whereas multiple drivers could make use of a delay function by the provided RTOS.

_We define the variables that match the types ?_
Yes, if you set the variable to a layer that does not match the type, `csolution` will throw an error, since the layer specifies which type it implements.
