### ISSUE TITLE
[csolution] Files are not included, as `for-compiler:` is incorrectly placed (bug in schema checker 3rd party lib)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#927]
This seems to be a schema problem in csolution.  It was expected that the two different `files:` sections are included.  No error is issued, instead no files are included for GCC.

```yml
layer:  
  description: Printf retarget for CMSDK

  groups:
    - group: Printf retarget
      for-compiler: AC6
      files:
        - file: stdout_UART.c
        - file: retarget_io.c
      
      for-compiler: GCC
      files:
        - file: stdout_UART.c
        - file: retarget_gcc.c
```

Correct way to use it is:

Option 1:

```yml
layer:  
  description: Printf retarget for CMSDK

  groups:
    - group: Printf retarget
      for-compiler: AC6
      files:
        - file: stdout_UART.c
        - file: retarget_io.c
         
   - group: Printf retarget 
      for-compiler: GCC
      files:
        - file: stdout_UART.c
        - file: retarget_gcc.c
```

Option 2:

```yml
layer:  
  description: Printf retarget for CMSDK

  groups:
    - group: Printf retarget
      files:
        - file: stdout_UART.c
        - file: retarget_io.c
          for-compiler: AC6
        - file: retarget_gcc.c
          for-compiler: GCC
 ```
