### ISSUE TITLE
How to set customized "RTE" root folder in open CMSIS toolbox 2.0.0_dev0

### ISSUE THREAD

**Issue by tcsunhao** [Open-CMSIS-Pack/devtools#947]
In open CMSIS toolbox 1.7.0, we use the following way to set customized RTE root folder:
```yaml
solution:
  packs:
  - pack: NXP::MK22F51212_DFP
  - pack: ARM::CMSIS
  target-types:
  - type: iar
    compiler: IAR
  - type: mdk
    compiler: AC6
  - type: armgcc
    compiler: GCC
  output-dirs:
    outdir: "./$TargetType$/$BuildType$"
    rtedir: "./$TargetType$/RTE"
  build-types:
  - type: release
  - type: debug
  projects:
  - project: hello_world.cproject.yml
```
For each compiler/toolchain, we provide one copy customized RTE for middleware to avoid messing up RTE files with all compilers/toolchains.

In open CMSIS toolbox 2.0.0_dev0, "rtedir" is not supported and I don't find any other ways to specify "RTE" root.
If I remove "rtedir", then "RTE" is generated with cproject.yml, and for our startup component with 3 different start up assemble files for 3 different compilers, only one start up assemble is added which result in build failure:

```xml
    <component Cclass="Device" Cgroup="Startup" Csub="" Cversion="1.1.0" condition="device.MK22F51212_startup.condition_id">
      <description>Device MK22F51212_startup</description>
      <files>
        <file condition="allOf.toolchains.f7a7af2513d7e86f1d51b.condition_id" category="sourceAsm" attr="config" name="devices/MK22F51212/iar/startup_MK22F51212.s" version="1.1.0" projectpath="startup"/>
        <file condition="allOf.toolchains.d3c5cd56afaad9c4e3962.condition_id" category="sourceAsm" name="devices/MK22F51212/gcc/startup_MK22F51212.S" projectpath="startup"/>
        <file condition="allOf.toolchains.fa1dc03f3792855ec22d8.condition_id" category="sourceAsm" attr="config" name="devices/MK22F51212/arm/startup_MK22F51212.S" version="1.1.0" projectpath="startup"/>
      </files>
    </component>
```
![image](https://github.com/Open-CMSIS-Pack/devtools/assets/3381677/72cf5cd8-f61d-4709-9b4b-68464eeaede9)

So what is the way in open CMSIS toolbox 1.0.0 to set customized "RTE", we don't want to mix all compiler RTE config into one folder.
