### ISSUE TITLE
Version Specification / Schema Check Mismatch

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/devtools#954]
Several elements allow to specify versions.  For example it is possible to specify (which perfectly works):

**(A - Works)**

```yml
packs:
    - pack: NXP::K32L3A60_DFP@16.0.0
    - pack: NXP::FRDM-K32L3A6_BSP@16.0.0
```

**(B - Fails at Schema Check)** However it is also possible to specify:
```yml
packs:
    - pack: NXP::K32L3A60_DFP@~16
    - pack: NXP::FRDM-K32L3A6_BSP@~16
```

This seems to work fine for the csolution convert step when schema check is disabled, but does not pass the schema check. It is therefore obviously an issue in the current schema definition.

**(C - Fails at Schema Check, gap in documentation)** But, I believe also this should be possible (and effectively identical):
```yml
packs:
    - pack: NXP::K32L3A60_DFP@16
    - pack: NXP::FRDM-K32L3A6_BSP@16
```

Here every version that is higher than 16.0.0 but lower than 17.0.0 should be accepted.  This is currently missing in the documentation.  The csolution tool seems to work, but schema check fails again.

Potential Actions:
  - Confirm that csolution tool implementation copes with all variants described above.
  - Fix the problems in the schema validation for (B) and (C)
  - Fix the documentation for (C)
