### ISSUE TITLE
Misc options from cproject are missing in the generated cprj file

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/devtools#973]
Hi

With my cproject file like this:
```
project:
  device: STM32U585AIIxQ
  processor:
    trustzone: off
  setups:
    - setup: GCC
      for-compiler:
        - GCC
      misc:
      - C:
          - -fdata-sections
          - -ffunction-sections
          - -std=gnu11
          - -Wall
          - -fstack-usage
```

C options are not present in the generated cprj file (in cflags)

regards,

**Comment by brondani** [comment]
@jeromecoutant Only with this code snippet I cannot reproduce the issue. The options appear normally in the cprj:
```
<cflags add="-fdata-sections -ffunction-sections -std=gnu11 -Wall -fstack-usage" compiler="GCC"/>
```
Maybe there are multiple `setup` being considered for a single context? Would you be able to share a complete reproducer or at least the full `setups` section?

**Comment by jeromecoutant** [comment]
Yes, I would like to configure multiple setup

```
solution:
  build-types:
    - type: GCC-Release
      compiler: GCC
    - type: GCC-Debug
      compiler: GCC

```

```
project:
    - setup: Debug
...
    - setup: Release
...
    - setup: GCC
...


```
